import express, { type Express, type Router } from "express";
import type { UpstreamClient, UpstreamHealth } from "./upstream.js";
import type { TickerStatus } from "./automation/ticker.js";

export interface GatewayDeps {
  readonly upstream: UpstreamClient;
  // The chat-automation API (POST/GET/DELETE /api/automations). Optional so the P0 health
  // topology can be built without it; mounted under /api when provided.
  readonly automationRouter?: Router;
  // The mission API (POST /api/missions/plan — read-only plan + real-company match).
  // Optional; mounted under /api when provided.
  readonly missionRouter?: Router;
  // Pure AI canvas planning. Independent of upstream companies and Agent execution.
  readonly canvasPlannerRouter?: Router;
  // The per-agent conversation API (POST /api/conversations/:companyId/agents/:agentId/messages
  // — SSE stream of a real conversation turn with a hired agent). Optional; mounted under /api.
  readonly conversationRouter?: Router;
  // The mission DISPATCH API (POST /api/missions/dispatch — delegate ONE approved
  // track to a matched company's agent, a real cross-company mutation). Separate
  // from the read-only mission planner. Optional; mounted under /api when provided.
  readonly missionDispatchRouter?: Router;
  // Browser SSO identity verification (GET /api/auth/me). It receives the user's
  // ClawHunt bearer token and returns an identity-only projection.
  readonly clawHuntAuthRouter?: Router;
  // Live scheduler status for /health readback (design doc §liveness: the UI must never
  // optimistically claim an automation "will run" — it reads this back). Optional.
  readonly automationStatus?: () => TickerStatus;
  // Per-launch identity (generated by the gateway itself on boot). Served on the fast
  // /gateway-id route (NOT /health, which awaits upstream) so a launcher can confirm liveness
  // independently of upstream health.
  readonly instanceId?: string;
}

export interface GatewayHealthPayload {
  readonly ok: true;
  readonly service: "superclaw";
  readonly upstream: UpstreamHealth;
  readonly automation?: TickerStatus;
  readonly instanceId?: string;
}

/**
 * Build the /health payload.
 *
 * The top-level `{ ok: true, service: "superclaw" }` is a verbatim mirror of
 * the Python `/health` shape (apps/api/main.py:3519) so the gateway is a
 * drop-in front door. The extra `upstream` field is a P0 diagnostic extension
 * (not part of the Python contract) that proves the gateway -> upstream wiring
 * — the "接电" vertical slice.
 *
 * The gateway reports ok=true even when the upstream is down: gateway liveness
 * and upstream liveness are distinct, and the upstream field carries the truth.
 */
export function buildHealthPayload(
  upstream: UpstreamHealth,
  automation?: TickerStatus,
  instanceId?: string,
): GatewayHealthPayload {
  return {
    ok: true,
    service: "superclaw",
    upstream,
    ...(automation ? { automation } : {}),
    ...(instanceId ? { instanceId } : {}),
  };
}

export function createGatewayApp(deps: GatewayDeps): Express {
  const app = express();
  app.disable("x-powered-by");

  // Fast liveness + identity — does NOT call upstream (unlike /health, which awaits it). The
  // co-launcher polls this for readiness and identity so a slow/stuck upstream can never make
  // a healthy gateway look down, nor a stale orphan look alive past its real liveness.
  app.get("/gateway-id", (_req, res) => {
    res.json({ ok: true, instanceId: deps.instanceId ?? null });
  });

  // The /api alias exposes the same read-only health through the browser proxy.
  app.get(["/health", "/api/health"], async (_req, res) => {
    const upstream = await deps.upstream.health();
    res.json(buildHealthPayload(upstream, deps.automationStatus?.(), deps.instanceId));
  });

  // These routers authenticate before parsing their bounded bodies. Mount them
  // before the older /api-wide parsers so those parsers cannot run before auth.
  if (deps.canvasPlannerRouter) {
    app.use("/api", deps.canvasPlannerRouter);
  }

  if (deps.conversationRouter) {
    app.use("/api", deps.conversationRouter);
  }

  if (deps.automationRouter) {
    app.use("/api", express.json(), deps.automationRouter);
  }

  if (deps.missionRouter) {
    app.use("/api", express.json(), deps.missionRouter);
  }

  if (deps.missionDispatchRouter) {
    app.use("/api", express.json(), deps.missionDispatchRouter);
  }

  if (deps.clawHuntAuthRouter) {
    app.use("/api", deps.clawHuntAuthRouter);
  }

  return app;
}
