// Generated by scripts/showcase/ from a recorded run; do not edit by hand.
import type { ProductionRunRecord } from '../productionRuns';

const record: ProductionRunRecord = {
  "caseId": "knowledge-base",
  "edition": {
    "zh": "AwwO 桌面版 · Codex 本地执行器（每个节点是一个可读写本地工作目录的 Codex 会话）",
    "en": "AwwO desktop · Codex local runtime (each node is a Codex session with its own local working directory)"
  },
  "runtime": "codex_local",
  "model": "Codex",
  "capturedOn": "2026-09-04",
  "seconds": 2664,
  "completed": 7,
  "total": 7,
  "outputLocale": "zh",
  "artifactNodeId": "frontend",
  "nodes": [
    {
      "id": "product",
      "title": {
        "zh": "产品边界与架构需求",
        "en": "Product scope & architecture"
      },
      "column": 0,
      "row": 0,
      "status": "done",
      "seconds": 351,
      "outputType": "fields",
      "fields": [
        {
          "id": "result",
          "value": "AWW-2 已完成并回读确认。已复用既有文档，对齐固定七节点：P产品边界、U用户登录与工作区权限、G文档数据治理、B后端接口、F知识库Web工作台、V交付验收、M上线物料。十二条连接：P→U/G/B/M，U→B/F，G→B/F，B→F/V，M→F，F→V。\n交付：[边界与验收文档](artifacts/knowledge-saas-boundary-v1.md)。接线契约和校验记录已同步留存到任务文档并回读一致。\n验证：节点、连接、端口引用、依赖无环及输出格式检查通过。未执行实现，未核验真实绑定、其他节点运行或功能联调。仅前端可制作无依赖index.html，须提供真实路径并标注模拟数据；所有节点仅返回声明字段JSON，每字符串≤1200字。不得安装依赖、访问外部业务系统、发送业务消息、发布或部署。"
        },
        {
          "id": "followups",
          "value": "待定：身份提供方、数据库、文档存储、搜索、前后端框架、部署环境、观测审计，以及文档规模、角色基线、保留恢复规则和性能目标。由用户及对应模块负责人在相关实现前确认。"
        }
      ]
    },
    {
      "id": "users",
      "title": {
        "zh": "用户登录与工作区权限",
        "en": "Login & workspace permissions"
      },
      "column": 1,
      "row": 0,
      "status": "done",
      "seconds": 301,
      "outputType": "fields",
      "fields": [
        {
          "id": "identity",
          "value": "AWW-3 已完成并标记 done，任务文档已回读一致。[完整契约](artifacts/identity-permissions-v1.md)定义账号、登录、会话撤销、邀请、成员生命周期和所有权转移。身份源待选；MFA、密码及会话参数明确列为实现前决策。会话设计参考[OWASP](https://cheatsheetseries.owasp.org/cheatsheets/Session_Management_Cheat_Sheet.html)。"
        },
        {
          "id": "permissions",
          "value": "已给出 Owner/Admin/Editor/Viewer × 工作区、成员、集合、文档、标签、看板、审计的动作矩阵。服务端逐请求校验成员状态和 workspace_id，默认拒绝；撤权后下一请求生效。搜索、摘要、计数与正文统一鉴权；审计限定本工作区读取，用户不可改删。首版不含资源私有ACL、跨工作区共享或计费。授权原则参考[OWASP](https://cheatsheetseries.owasp.org/cheatsheets/Authorization_Cheat_Sheet.html)。"
        },
        {
          "id": "checks",
          "value": "9项静态检查通过，输出字段及长度符合约定。已定义15项验收场景，覆盖登录退出、过期停用、邀请重放、跨租户越权、撤权并发、最后Owner、搜索泄漏及审计故障。全部功能验收为not_run；尚未实现认证服务或执行联调。契约沿既定U→B、U→F交接，设计完成不代表功能验收通过。"
        }
      ]
    },
    {
      "id": "data",
      "title": {
        "zh": "文档数据治理",
        "en": "Document data governance"
      },
      "column": 1,
      "row": 1,
      "status": "done",
      "seconds": 283,
      "outputType": "fields",
      "fields": [
        {
          "id": "schema",
          "value": "已完成[数据治理契约](artifacts/knowledge-governance-v1.md)，包含 Document、DocumentVersion、Collection、Category、Tag、Source、QualityRun、QualityFinding、AuditEvent 的字段类型、必填性、关系和约束。\n文档必须归属 workspace，collection 可空；记录责任人、创建者、更新者、来源、语言、状态、版本及时间。所有关联必须同工作区，责任人字段不授予权限。\n编辑追加不可变版本；已发布内容继续读取旧快照，新草稿不得泄漏标题、标签或正文。发布通过阻断规则后原子更新发布指针；revision 冲突返回409。归档与软删除退出普通检索。"
        },
        {
          "id": "quality",
          "value": "拟定阻断规则：发布必填元数据、非空正文、同租户引用完整、正文校验和一致、责任人有效。警告规则：重复标题、相同正文、超过配置期限；重复不自动合并，未配置过期阈值则标记未执行。\n质量结果绑定具体版本、规则版本、执行者、检查时间和证据；未检查或检查异常不得算通过。collection为空合法，破损引用才属于孤立数据。\n实际观察：未提供样本和现有字典，业务质量检查未执行，异常数量未知。已通过契约静态复核及JSON字段、字符串长度检查；未进行功能联调。"
        },
        {
          "id": "lineage",
          "value": "来源依据：AWW-2边界v1.1及AWW-4输入；producer_node=G，contract_version=1.0，evidence_level=design。\n人工文本/Markdown映射正文与版本快照；可信会话提供作者身份；Source记录来源和处理方式；质检与业务动作形成质量记录和审计。文件、富文本及外部同步仅保留扩展边界，未实际接入。\nU负责授权裁决，B执行，G定义治理规则，F展示。检索、详情、摘要、分页、计数及看板均须按当前权限过滤；首版不支持文档私有ACL或跨工作区共享。\n审计保留90天；正文、版本及来源的保留期另行确认。审批、恢复、物理清除、敏感识别与脱敏由产品负责人在相关实现前决策。\nAWW-4已标记done并读回确认；事项文档修订2与提交内容一致。本次完成设计交付，未实现或部署业务系统。"
        }
      ]
    },
    {
      "id": "materials",
      "title": {
        "zh": "知识库上线物料",
        "en": "Knowledge-base launch assets"
      },
      "column": 1,
      "row": 2,
      "status": "done",
      "seconds": 177,
      "outputType": "fields",
      "fields": [
        {
          "id": "assets",
          "value": "交付状态：AWW-5 已完成并回读确认；文案与素材规格完成，未写文件、生成设计或执行发布。\n来源：AWW-2 产品边界 v1.1。producer_node=M；contract_version=1.0；evidence_level=design。\n实际文案位置：本 JSON；AWW-5 交付评论 …。\n\n|物料|用途/页面|文案位置|状态|\n|---|---|---|---|\n|首页与登录|定位、登录入口|copy：home.*、auth.*|已提供|\n|工作台状态|工作区、检索、详情、编辑、看板、成员|copy：ws.* 至 demo.*|已提供|\n|使用指南|首次引导、帮助入口|下文|已提供|\n|品牌素材|页面视觉与素材选用|specifications|需求已定义，未制作|\n\n使用指南：\n\n1. 登录：选择页面提供的登录方式；登录失效后重新登录。\n2. 工作区：选择你已加入的工作区；尚未加入时联系管理员。\n3. 检索：输入关键词，按分类或标签筛选；无结果时修改关键词或清除筛选。\n4. 浏览与编辑：查看成员阅读已发布版本；编辑者及获授权管理员可创建草稿，填写标题、分类、负责人、来源引用和正文，保存并修正质检问题后发布。编辑已发布文档会创建新草稿，旧发布版继续可读。\n5. 数据看板：查看当前授权范围内的发布文档数和分类分布；待治理数仅对获授权角色展示。以页面标示的统计范围和时间为准。\n6. 成员与权限：管理员管理成员及角色；所有权转移由 Owner 操作，始终保留至少一名活跃 Owner。管理员不能移除或变更 Owner；查看成员不能编辑文档。\n\n前端消费方：F 知识库 Web 工作台；按 key 映射页面、权限及状态，记录物料覆盖情况。"
        },
        {
          "id": "copy",
          "value": "home.title：让团队知识有处可查\nhome.body：在工作区整理文档、维护发布版本，用关键词找到所需内容。\nhome.cta：登录工作台\nauth.hint：登录后选择你的工作区。\nauth.expired：登录已失效，请重新登录。\nauth.login：重新登录\nauth.failed：登录未成功，请重试。\nauth.disabled：账号已停用，请联系管理员。\nws.choose：选择工作区\nws.empty：你尚未加入工作区，请联系管理员。\ndoc.empty：暂无可查看的已发布文档。\ndoc.first：创建第一篇文档，保存草稿后完善发布信息。\ndoc.create：新建文档\nsearch.placeholder：输入关键词搜索文档\nsearch.empty：未找到符合条件的文档，请修改关键词或清除筛选。\nsearch.clear：清除筛选\ncommon.loading：正在加载…\ncommon.loadError：加载失败，请稍后重试。\ncommon.retry：重新加载\ncommon.forbidden：你无权执行此操作，请联系工作区管理员。\ndoc.unavailable：文档不可用。\ncommon.back：返回文档列表\ndoc.save：保存草稿\ndoc.saving：正在保存草稿…\ndoc.saved：草稿已保存。\ndoc.saveError：保存失败，请保留当前内容，稍后再试。\ndoc.unsaved：有尚未保存的修改，离开将丢失这些修改。\ndoc.stay：继续编辑\ndoc.leave：放弃修改并离开\ndoc.conflict：版本已更新。请先保留当前修改，再加载最新版本核对。\ndoc.invalid：暂不能发布，请根据提示修正必填信息或质检问题。\ndoc.publish：发布版本\ndoc.publishing：正在发布版本…\ndoc.published：版本已发布。\ndoc.publishError：发布未成功，请先确认当前版本状态。\ndashboard.empty：当前统计范围暂无数据。\ndashboard.scope：统计范围：{scope}；更新时间：{asOf}。\nmember.noPermission：你无权管理成员，请联系工作区管理员。\nmember.ownerGuard：请保留至少一名活跃所有者；转移所有权须由当前所有者操作。\ndemo.banner：演示模式：页面使用模拟数据，未连接真实业务服务。"
        },
        {
          "id": "specifications",
          "value": "交付格式：仅 assets/copy/specifications 三个 Markdown 字符串，各≤1200字。copy 每行以首个全角冒号分隔稳定 key 与文案，共40个不重复key。\n使用规则：保持key稳定；{scope}/{asOf}为服务端提供的统计范围/时间字符串，展示前转义；缺值时隐藏该元信息行。暂无正式名称，临时使用类别名“团队知识库”；暂按简体中文、清晰克制语气编写，正式名称、语气、多语言由产品负责人确认。\n状态映射：401→auth.expired；账号停用依据明确错误码映射auth.disabled；403→common.forbidden或member.noPermission；404→doc.unavailable，不透露资源是否存在；409→doc.conflict；422→doc.invalid并展示安全字段提示；503/网络失败→对应失败态。读失败可重新加载；写失败不得自动重放，冲突先保留修改。成功文案仅在对应操作成功响应后展示。\n入口规则：创建工作区入口须由F核对U/B契约后决定；doc.first仅用于可管理文档集合为空且可创建的状态。\n权限映射：doc.first/create/save/publish仅在服务端允许相应动作时展示；Viewer不显示草稿及治理指标。已加载的空集合数值显示0；加载失败不能显示为0。demo.banner仅用于模拟页面且持续可见。前端隐藏按钮不能替代服务端授权。\n品牌清单（均待制作/确认）：Logo：登录与页头，SVG、透明PNG，横版/方形；图标：导航与状态，SVG，24×24基准、统一线宽；配色：主色、文字、背景、成功/警告/错误语义色及对比度检查；字体：中文系统字体优先，定制字体须核实授权；插图：空状态，可选4:3；截图：指南，可选16:9，须来自已验收页面并脱敏。尺寸为需求建议，F确认容器后定稿。未提供参考或授权来源，占位素材须明确标识。\n上线前交接：产品负责人确认品牌与语言；F核对实际入口、角色和错误码并回传覆盖记录；V据B/F证据验收。当前仅完成文案与规格，真实登录、接口联调、截图及发布未验收。不宣传AI问答、实时协作、自动采集、计费、客户案例或性能指标。"
        }
      ]
    },
    {
      "id": "backend",
      "title": {
        "zh": "后端接口与业务规则",
        "en": "Backend API & business rules"
      },
      "column": 2,
      "row": 0,
      "status": "done",
      "seconds": 619,
      "outputType": "fields",
      "fields": [
        {
          "id": "api",
          "value": "AWW-6 已标记 done。[后端契约](artifacts/backend-contract-v1.md)覆盖业务模型、接口请求响应、权限校验、幂等与事务、检索及看板口径，供 F/V 消费。"
        },
        {
          "id": "implementation",
          "value": "本轮为设计交付，未实现或部署业务服务。分类写入、独立手动质检默认不开放；技术选型及审计保留期限仍需相关负责人在实现前确认。"
        },
        {
          "id": "checks",
          "value": "14项静态检查通过，包含42行接口定义；契约与验证文档已写入事项并回读一致，内部复核 AWW-7 已完成。17个服务验证场景均为 not_run，未执行真实认证、数据库、并发或前后端联调。"
        }
      ]
    },
    {
      "id": "frontend",
      "title": {
        "zh": "知识库 Web 工作台",
        "en": "Knowledge-base web workspace"
      },
      "column": 3,
      "row": 0,
      "status": "done",
      "seconds": 964,
      "outputType": "fields",
      "fields": [
        {
          "id": "delivery",
          "value": "前端演示已交付，包含工作区、登录态、检索、文档管理、权限可见性及看板。运行 python server.py 后访问 http://127.0.0.1:4173/。详见 artifacts/delivery.md。AWW-8 已回写为 blocked：等待浏览器验收环境及 U/B 真实身份、业务服务。"
        },
        {
          "id": "preview",
          "value": "index.html"
        },
        {
          "id": "checks",
          "value": "模型测试 12/12、实际页面脚本 DOM 测试 3/3 通过，入口及依赖 HTTP 200。已验证切换工作区保留检索条件、冲突保留输入、401 清屏等。浏览器启动被环境拒绝，尚无真实布局、键盘或截图验收；未部署上线。"
        }
      ]
    },
    {
      "id": "review",
      "title": {
        "zh": "交付验收",
        "en": "Delivery review"
      },
      "column": 4,
      "row": 0,
      "status": "done",
      "seconds": 429,
      "outputType": "fields",
      "fields": [
        {
          "id": "report",
          "value": "部分通过，整体验收未通过。AWW-12 已回读为 blocked。已建立15项验收标准，模型/DOM测试15/15及补充检查1/1通过。[验收报告](artifacts/acceptance-report.md)"
        },
        {
          "id": "issues",
          "value": "确认两项演示缺陷：Straße 无法被 STRASSE 命中；标签恢复后旧失败质检仍计入治理阻断。已委派前端 AWW-15，正在修复。浏览器验收依赖 AWW-11，由环境管理员提供可执行环境、前端提交证据后复验。"
        },
        {
          "id": "verification",
          "value": "真实浏览器启动遇到 WinError 5，原生交互、布局及浏览器端到端未验证。真实账号、部署和外部集成本轮不验收。测试输出、缺陷复现与源码快照均已保存；AWW-13 独立审查已关闭为 done。[验证记录](artifacts/validation.json)"
        }
      ]
    }
  ],
  "edges": [
    {
      "from": "product",
      "to": "users",
      "label": {
        "zh": "产品边界",
        "en": "Product scope"
      }
    },
    {
      "from": "product",
      "to": "data",
      "label": {
        "zh": "产品边界",
        "en": "Product scope"
      }
    },
    {
      "from": "product",
      "to": "materials",
      "label": {
        "zh": "产品边界",
        "en": "Product scope"
      }
    },
    {
      "from": "product",
      "to": "backend",
      "label": {
        "zh": "业务规则",
        "en": "Business rules"
      }
    },
    {
      "from": "users",
      "to": "backend",
      "label": {
        "zh": "身份与权限契约",
        "en": "Identity and permission contract"
      }
    },
    {
      "from": "data",
      "to": "backend",
      "label": {
        "zh": "数据字典",
        "en": "Data dictionary"
      }
    },
    {
      "from": "users",
      "to": "frontend",
      "label": {
        "zh": "用户与权限契约",
        "en": "User and permission contract"
      }
    },
    {
      "from": "data",
      "to": "frontend",
      "label": {
        "zh": "文档数据字典",
        "en": "Document data dictionary"
      }
    },
    {
      "from": "backend",
      "to": "frontend",
      "label": {
        "zh": "接口契约",
        "en": "API contract"
      }
    },
    {
      "from": "materials",
      "to": "frontend",
      "label": {
        "zh": "上线物料",
        "en": "Launch assets"
      }
    },
    {
      "from": "backend",
      "to": "review",
      "label": {
        "zh": "接口契约",
        "en": "API contract"
      }
    },
    {
      "from": "frontend",
      "to": "review",
      "label": {
        "zh": "交付的工作台",
        "en": "Delivered workspace"
      }
    }
  ],
  "note": {
    "zh": "7 个节点全部完成。交付验收如实写了“部分通过，整体验收未通过”：它退回了两处演示缺陷（Straße 搜不到 STRASSE；标签恢复后旧的失败质检仍计入阻断），前端修复后复验通过。路径中的本机目录与内部 ID 已隐去，其余为节点原文。",
    "en": "All 7 nodes completed. The delivery review recorded “partly passed, overall not accepted”: it sent back two demo defects (Straße not matching STRASSE; an old failed quality check still blocking after a tag was restored), and they passed re-verification after the front end fixed them. Local directories and internal IDs in paths are hidden; everything else is the nodes’ own text."
  },
  "verification": {
    "zh": "封面是交付的知识库工作台在演示模式（模拟数据）下的录屏。2026-09-05 的复验：模型与 Unicode 回归 31/31、应用 DOM 4/4、焦点回归 8/8 通过，两处被退回的缺陷复验通过；真实账号、后端服务与生产环境不在验收范围内。",
    "en": "The cover is a recording of the delivered knowledge-base workspace in its demo mode with simulated data. Re-acceptance on 2026-09-05: model and Unicode regressions 31/31, app DOM 4/4 and focus regressions 8/8 passed, and both defects sent back passed re-verification; real accounts, backend services and production were outside its scope."
  }
};
export default record;
