"""Sync SuperClaw skills into native agent-runtime skill directories.

Why this exists
---------------
Agent runtimes — Codex, Claude Code, Gemini CLI — discover skills by reading
native ``SKILL.md`` directories. SuperClaw therefore needs a managed projection
ledger for two intentionally separate tracks:

- **Native skills** are markdown artifacts imported into
  :mod:`superclaw.skill_store`. Projection copies the normalized ``SKILL.md`` and
  assets in full. Install-time provenance/signature/executable checks live in
  the store; runtime projection adds no plugin governance and no MCP hop.
- **Plugin skills** are the legacy/governed proxy compatibility track. Their
  projected ``SKILL.md`` files remain discovery pointers that call SuperClaw's
  MCP proxy, and enumeration still runs through the fail-closed plugin gate.

Both tracks use the same projection lock for safe reconcile: a user's local edit
is detected and not overwritten, and stale managed files are reclaimed from
positive source-of-truth signals rather than a bare gate miss.
- **Target directories are resolved per runtime, never hardcoded.** A runtime's
  skill path is a versioned fact (Codex has moved between ``.codex/skills`` and
  ``.agents/skills``), so each target resolves via an absolute env override, then
  a probe of known locations, then a default.
- **Every projected file is tracked in a projection lock** under the user's
  global SuperClaw state (the projection targets are user-global, so the ledger
  is too). Writes are atomic and serialized by a file lock; a user's local edit
  is detected (managed marker + render digest) and never silently clobbered.
"""

from __future__ import annotations

import contextlib
import hashlib
import json
import os
import re
import tempfile
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Callable, Iterator, Mapping

from superclaw.plugin_mcp_proxy import projected_tool_name
from superclaw.plugin_proxy import DEFAULT_RUNTIME_VERSION
from superclaw.plugin_runtime_projection import gate_passing_plugins
from superclaw.plugins import (
    MANIFEST_NAME,
    default_revocation_file,
    list_cached_plugins,
    plugin_cache_root,
)
from superclaw.environment import superclaw_home
from superclaw.skill_store import SkillImportRecord, default_skill_revocation_file, list_skills

try:  # POSIX advisory file lock.
    import fcntl
except ImportError:  # pragma: no cover - platform dependent
    fcntl = None  # type: ignore[assignment]

try:  # Windows exclusive lock fallback.
    import msvcrt
except ImportError:  # pragma: no cover - platform dependent
    msvcrt = None  # type: ignore[assignment]

# Injected verbatim at the top of every file we generate. Two jobs: it tells a
# human the file is owned by SuperClaw, and it is the marker we look for before
# ever overwriting or deleting a file — no marker means the user owns it and we
# keep our hands off.
MANAGED_MARKER = (
    "<!-- AUTO-GENERATED BY SUPERCLAW — DO NOT EDIT. "
    "Run `superclaw plugin sync-skills` to update; local edits are not synced back. -->"
)

# The projection ledger is user-global because the projection targets are
# user-global (~/.codex/skills, ...). Keeping it in cwd would let lifecycle state
# drift by working directory and orphan files written into the user's home.
DEFAULT_PROJECTION_LOCK = superclaw_home() / "projections.lock"
PROJECTION_LOCK_SCHEMA_VERSION = "0.1.0"
PROXY_TIER = "proxy"
NATIVE_TIER = "native"


def default_projection_lock() -> Path:
    """The projection ledger path, overridable via ``SUPERCLAW_PROJECTION_LOCK``.

    Mirrors how the plugin cache honors ``SUPERCLAW_PLUGIN_CACHE_PATH``: the env
    override lets a surface (API/tests) redirect the ledger without writing into
    the real user home. Resolved at call time so tests can set it after import.
    """
    override = os.environ.get("SUPERCLAW_PROJECTION_LOCK")
    # Call-time under the single data root so it tracks SUPERCLAW_HOME after import.
    return Path(override).expanduser() if override else superclaw_home() / "projections.lock"


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


class SkillSyncError(RuntimeError):
    """Raised when a skill cannot be projected safely."""


# --------------------------------------------------------------------------- #
# Runtime targets (de-hardcoded; absolute env override -> probe -> default)
# --------------------------------------------------------------------------- #


@dataclass(frozen=True)
class RuntimeSkillTarget:
    """A native runtime's skill directory, resolved without hardcoding a path.

    A runtime's skill directory is a *versioned* fact, not a constant, so
    resolution is layered: an explicit (and absolute) env override always wins;
    otherwise we probe known locations (default first, then alternates a newer
    runtime may have moved to) and use the first that exists; failing that we
    fall back to the default so a first-time sync still creates the canonical
    directory.
    """

    name: str
    env_var: str
    default_subdir: Path
    alternate_subdirs: tuple[Path, ...] = ()

    def skills_dir(
        self,
        *,
        home: Path | None = None,
        env: Mapping[str, str] | None = None,
    ) -> Path:
        environ = os.environ if env is None else env
        override = environ.get(self.env_var)
        if override:
            candidate = Path(override).expanduser()
            if not candidate.is_absolute():
                raise SkillSyncError(f"{self.env_var} must be an absolute path: {override!r}")
            # Normalize away any ``..`` so the override can't traverse out of the
            # directory it names.
            return candidate.resolve()
        base = Path.home() if home is None else home
        for subdir in (self.default_subdir, *self.alternate_subdirs):
            candidate = base / subdir
            if candidate.is_dir():
                return candidate
        return base / self.default_subdir


RUNTIME_TARGETS: dict[str, RuntimeSkillTarget] = {
    "codex": RuntimeSkillTarget(
        name="codex",
        env_var="SUPERCLAW_CODEX_SKILLS_DIR",
        default_subdir=Path(".codex/skills"),
        # Codex has moved its skill path between releases; probe the alternate
        # before falling back so we land in whichever one this version reads.
        alternate_subdirs=(Path(".agents/skills"),),
    ),
    "claude": RuntimeSkillTarget(
        name="claude",
        env_var="SUPERCLAW_CLAUDE_SKILLS_DIR",
        default_subdir=Path(".claude/skills"),
    ),
    "gemini": RuntimeSkillTarget(
        name="gemini",
        env_var="SUPERCLAW_GEMINI_SKILLS_DIR",
        default_subdir=Path(".gemini/skills"),
    ),
}


def resolve_targets(names: tuple[str, ...] | None = None) -> list[RuntimeSkillTarget]:
    """Resolve target names to :class:`RuntimeSkillTarget`; default is all."""
    if names is None:
        return list(RUNTIME_TARGETS.values())
    resolved: list[RuntimeSkillTarget] = []
    for name in names:
        target = RUNTIME_TARGETS.get(name)
        if target is None:
            raise SkillSyncError(
                f"unknown runtime target: {name!r} (known: {', '.join(sorted(RUNTIME_TARGETS))})"
            )
        resolved.append(target)
    return resolved


# --------------------------------------------------------------------------- #
# Rendering (discovery-only / proxy)
# --------------------------------------------------------------------------- #


def _safe_skill_name(value: str) -> str:
    normalized = re.sub(r"[^a-zA-Z0-9_-]+", "-", value.strip()).strip("-").lower()
    return normalized or "plugin-skill"


def _yaml_scalar(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", " ")


def render_proxy_skill(manifest: Mapping[str, Any], tool: Mapping[str, Any]) -> str:
    """Render a discovery-only ``SKILL.md`` that routes execution to the proxy.

    B-fast shape: the body names the exact MCP tool and its input schema so the
    runtime can issue a single ``tools/call`` instead of paying the
    ``list_tools`` / ``describe_tool`` round-trips. Execution still lands on the
    SuperClaw MCP proxy and the governance gate.
    """
    plugin_id = str(manifest["id"])
    raw_tool_name = str(tool["name"])
    mcp_tool_name = projected_tool_name(plugin_id, raw_tool_name)
    description = str(tool.get("description") or f"Use SuperClaw plugin tool {raw_tool_name}.")
    input_schema = json.dumps(tool.get("input_schema", {}), indent=2, sort_keys=True, ensure_ascii=False)
    return f"""{MANAGED_MARKER}
---
name: {mcp_tool_name}
description: "{_yaml_scalar(description)}"
---

# {mcp_tool_name}

Use this skill when the task needs the SuperClaw plugin tool `{raw_tool_name}`.

Call the MCP tool `{mcp_tool_name}` through the SuperClaw MCP proxy in one
`tools/call`. Do not load the original plugin directory, sidecar entrypoint,
cache directory, license state, or developer source directly. Every call is
governed by SuperClaw at execution time.

Input schema:

```json
{input_schema}
```
"""


def _tombstone(plugin_id: str) -> str:
    return (
        f"{MANAGED_MARKER}\n"
        "---\n"
        f"name: {_safe_skill_name(plugin_id)}-revoked\n"
        'description: "This SuperClaw skill was revoked and must not be used."\n'
        "---\n\n"
        f"# Revoked\n\nThe SuperClaw skill `{plugin_id}` was revoked. Do not use it.\n"
    )


# --------------------------------------------------------------------------- #
# Projection lock (file-locked, atomic)
# --------------------------------------------------------------------------- #


@dataclass(frozen=True)
class ProjectionRecord:
    """One projected ``SKILL.md`` file, tracked for update / GC / drift checks."""

    plugin_id: str
    version: str
    target: str
    tier: str
    path: str
    render_digest: str
    source_digest: str
    synced_at: str

    def to_dict(self) -> dict[str, Any]:
        return {
            "plugin_id": self.plugin_id,
            "version": self.version,
            "target": self.target,
            "tier": self.tier,
            "path": self.path,
            "render_digest": self.render_digest,
            "source_digest": self.source_digest,
            "synced_at": self.synced_at,
        }

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> "ProjectionRecord":
        return cls(
            plugin_id=str(data["plugin_id"]),
            version=str(data.get("version") or ""),
            target=str(data["target"]),
            tier=str(data.get("tier") or PROXY_TIER),
            path=str(data["path"]),
            render_digest=str(data.get("render_digest") or ""),
            source_digest=str(data.get("source_digest") or ""),
            synced_at=str(data.get("synced_at") or ""),
        )


def load_projection_lock(lock_path: Path) -> dict[str, ProjectionRecord]:
    """Load the projection lock keyed by absolute output path."""
    if not lock_path.exists():
        return {}
    data = json.loads(lock_path.read_text(encoding="utf-8"))
    records: dict[str, ProjectionRecord] = {}
    for entry in data.get("records", []):
        record = ProjectionRecord.from_dict(entry)
        records[record.path] = record
    return records


def save_projection_lock(lock_path: Path, records: Mapping[str, ProjectionRecord]) -> None:
    """Persist the projection lock atomically."""
    payload = {
        "schema_version": PROJECTION_LOCK_SCHEMA_VERSION,
        "records": [records[key].to_dict() for key in sorted(records)],
    }
    lock_path.parent.mkdir(parents=True, exist_ok=True)
    _atomic_write(lock_path, json.dumps(payload, indent=2, sort_keys=True, ensure_ascii=False) + "\n")


@contextlib.contextmanager
def _hold_lock(lock_path: Path) -> Iterator[None]:
    """Serialize the lock's read-modify-write across concurrent CLI invocations.

    Uses ``fcntl`` (POSIX) or ``msvcrt`` (Windows). If neither is available we
    fail closed rather than write the ledger unlocked — a silent no-op would let
    concurrent syncs corrupt the projection record.
    """
    lock_path.parent.mkdir(parents=True, exist_ok=True)
    guard = lock_path.with_name(lock_path.name + ".guard")
    handle = open(guard, "a+")  # noqa: SIM115 - released in finally
    try:
        if fcntl is not None:
            fcntl.flock(handle.fileno(), fcntl.LOCK_EX)
        elif msvcrt is not None:  # pragma: no cover - platform dependent
            handle.seek(0)
            msvcrt.locking(handle.fileno(), msvcrt.LK_LOCK, 1)
        else:  # pragma: no cover - platform dependent
            raise SkillSyncError("no file-locking primitive available; refusing unlocked projection write")
        yield
    finally:
        with contextlib.suppress(OSError):
            if fcntl is not None:
                fcntl.flock(handle.fileno(), fcntl.LOCK_UN)
            elif msvcrt is not None:  # pragma: no cover - platform dependent
                handle.seek(0)
                msvcrt.locking(handle.fileno(), msvcrt.LK_UNLCK, 1)
        handle.close()


def _digest(content: str) -> str:
    return "sha256:" + hashlib.sha256(content.encode("utf-8")).hexdigest()


def _digest_bytes(content: bytes) -> str:
    return "sha256:" + hashlib.sha256(content).hexdigest()


def _file_digest(path: Path) -> str:
    return _digest_bytes(path.read_bytes())


def _atomic_write(path: Path, content: str) -> None:
    _atomic_write_bytes(path, content.encode("utf-8"))


def _atomic_write_bytes(path: Path, content: bytes, *, mode: int | None = None) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    # Unique temp in the same directory so concurrent writers never collide and
    # the final replace() stays atomic on one filesystem.
    fd, tmp_name = tempfile.mkstemp(dir=str(path.parent), prefix=path.name + ".", suffix=".superclaw-tmp")
    tmp = Path(tmp_name)
    try:
        with os.fdopen(fd, "wb") as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        if mode is not None:
            tmp.chmod(mode)
        tmp.replace(path)
    finally:
        if tmp.exists():
            tmp.unlink()


def _is_managed_unmodified(path: Path, render_digest: str) -> bool:
    """True iff the on-disk file is ours and untouched since we wrote it.

    The safety gate before any overwrite or delete: a file that lost its marker,
    or whose digest no longer matches what we recorded, was edited by the user (a
    local override) and is never silently clobbered.
    """
    if not path.exists():
        return False
    current = path.read_text(encoding="utf-8", errors="replace")
    if MANAGED_MARKER not in current:
        return False
    return _digest(current) == render_digest


def _record_is_unmodified(path: Path, record: ProjectionRecord | None) -> bool:
    if record is None or not path.exists():
        return False
    if record.tier == NATIVE_TIER:
        return _file_digest(path) == record.render_digest
    return _is_managed_unmodified(path, record.render_digest)


# --------------------------------------------------------------------------- #
# Plan
# --------------------------------------------------------------------------- #


def _load_manifest(plugin_path: Path) -> dict[str, Any]:
    return json.loads((plugin_path / MANIFEST_NAME).read_text(encoding="utf-8"))


def plan_plugin_skill_sync(
    *,
    plugin_id: str | None = None,
    targets: tuple[str, ...] | None = None,
    cache_root: Path | None = None,
    home: Path | None = None,
    env: Mapping[str, str] | None = None,
    entitlement_file: Path | None = None,
    revocation_file: Path | None = None,
    policy_file: Path | None = None,
    public_key: str | None = None,
    runtime_version: str = DEFAULT_RUNTIME_VERSION,
) -> list[dict[str, Any]]:
    """Compute what a sync would write, without touching the filesystem.

    Enumeration runs through the *same* fail-closed governance gate the call
    path uses (:func:`available_plugins`). A plugin the kernel would not offer
    right now is never projected — so a revoked or unsigned skill cannot leak a
    discovery surface into a runtime.
    """
    return _enumerate_plans(
        plugin_id=plugin_id,
        targets=targets,
        cache_root=cache_root,
        home=home,
        env=env,
        entitlement_file=entitlement_file,
        revocation_file=revocation_file,
        policy_file=policy_file,
        public_key=public_key,
        runtime_version=runtime_version,
    )[0]


def _enumerate_plans(
    *,
    plugin_id: str | None,
    targets: tuple[str, ...] | None,
    cache_root: Path | None,
    home: Path | None,
    env: Mapping[str, str] | None,
    entitlement_file: Path | None,
    revocation_file: Path | None,
    policy_file: Path | None,
    public_key: str | None,
    runtime_version: str,
) -> tuple[list[dict[str, Any]], set[str]]:
    """Return ``(plans, allowed_ids)``.

    ``allowed_ids`` is the set of plugin ids that passed the governance gate this
    run — taken from :func:`available_plugins` directly, *not* reverse-derived
    from the tool plans, so a plugin that enumerated cleanly but now declares no
    tools is still recognized as "allowed" (and its stale projections become
    reclaimable).
    """
    resolved_targets = resolve_targets(targets)
    public_key = public_key or os.environ.get("SUPERCLAW_PLUGIN_ROOT_PUBLIC_KEY")
    # Tools-agnostic gate enumeration: a plugin that passes governance but now
    # declares zero tools must still count as allowed, so its orphaned
    # projections get reclaimed. Same gate as available_plugins (shared code).
    allowed = gate_passing_plugins(
        cache_root=cache_root,
        entitlement_file=entitlement_file,
        revocation_file=revocation_file,
        policy_file=policy_file,
        public_key=public_key,
        runtime_version=runtime_version,
    )
    root = plugin_cache_root(cache_root)
    plans: list[dict[str, Any]] = []
    allowed_ids: set[str] = set()
    for allowed_plugin_id, version in allowed:
        if plugin_id is not None and allowed_plugin_id != plugin_id:
            continue
        plugin_path = root / allowed_plugin_id / version
        try:
            manifest = _load_manifest(plugin_path)
        except (OSError, ValueError):
            continue
        allowed_ids.add(allowed_plugin_id)
        source_digest = str((manifest.get("provenance") or {}).get("package_digest") or "")
        tools = [t for t in manifest.get("tools", []) if isinstance(t, dict) and t.get("name")]
        for target in resolved_targets:
            skills_dir = target.skills_dir(home=home, env=env)
            for tool in tools:
                content = render_proxy_skill(manifest, tool)
                out = skills_dir / _safe_skill_name(f"{allowed_plugin_id}-{tool['name']}") / "SKILL.md"
                plans.append(
                    {
                        "plugin_id": allowed_plugin_id,
                        "version": version,
                        "target": target.name,
                        "tier": PROXY_TIER,
                        "path": str(out),
                        "content": content,
                        "source_digest": source_digest,
                    }
                )
    return plans, allowed_ids


def plan_native_skill_sync(
    *,
    skill_slug: str | None = None,
    targets: tuple[str, ...] | None = None,
    store_dir: Path | None = None,
    home: Path | None = None,
    env: Mapping[str, str] | None = None,
    revocation_file: Path | None = None,
) -> list[dict[str, Any]]:
    """Compute native skill file-copy projections without touching the filesystem.

    Enumeration goes through :func:`superclaw.skill_store.list_skills`, which
    fails closed on a tampered or revoked skill (§5 5b/5c). So a revoked skill is
    never planned — and because it drops out of the desired set, a previously
    projected copy is reclaimed on the next sync.
    """
    plans = _enumerate_native_plans(
        skill_slug=skill_slug,
        targets=targets,
        store_dir=store_dir,
        home=home,
        env=env,
        revocation_file=revocation_file,
    )
    return [{k: v for k, v in plan.items() if k != "content_bytes"} for plan in plans]


def _enumerate_native_plans(
    *,
    skill_slug: str | None,
    targets: tuple[str, ...] | None,
    store_dir: Path | None,
    home: Path | None,
    env: Mapping[str, str] | None,
    revocation_file: Path | None,
) -> list[dict[str, Any]]:
    resolved_targets = resolve_targets(targets)
    # list_skills is the single fail-closed read: it recomputes the on-disk
    # digest and drops any skill that is tampered or revoked, so a revoked skill
    # is excluded from the plan here (never projected) and, being absent from the
    # desired set, its prior projection is reclaimed by _reconcile_native_stale.
    records = list_skills(
        store_dir=store_dir,
        revocation_file=revocation_file or default_skill_revocation_file(),
    )
    plans: list[dict[str, Any]] = []
    for skill in records:
        if skill_slug is not None and skill.slug != skill_slug:
            continue
        for target in resolved_targets:
            target_root = target.skills_dir(home=home, env=env) / skill.slug
            # The SKILL.md slot identifies the skill directory. A pre-existing
            # SKILL.md we never projected (no ledger record) means the whole
            # directory belongs to the user / another tool, so EVERY file of this
            # skill (SKILL.md + assets) is held back — see the directory-atomic
            # foreign guard in sync_native_skills. Carried on each plan so the
            # write loop can decide per (skill, target) without re-resolving dirs.
            skill_md_path = str(target_root / "SKILL.md")
            for source, relative in _native_skill_files(skill):
                out = target_root / relative
                plans.append(
                    {
                        "plugin_id": skill.slug,
                        "version": "",
                        "target": target.name,
                        "tier": NATIVE_TIER,
                        "path": str(out),
                        "skill_md_path": skill_md_path,
                        "content_bytes": source.read_bytes(),
                        "mode": source.stat().st_mode & 0o777,
                        "source_digest": skill.source_digest,
                    }
                )
    return plans


def _native_skill_files(skill: SkillImportRecord) -> list[tuple[Path, Path]]:
    files: list[tuple[Path, Path]] = [(skill.skill_path, Path("SKILL.md"))]
    assets_root = skill.root / "assets"
    if assets_root.exists():
        for path in sorted(item for item in assets_root.rglob("*") if item.is_file()):
            if path.is_symlink():
                raise SkillSyncError(f"native skill asset may not be a symlink: {path}")
            files.append((path, Path("assets") / path.relative_to(assets_root)))
    return files


# --------------------------------------------------------------------------- #
# Sync (write + reconcile)
# --------------------------------------------------------------------------- #


@dataclass
class SyncResult:
    written: list[str] = field(default_factory=list)
    unchanged: list[str] = field(default_factory=list)
    skipped_local_override: list[str] = field(default_factory=list)
    reclaimed: list[str] = field(default_factory=list)
    tombstoned: list[str] = field(default_factory=list)
    plans: list[dict[str, Any]] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return {
            "written": self.written,
            "unchanged": self.unchanged,
            "skipped_local_override": self.skipped_local_override,
            "reclaimed": self.reclaimed,
            "tombstoned": self.tombstoned,
            "plans": self.plans,
        }


def sync_native_skills(
    *,
    skill_slug: str | None = None,
    targets: tuple[str, ...] | None = None,
    store_dir: Path | None = None,
    home: Path | None = None,
    env: Mapping[str, str] | None = None,
    lock_path: Path | None = None,
    force: bool = False,
    reconcile: bool = True,
    revocation_file: Path | None = None,
    now: Callable[[], datetime] | None = None,
) -> SyncResult:
    """Copy native stored skills into runtime skill directories.

    Native projection is a full-file copy from :mod:`superclaw.skill_store`.
    It does not enumerate plugins, invoke plugin governance, or render MCP proxy
    pointers. Reconcile only touches ledger records with ``tier == "native"``.

    Revocation closes end-to-end (§5 5c): the enumerate step drops a revoked or
    tampered skill, and the reconcile step then reclaims any copy it had
    previously projected into a runtime skill directory.
    """
    clock = now or _utcnow
    lock_path = lock_path if lock_path is not None else default_projection_lock()
    with _hold_lock(lock_path):
        # Plan *inside* the lock so a revocation that lands between planning and
        # writing cannot resurrect a projection another process just withdrew
        # (same discipline as sync_plugin_skills).
        plans = _enumerate_native_plans(
            skill_slug=skill_slug,
            targets=targets,
            store_dir=store_dir,
            home=home,
            env=env,
            revocation_file=revocation_file,
        )
        result = SyncResult(plans=[{k: v for k, v in p.items() if k != "content_bytes"} for p in plans])
        records = load_projection_lock(lock_path)
        desired: set[str] = set()

        # Directory-atomic foreign guard: if a skill's SKILL.md slot already
        # exists but we never projected it (no ledger record), the whole runtime
        # directory belongs to the user / another tool that happens to share the
        # slug. Hold back EVERY file of that skill — not just SKILL.md — so a sync
        # can never inject our asset files into a stranger's same-named skill dir.
        # NOT force-overridable: --force re-asserts OUR projections, it does not
        # license clobbering a directory SuperClaw never created.
        foreign_skill_md: set[str] = {
            plan["skill_md_path"]
            for plan in plans
            if Path(plan["skill_md_path"]).exists() and plan["skill_md_path"] not in records
        }

        for plan in plans:
            path = Path(plan["path"])
            content = plan["content_bytes"]
            render_digest = _digest_bytes(content)
            desired.add(plan["path"])
            existing = records.get(plan["path"])

            # Foreign skill directory (its SKILL.md is not ours): skip the whole
            # skill, even under --force. Report the SKILL.md slot once per skill.
            if plan["skill_md_path"] in foreign_skill_md:
                if plan["path"] == plan["skill_md_path"]:
                    result.skipped_local_override.append(plan["path"])
                continue

            # Foreign individual file (this exact path exists but is unrecorded):
            # never overwrite, even under --force. Force only re-asserts files we
            # have a ledger record for; it does not seize unrelated files.
            if path.exists() and existing is None:
                result.skipped_local_override.append(plan["path"])
                continue

            # Our own projection the user hand-edited: skip unless --force.
            if path.exists() and not force and existing is not None and not _record_is_unmodified(path, existing):
                result.skipped_local_override.append(plan["path"])
                continue

            # Unchanged iff the ON-DISK bytes already equal what we would write.
            # Comparing the file (not just the ledger's recorded digest) is what
            # lets --force actually re-assert a hand-edited projection even when
            # the store content is unchanged — the ledger digest would still match
            # the intended content and wrongly report "unchanged", so force would
            # never restore the file.
            if path.exists() and _file_digest(path) == render_digest:
                result.unchanged.append(plan["path"])
                continue

            _atomic_write_bytes(path, content, mode=plan.get("mode"))
            records[plan["path"]] = ProjectionRecord(
                plugin_id=plan["plugin_id"],
                version=plan["version"],
                target=plan["target"],
                tier=NATIVE_TIER,
                path=plan["path"],
                render_digest=render_digest,
                source_digest=plan["source_digest"],
                synced_at=clock().isoformat(),
            )
            result.written.append(plan["path"])

        if reconcile:
            _reconcile_native_stale(
                records,
                desired=desired,
                scope_skill_slug=skill_slug,
                force=force,
                result=result,
            )

        save_projection_lock(lock_path, records)
    return result


def _reconcile_native_stale(
    records: dict[str, ProjectionRecord],
    *,
    desired: set[str],
    scope_skill_slug: str | None,
    force: bool,
    result: SyncResult,
) -> None:
    for key, record in list(records.items()):
        if record.tier != NATIVE_TIER or key in desired:
            continue
        if scope_skill_slug is not None and record.plugin_id != scope_skill_slug:
            continue
        path = Path(record.path)
        if path.exists() and not force and not _record_is_unmodified(path, record):
            result.skipped_local_override.append(record.path)
            continue
        if path.exists():
            path.unlink()
        _prune_native_empty_parents(path, record.plugin_id)
        records.pop(key, None)
        result.reclaimed.append(record.path)


def native_skill_status(
    *,
    skill_slug: str | None = None,
    targets: tuple[str, ...] | None = None,
    store_dir: Path | None = None,
    home: Path | None = None,
    env: Mapping[str, str] | None = None,
    lock_path: Path | None = None,
    revocation_file: Path | None = None,
) -> list[dict[str, Any]]:
    """Report native-skill projection health WITHOUT writing anything (read-only).

    Surfaces the drift the silent file-copy model would otherwise hide:

    - ``ok`` — projected, on disk, byte-identical to what we projected, and the
      store copy has not changed since.
    - ``not_projected`` — a governed store skill that has not been synced to this
      target yet (the "created != active" gap).
    - ``foreign_collision`` — a same-named SKILL.md occupies the slot that we
      never projected; a sync will hold it back rather than overwrite it.
    - ``drift_local_edit`` — our projection was hand-edited in the runtime dir
      (on-disk bytes differ from the ledger); a sync skips it unless ``--force``.
    - ``drift_store_updated`` — the store skill changed (or grew a file) but the
      projection is stale; re-run sync to refresh it.
    - ``missing_projection`` — the ledger records a projection but the file is
      gone; re-run sync to restore it.
    - ``stale_revoked`` — a projection still on disk whose store skill is now
      revoked/tampered/removed; the next sync reclaims it.

    Ownership is decided at the SKILL.md slot (it identifies the skill directory),
    but the reported status AGGREGATES over EVERY projected file of the skill —
    SKILL.md and each asset — worst-state-first, so an asset-only edit or deletion
    is visible and never masked as ``ok``. Exactly one row per (skill, target).
    """
    resolved_targets = resolve_targets(targets)
    governed = {
        skill.slug: skill
        for skill in list_skills(
            store_dir=store_dir,
            revocation_file=revocation_file or default_skill_revocation_file(),
        )
    }
    records = load_projection_lock(lock_path or default_projection_lock())
    rows: list[dict[str, Any]] = []

    def _emit(slug: str, target_name: str, status: str, detail: str) -> None:
        rows.append({"slug": slug, "target": target_name, "status": status, "detail": detail})

    # Worst-first precedence so one row per (skill, target) reflects the most
    # actionable state across ALL of the skill's files (SKILL.md + every asset),
    # never just SKILL.md — an asset-only edit/deletion must not read as "ok".
    severity = {
        "foreign_collision": 6,
        "not_projected": 5,
        "missing_projection": 4,
        "drift_local_edit": 3,
        "drift_store_updated": 2,
        "ok": 1,
    }

    # 1) Governed store skills × each target.
    for slug, skill in sorted(governed.items()):
        if skill_slug is not None and slug != skill_slug:
            continue
        for target in resolved_targets:
            target_root = target.skills_dir(home=home, env=env) / slug
            skill_md = target_root / "SKILL.md"
            if str(skill_md) not in records:
                # Ownership is decided at the SKILL.md slot (the skill directory).
                if skill_md.exists():
                    _emit(slug, target.name, "foreign_collision", str(skill_md))
                else:
                    _emit(slug, target.name, "not_projected", "run `superclaw skill sync` to project")
                continue
            # Aggregate over EVERY projected file of this skill — SKILL.md and
            # each asset — so asset drift is visible and status matches what sync
            # would actually do.
            status = "ok"
            detail = str(skill_md)
            for _source, relative in _native_skill_files(skill):
                out = target_root / relative
                rec = records.get(str(out))
                if rec is None and out.exists():
                    # An unrecorded file already sits at this asset slot — sync
                    # will hold it back (foreign), so "re-sync" would be a lie.
                    file_status, file_detail = "drift_local_edit", f"unrecorded file at {out}; sync skips it"
                elif rec is None:
                    file_status, file_detail = "drift_store_updated", f"store added {relative}; re-sync"
                elif not out.exists():
                    file_status, file_detail = "missing_projection", str(out)
                elif _file_digest(out) != rec.render_digest:
                    file_status, file_detail = "drift_local_edit", str(out)
                elif rec.source_digest != skill.source_digest:
                    file_status, file_detail = "drift_store_updated", "store changed; re-sync to refresh"
                else:
                    file_status, file_detail = "ok", str(out)
                if severity[file_status] > severity[status]:
                    status, detail = file_status, file_detail
            _emit(slug, target.name, status, detail)

    # 2) Native projections whose store skill is gone (revoked / tampered /
    #    deleted) but a file still lingers — the stale-projection window. Collapse
    #    to one row per (skill, target) even when several asset files remain.
    seen_stale: set[tuple[str, str]] = set()
    target_names = {t.name for t in resolved_targets}
    for _key, record in sorted(records.items()):
        if record.tier != NATIVE_TIER or record.plugin_id in governed:
            continue
        if skill_slug is not None and record.plugin_id != skill_slug:
            continue
        if not Path(record.path).exists():
            continue
        target_name = record.target or ""
        if targets is not None and target_name not in target_names:
            continue
        ident = (record.plugin_id, target_name)
        if ident in seen_stale:
            continue
        seen_stale.add(ident)
        _emit(record.plugin_id, target_name, "stale_revoked", "projection lingers; next sync reclaims it")

    return rows


def _installed_plugin_ids(cache_root: Path | None) -> set[str]:
    return {str(row["id"]) for row in list_cached_plugins(cache_root=cache_root)}


def _revoked_entries(revocation_file: Path | None) -> list[dict[str, Any]]:
    path = revocation_file or default_revocation_file()
    if not path.exists():
        return []
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return []
    return [item for item in payload.get("revoked", []) if isinstance(item, dict) and item.get("plugin_id")]


def _record_is_revoked(record: ProjectionRecord, revoked: list[dict[str, Any]]) -> bool:
    """Match a projection against revocation entries at id+version+digest grain.

    A revocation entry may pin a specific version and/or package digest; an entry
    that omits them revokes the whole plugin id. This mirrors the kernel's own
    revocation check (``PackageTrustVerifier.check_revocation`` /
    ``check_plugin_revocation``) so projection withdrawal can't be coarser (or
    finer) than execution.
    """
    for item in revoked:
        if str(item.get("plugin_id")) != record.plugin_id:
            continue
        version = item.get("version")
        digest = item.get("package_digest")
        if version not in {None, record.version}:
            continue
        if digest not in {None, record.source_digest}:
            continue
        return True
    return False


def sync_plugin_skills(
    *,
    plugin_id: str | None = None,
    targets: tuple[str, ...] | None = None,
    cache_root: Path | None = None,
    home: Path | None = None,
    env: Mapping[str, str] | None = None,
    entitlement_file: Path | None = None,
    revocation_file: Path | None = None,
    policy_file: Path | None = None,
    public_key: str | None = None,
    runtime_version: str = DEFAULT_RUNTIME_VERSION,
    lock_path: Path | None = None,
    force: bool = False,
    reconcile: bool = True,
    now: Callable[[], datetime] | None = None,
) -> SyncResult:
    """Project governed skills into native runtime directories (managed write).

    Only plugins that pass the fail-closed governance gate are projected.
    Idempotent: re-running rewrites only what changed; a user's local edit is
    reported as ``skipped_local_override`` and never overwritten unless
    ``force``. A *full* sync (no ``plugin_id`` filter) also reconciles: it
    reclaims projections for plugins that have since been uninstalled (delete) or
    revoked (tombstone), keyed off positive signals so a misconfigured run can
    never delete everything.
    """
    clock = now or _utcnow
    lock_path = lock_path if lock_path is not None else default_projection_lock()
    with _hold_lock(lock_path):
        # Plan *inside* the lock: governance state (revocations, the cache) can
        # change between planning and writing, so a plan computed before the lock
        # could resurrect a projection another process just revoked.
        plans, allowed_ids = _enumerate_plans(
            plugin_id=plugin_id,
            targets=targets,
            cache_root=cache_root,
            home=home,
            env=env,
            entitlement_file=entitlement_file,
            revocation_file=revocation_file,
            policy_file=policy_file,
            public_key=public_key,
            runtime_version=runtime_version,
        )
        result = SyncResult(plans=[{k: v for k, v in p.items() if k != "content"} for p in plans])
        records = load_projection_lock(lock_path)
        desired: set[str] = set()

        for plan in plans:
            path = Path(plan["path"])
            content = plan["content"]
            render_digest = _digest(content)
            desired.add(plan["path"])
            existing = records.get(plan["path"])

            if path.exists() and not force:
                prior_digest = existing.render_digest if existing else ""
                if not _is_managed_unmodified(path, prior_digest):
                    result.skipped_local_override.append(plan["path"])
                    continue

            if existing is not None and existing.render_digest == render_digest and path.exists():
                result.unchanged.append(plan["path"])
                continue

            _atomic_write(path, content)
            records[plan["path"]] = ProjectionRecord(
                plugin_id=plan["plugin_id"],
                version=plan["version"],
                target=plan["target"],
                tier=plan["tier"],
                path=plan["path"],
                render_digest=render_digest,
                source_digest=plan["source_digest"],
                synced_at=clock().isoformat(),
            )
            result.written.append(plan["path"])

        if reconcile:
            # A scoped sync (a single plugin, e.g. install --sync-skills on an
            # upgrade) reconciles only that plugin's stale records — so a tool
            # removed in the new version is reclaimed — without touching others.
            _reconcile_stale(
                records,
                desired=desired,
                allowed_ids=allowed_ids,
                scope_plugin_id=plugin_id,
                cache_root=cache_root,
                revocation_file=revocation_file,
                force=force,
                result=result,
            )

        save_projection_lock(lock_path, records)
    return result


def _reconcile_stale(
    records: dict[str, ProjectionRecord],
    *,
    desired: set[str],
    allowed_ids: set[str],
    scope_plugin_id: str | None,
    cache_root: Path | None,
    revocation_file: Path | None,
    force: bool,
    result: SyncResult,
) -> None:
    """Reclaim projections that should no longer exist.

    ``scope_plugin_id`` bounds the sweep: ``None`` reconciles every record (a
    full sync), otherwise only records for that plugin (a scoped sync, so other
    plugins' projections are never touched).

    Keyed off *positive* signals only, so a misconfigured sync (e.g. a missing
    public key that empties the allowed set) can never wipe everything:

    - revoked (id+version+digest match) → tombstone;
    - uninstalled (plugin absent from the cache) → delete;
    - a tool that vanished from a plugin we *did* enumerate this run (its id is in
      ``allowed_ids`` but this path was not produced) → delete the stale tool file;
    - a plugin that is installed but was simply not enumerated this run (gate
      miss) → leave untouched.
    """
    installed = _installed_plugin_ids(cache_root)
    revoked = _revoked_entries(revocation_file)
    for key, record in list(records.items()):
        if record.tier != PROXY_TIER:
            continue
        if key in desired:
            continue
        if scope_plugin_id is not None and record.plugin_id != scope_plugin_id:
            continue
        path = Path(record.path)
        guarded_blocked = path.exists() and not force and not _is_managed_unmodified(path, record.render_digest)

        if _record_is_revoked(record, revoked):
            if guarded_blocked:
                result.skipped_local_override.append(record.path)
                continue
            tomb = _tombstone(record.plugin_id)
            _atomic_write(path, tomb)
            records[key] = ProjectionRecord(
                plugin_id=record.plugin_id,
                version=record.version,
                target=record.target,
                tier=record.tier,
                path=record.path,
                render_digest=_digest(tomb),
                source_digest=record.source_digest,
                synced_at=record.synced_at,
            )
            result.tombstoned.append(record.path)
        elif record.plugin_id not in installed or record.plugin_id in allowed_ids:
            # Uninstalled, or a tool that disappeared from a plugin we enumerated
            # cleanly this run. Either way the projection is genuinely stale.
            if guarded_blocked:
                result.skipped_local_override.append(record.path)
                continue
            if path.exists():
                path.unlink()
            _prune_empty_parent(path)
            records.pop(key, None)
            result.reclaimed.append(record.path)


# --------------------------------------------------------------------------- #
# Unsync (explicit reclaim)
# --------------------------------------------------------------------------- #


@dataclass
class UnsyncResult:
    removed: list[str] = field(default_factory=list)
    tombstoned: list[str] = field(default_factory=list)
    skipped_local_override: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return {
            "removed": self.removed,
            "tombstoned": self.tombstoned,
            "skipped_local_override": self.skipped_local_override,
        }


def unsync_plugin_skills(
    *,
    plugin_id: str,
    lock_path: Path | None = None,
    revoked: bool = False,
    force: bool = False,
) -> UnsyncResult:
    """Reclaim projected files for a plugin on uninstall / revoke.

    Normal uninstall deletes the managed file; revoke overwrites it with a
    tombstone so a runtime that already discovered the skill sees an explicit
    notice. A user's local override is left untouched (unless ``force``) and
    reported. Proxy-tier skills are already fail-closed at execution time, so a
    missed file never widens what is reachable.
    """
    lock_path = lock_path if lock_path is not None else default_projection_lock()
    with _hold_lock(lock_path):
        records = load_projection_lock(lock_path)
        result = UnsyncResult()
        remaining: dict[str, ProjectionRecord] = {}

        for key, record in records.items():
            if record.tier != PROXY_TIER or record.plugin_id != plugin_id:
                remaining[key] = record
                continue
            path = Path(record.path)
            if path.exists() and not force and not _is_managed_unmodified(path, record.render_digest):
                result.skipped_local_override.append(record.path)
                remaining[key] = record
                continue
            if revoked:
                tomb = _tombstone(plugin_id)
                _atomic_write(path, tomb)
                result.tombstoned.append(record.path)
                remaining[key] = ProjectionRecord(
                    plugin_id=record.plugin_id,
                    version=record.version,
                    target=record.target,
                    tier=record.tier,
                    path=record.path,
                    render_digest=_digest(tomb),
                    source_digest=record.source_digest,
                    synced_at=record.synced_at,
                )
            else:
                if path.exists():
                    path.unlink()
                _prune_empty_parent(path)
                result.removed.append(record.path)

        save_projection_lock(lock_path, remaining)
    return result


def _prune_empty_parent(path: Path) -> None:
    parent = path.parent
    try:
        if parent.is_dir() and not any(parent.iterdir()):
            parent.rmdir()
    except OSError:
        pass


def _prune_native_empty_parents(path: Path, skill_slug: str) -> None:
    parent = path.parent
    while parent.name != skill_slug:
        try:
            if parent.is_dir() and not any(parent.iterdir()):
                parent.rmdir()
            else:
                return
        except OSError:
            return
        parent = parent.parent
    try:
        if parent.is_dir() and not any(parent.iterdir()):
            parent.rmdir()
    except OSError:
        pass
