import type { AgentTemplateId } from '../canvas/agentTemplates';
import type { Localized, OfficialWorkflow, OfficialWorkflowNode } from './examples/officialWorkflows';

/** The canvases behind the homepage production cases (productionCatalog.ts). Each one is a real
 * workflow: `createOfficialDocument` compiles it into the canvas a member can copy, and the run
 * records in production-runs/ are what AwwO delivered when it ran. The tasks are sized for AwwO's
 * default execution settings — one model call per node and at most 4,096 output tokens — so the
 * hand-offs stay short and every build is a single small HTML file. The knowledge-base case ran on
 * 2026-09-04 with its own canvas and keeps that record (production-runs/knowledge-base.ts). */
const l = (zh: string, en: string): Localized => ({ zh, en });
const n = (id: string, title: Localized, role: AgentTemplateId, column: number, row: number,
  task: Localized, output: Localized, acceptance: Localized, outputType?: 'html'): OfficialWorkflowNode =>
  ({ id, title, role, column, row, task, output, acceptance: [acceptance], ...(outputType ? { outputType } : {}) });
const e = (from: string, to: string, zh: string, en: string) => ({ from, to, label: l(zh, en) });

const BUILD_RULES = l('\n交付要求：单文件 HTML，整页不超过 8000 个字符（约 230 行），不写注释、不留空行；不使用 localStorage、cookie、网络请求或任何外部资源；页面在 iframe 里运行，点击画面后键盘生效；页面适配窗口大小：内容居中、背景铺满、不出现滚动条，canvas 用 CSS 等比缩放到窗口内，鼠标坐标按显示尺寸换算。输出前默默自查，不要写出自查过程：每个 {、(、[ 都成对闭合，上游代码括号不成对时先补齐；上游代码原样复用，不再包一层 try/catch；页面一打开就有画面；第一次操作之前就运行的代码（比如绘制循环）不能读取还没创建的对象，例如还没创建的 AudioContext。只输出 HTML 文档本身：以 <!DOCTYPE html> 开头、以 </html> 结尾，前后不加任何说明。',
  '\nDelivery: one HTML file of at most 8,000 characters (about 230 lines), with no comments or blank lines; no localStorage, cookies, network requests or external resources; the page runs inside an iframe, and keys work once the page is clicked; the page fits its window: content centred, background filling the page, no scrollbars, canvases scaled to fit with CSS keeping their aspect ratio, and mouse positions converted by the displayed size. Check silently before answering and do not write the checks out: every {, ( and [ is closed, fixing unbalanced upstream code first; upstream code is reused as delivered, never wrapped in another try/catch; the page shows something as soon as it opens; and code that runs before the first user action (such as a draw loop) never reads an object that does not exist yet, such as an AudioContext not created yet. Output only the HTML document itself, from <!DOCTYPE html> to </html>, with nothing before or after it.');
const build = (zh: string, en: string) => l(zh + BUILD_RULES.zh, en + BUILD_RULES.en);
// For nodes whose code the build pastes as delivered: a defect here ships in the page.
const CODE = l('代码要能原样粘贴运行：括号成对闭合，不用省略号；顶层不自动运行任何东西（不在顶层调用 setInterval，也不读取还没创建的对象），由调用方在需要时调用。',
  'The code must run as pasted: every bracket closed and no ellipses; nothing runs by itself at the top level (no top-level setInterval, no reads of objects not created yet) — callers invoke it when needed.');
const code = (zh: string, en: string) => l(zh + CODE.zh, `${en} ${CODE.en}`);
const STATIC = l('只能阅读源码时写明“未实际运行”；列出确认通过的项、发现的缺陷（附相关代码片段）和未验证项，不超过 400 字。',
  'If you can only read the source, say “not actually run”; list confirmed items, defects found (with the relevant code) and unverified items, at most 300 words.');
const review = (zh: string, en: string) => l(zh + STATIC.zh, en + STATIC.en);
const KEPT_APART = l('静态检查与实际运行严格区分', 'Static review and actual execution are kept strictly apart');
const AUDIO_LATE = l('首次用户操作后才创建 AudioContext', 'The AudioContext is created only after the first user action');
const SETTINGS = l('按 AwwO 当前默认执行设置，每个节点调用一次模型、最多输出 4096 token，所以规模刻意做小。',
  'Under AwwO’s current default execution settings each node makes one model call with at most 4,096 output tokens, so the scope is deliberately small.');
const limits = (zh: string, en: string) => l(`${zh}${SETTINGS.zh}`, `${en} ${SETTINGS.en}`);
const REVIEW_TITLE = l('验收', 'Review'), REVIEW_OUTPUT = l('验收记录', 'Review record');

const PIXEL: OfficialWorkflow = {
  id: 'pixel-platformer', category: 'game', categoryLabel: l('游戏', 'Game'), accent: '#f59e0b',
  title: l('像素平台跳跃 · 狐狸邮差', 'Pixel platformer · Fox Courier'),
  summary: l('策划定数值，美术、关卡、音效并行，程序合成一关能玩的像素平台跳跃。', 'Design sets the numbers; art, levels and sound work in parallel; code assembles a playable pixel platformer level.'),
  description: l('狐狸邮差在空中集市的屋顶与浮空摊位间跳跃，收集 3 封信送到终点邮筒。像素精灵、关卡地图和音效都是上游 Agent 的产出，程序节点原样合成。', 'A fox courier jumps across sky-market rooftops and floating stalls, collects three letters and delivers them to the mailbox. The sprites, the level map and the sound effects are upstream agents’ outputs; the code node assembles them as delivered.'),
  pattern: l('玩法与数值 → 像素美术 / 关卡地图 / 音效并行 → 程序合成 → 试玩验收', 'Gameplay and tuning → pixel art / level map / sound in parallel → code assembly → playtest review'),
  brief: l('做一款像素风平台跳跃试玩关《狐狸邮差》：狐狸在空中集市的屋顶与浮空摊位间奔跑跳跃，收集 3 封信后碰到终点邮筒即通关。←/→ 或 A/D 移动，空格/↑/W 跳跃，R 重来；碰到尖刺或掉出画面回到起点；画面上显示信件数与用时。像素图形全部由代码绘制，交付单文件 HTML，在浏览器里直接可玩。',
    'Make a pixel-art platformer level, “Fox Courier”: a fox runs and jumps across sky-market rooftops and floating stalls, collects 3 letters, then touches the mailbox at the end to win. ←/→ or A/D to move, Space/↑/W to jump, R to restart; spikes or falling off the screen send the fox back to the start; show letters collected and elapsed time. All pixel graphics are drawn in code; deliver one HTML file that plays directly in the browser.'),
  nodes: [
    n('design', l('玩法与数值', 'Gameplay and tuning'), 'general', 0, 0,
      l('定义核心循环、操作、胜负与重来规则，并给出可以直接写进代码的数值：图块 16 像素、整关就是一屏 20×12 图块（画布 320×192 像素，不需要镜头）、重力、跑速、跳跃初速度、最大下落速度、土狼时间与跳跃缓冲（单位用 像素/帧，按 60 帧）。说明 HUD 与通关画面。用列表和数值表，不超过 450 字。',
        'Define the core loop, controls, win/lose and restart rules, and give numbers that go straight into code: 16-pixel tiles, a level that is exactly one 20×12-tile screen (a 320×192-pixel canvas, no camera), gravity, run speed, jump velocity, max fall speed, coyote time and jump buffering (in pixels/frame at 60 fps). Describe the HUD and the win screen. Use lists and a table, at most 300 words.'),
      l('玩法规格与数值表', 'Gameplay spec and tuning table'), l('数值能直接用于代码；一次跳跃能跨上 3 格高的台阶', 'Numbers can go straight into code; one jump clears a 3-tile step')),
    n('art', l('像素美术', 'Pixel art'), 'materials', 1, 0,
      l('设计不超过 10 色的调色板（十六进制，地面和平台用深色，不用白色），用 8×8 字符画给出精灵：狐狸站立、狐狸奔跑（2 帧）、信件、邮筒、尖刺、地面砖、平台砖。每个精灵是 8 个长度为 8 的字符串，字符 0–9 对应调色板下标，. 表示透明；程序会把每个像素放大 2 倍，画成 16 像素的图块。另用两三句话说明天空渐变和远景云的画法。只输出一个可以直接粘进 JavaScript 的对象，不超过 45 行。',
        'Design a palette of at most 10 colours (hex; dark ground and platforms, never white) and give 8×8 character-art sprites: fox standing, fox running (2 frames), letter, mailbox, spike, ground tile, platform tile. Each sprite is 8 strings of length 8; characters 0–9 index the palette, . is transparent; the code draws every pixel at 2× as a 16-pixel tile. Add two or three sentences on drawing the sky gradient and distant clouds. Output only an object that can be pasted into JavaScript, at most 45 lines.'),
      l('调色板与精灵像素表', 'Palette and sprite grids'), l('每个精灵恰好 8×8，字符都是 0–9 或 .，且在调色板范围内', 'Every sprite is exactly 8×8 and uses only 0–9 or ., all within the palette')),
    n('levels', l('关卡地图', 'Level map'), 'data', 1, 1,
      l('按玩法数值设计一张 12 行 × 20 列的图块地图（正好一屏），用字符串数组表示：# 地面，= 平台，^ 尖刺，L 信件（恰好 3 封），M 邮筒，S 起点，. 空气。起点在左下，中间有间隙和尖刺，邮筒在右上方的高台上；保证用给定的跳跃数值从 S 出发能拿到全部信件并到达 M。附 3 行以内的可达性说明。只输出地图数组和说明。',
        'Using the tuning, design a 12-row × 20-column tile map (exactly one screen) as an array of strings: # ground, = platform, ^ spike, L letter (exactly 3), M mailbox, S start, . air. Start at the lower left, put gaps and spikes in the middle and the mailbox on a high ledge at the upper right; make sure every letter and the mailbox can be reached from S with the given jump numbers. Add at most 3 lines of reachability notes. Output only the map array and the notes.'),
      l('图块地图与可达性说明', 'Tile map and reachability notes'), l('每行恰好 20 个字符；L 恰好 3 个；S、M 各一个', 'Every row is exactly 20 characters; exactly 3 L; one S and one M')),
    n('sound', l('音效', 'Sound effects'), 'materials', 1, 2,
      code('用 Web Audio API 合成跳跃、拾取信件、送达通关、失败重来四个音效。给出一段 JavaScript：sfx(name) 在第一次用户操作后才创建 AudioContext，用振荡器和增益包络合成声音，不加载任何音频文件。不超过 20 行。',
        'Synthesize four sounds with the Web Audio API: jump, letter pickup, delivery/win, and fail/restart. Give a JavaScript snippet: sfx(name) creates the AudioContext only after the first user action and builds each sound from oscillators and gain envelopes, loading no audio files. At most 20 lines.'),
      l('合成音效函数', 'Synthesized sound function'), AUDIO_LATE),
    n('build', l('可玩试玩关', 'Playable level'), 'frontend', 2, 0,
      build('把玩法数值、像素精灵、关卡地图和音效函数合成为完整可玩的游戏：320×192 的 canvas 用 CSS 整数倍放大（image-rendering: pixelated），每个精灵像素画成 2×2，正好铺满一个 16 像素图块；地图行不足 20 列时用 . 补齐；整关在一屏内，不做镜头；图块碰撞（先水平后竖直），收集信件，集齐后碰到邮筒通关，尖刺或坠落回到起点（狐狸低于地图底部就立刻回到起点），HUD 显示信件数与用时，通关后按 R 重来。键盘监听挂在 window 上，用按键状态表处理移动与跳跃。直接复用上游的地图和精灵数据，不要改写。',
        'Assemble the tuning, sprites, level map and sound function into a complete playable game: a 320×192 canvas scaled up by an integer factor with CSS (image-rendering: pixelated), every sprite pixel drawn as 2×2 so a sprite fills one 16-pixel tile, map rows shorter than 20 columns padded with ., the whole level on one screen with no camera, tile collision (horizontal then vertical), letter pickups, winning by touching the mailbox once all letters are collected, spikes or falling sending the fox back to the start (the moment it drops below the bottom of the map), a HUD with letters and time, and R to restart after winning. Listen for keys on window and handle movement and jumping from a key-state table. Reuse the upstream map and sprite data exactly as delivered.'),
      l('可玩试玩关 HTML', 'Playable level HTML'), l('移动、跳跃、碰撞、拾取、通关和重来都真实生效', 'Movement, jumping, collision, pickups, winning and restarting all work'), 'html'),
    n('review', l('试玩验收', 'Playtest review'), 'review', 3, 0,
      review('对照玩法规格和 HTML 源码逐项检查：键位、能否跳上 3 格台阶、碰撞是否穿墙、信件计数、通关条件、尖刺与坠落重来、R 重来、有无外部请求。',
        'Check the HTML source against the gameplay spec item by item: keys, whether a 3-tile step can be cleared, collision tunnelling, the letter count, the win condition, spike and fall resets, R to restart, and any external request. '),
      REVIEW_OUTPUT, KEPT_APART),
  ],
  edges: [e('design', 'art', '画面尺寸与需要的精灵', 'Screen size and sprites needed'), e('design', 'levels', '数值与关卡规则', 'Tuning and level rules'), e('design', 'sound', '音效清单', 'Sound list'),
    e('design', 'build', '玩法与数值', 'Gameplay and tuning'), e('art', 'build', '调色板与精灵', 'Palette and sprites'), e('levels', 'build', '关卡地图', 'Level map'), e('sound', 'build', '音效代码', 'Sound code'),
    e('design', 'review', '验收标准', 'Acceptance criteria'), e('build', 'review', '游戏源码', 'Game source')],
  artifacts: [l('可玩的像素平台跳跃关卡', 'A playable pixel platformer level'), l('调色板与精灵像素表', 'Palette and sprite grids'), l('关卡地图与验收记录', 'Level map and review record')],
  limitations: limits('一个 HTML 试玩关，没有存档、关卡选择或手柄支持。', 'One HTML level without saves, level select or gamepad support.'),
};

const CONFIGURATOR: OfficialWorkflow = {
  id: '3d-configurator', category: '3d', categoryLabel: l('3D 交互', '3D interaction'), accent: '#38bdf8',
  title: l('3D 配置器 · Orvia 电动单车', '3D configurator · Orvia e-bike'),
  summary: l('产品定选项，建模给几何，渲染定投影，前端做出可旋转、可换装的网页配置器。', 'Product sets the options, modelling supplies geometry, rendering fixes the projection, and the front end builds a web configurator you can rotate and restyle.'),
  description: l('为虚构品牌 Orvia 的城市电动单车换车架颜色、电池、车座和前车筐，拖拽旋转、滚轮缩放，价格与续航实时更新。三维投影由 canvas 自绘，不依赖任何 3D 库。', 'Change the frame colour, battery, saddle and basket of a city e-bike from the fictional brand Orvia; drag to rotate, scroll to zoom, and watch price and range update. The 3D projection is drawn on a canvas with no 3D library.'),
  pattern: l('配置项与价格 → 车体三维结构 → 投影与着色方案 → 配置器页面 → 交付验收', 'Options and pricing → 3D bike structure → projection and shading → configurator page → delivery review'),
  brief: l('做一个网页 3D 配置器：虚构品牌 Orvia 的城市电动单车，可换 4 种车架颜色、2 种电池（标准 / 长续航）、2 种车座（运动 / 舒适），可加前车筐；拖拽旋转、滚轮缩放、双击复位，外观实时变化，价格与续航随选项更新（示例价格，页面上标注“示例”）。不引用任何 3D 库，用 canvas 自己做三维投影，交付单文件 HTML。',
    'Build a web 3D configurator for a city e-bike from the fictional brand Orvia: 4 frame colours, 2 batteries (standard / long range), 2 saddles (sport / comfort) and an optional front basket; drag to rotate, scroll to zoom, double-click to reset; the look updates live, and price and range follow the options (sample prices, labelled “sample” on the page). Use no 3D library: do the 3D projection on a canvas yourself, and deliver one HTML file.'),
  nodes: [
    n('product', l('配置项与价格', 'Options and pricing'), 'general', 0, 0,
      l('列出全部配置项：4 种车架颜色（名称与十六进制色值）、电池（续航公里数与加价）、车座、前车筐（加价）；给出基础价、计价公式和页面摘要的格式。价格是示例，页面要标注“示例价格”。用表格，不超过 300 字。',
        'List every option: 4 frame colours (names and hex values), batteries (range in km and price delta), saddles, the front basket (price delta); give the base price, the pricing formula and the format of the summary on the page. Prices are samples and must be labelled “sample prices” on the page. Use a table, at most 200 words.'),
      l('配置表与计价规则', 'Option table and pricing rules'), l('每个选项都有价格或续航影响，计价公式没有歧义', 'Every option has a price or range effect; the pricing formula is unambiguous')),
    n('modelling', l('车体三维结构', '3D bike structure'), 'data', 1, 0,
      l('用简单图元描述整车：坐标系 x 向前、y 向上、z 向侧面，单位厘米，原点在两轮中点下方的地面。给出两个车轮（中心、半径约 35、胎宽），车架管件（头管、上管、下管、立管、后下叉、后上叉、前叉，各给起点、终点、粗细），电池盒（标准与长续航两种尺寸的长方体），两种车座，车把，前车筐（长方体）。每个部件写明 id 以及受哪个配置项控制。只输出可以直接粘进 JavaScript 的数据，不超过 30 行。',
        'Describe the whole bike with simple primitives: x forward, y up, z sideways, in centimetres, with the origin on the ground midway between the wheels. Give two wheels (centre, radius about 35, tyre width), the frame tubes (head, top, down and seat tubes, chain stays, seat stays, fork; start, end and thickness each), the battery box (cuboids in standard and long-range sizes), two saddles, the handlebar and the front basket (a cuboid). Give every part an id and the option that controls it. Output only data that can be pasted into JavaScript, at most 30 lines.'),
      l('三维几何数据', '3D geometry data'), l('比例像一辆真实的城市车（轴距约 110 厘米）；每个可选部件都对应一个配置项', 'Proportions look like a real city bike (a wheelbase of about 110 cm); every optional part maps to an option')),
    n('rendering', l('投影与着色方案', 'Projection and shading'), 'general', 2, 0,
      l('根据几何数据给出 canvas 渲染方案：每个点先减去整车中心，再绕 y 轴和 x 轴旋转；透视投影用 sx = W/2 + f·x/(z+d)、sy = H/2 − f·y/(z+d)（y 向上所以取负；相机距离 d 约为整车长度的 2.5 倍，f = 0.6·W·d / 整车长度，让整车居中、约占视图宽度的 60%），z+d ≤ 1 的点不画；默认从侧前方约 30° 看，滚轮缩放只改 d；管件画成按深度变亮或变暗的粗线，车轮取 32 个点投影成环，长方体做背面剔除与平面着色，所有图元按平均深度从远到近绘制；说明颜色如何套用到部件。给出公式和不超过 20 行的伪代码。',
        'From the geometry, give a canvas rendering plan: subtract the bike’s centre from every point, then rotate about the y and x axes; project with sx = W/2 + f·x/(z+d) and sy = H/2 − f·y/(z+d) (negative because y points up; camera distance d about 2.5 times the bike’s length, f = 0.6·W·d / bike length, so the bike is centred and fills about 60% of the view width), skipping points where z+d ≤ 1; default to a view about 30° off the side, and let the wheel zoom change d only; tubes as thick strokes lit by depth, wheels as rings of 32 projected points, cuboids with back-face culling and flat shading, everything drawn far to near by average depth; explain how colours apply to parts. Give the formulas and at most 20 lines of pseudocode.'),
      l('投影公式与绘制顺序', 'Projection formulas and draw order'), l('不会投影相机背后的点；绘制顺序能处理遮挡', 'Points behind the camera are never projected; the draw order handles occlusion')),
    n('frontend', l('配置器页面', 'Configurator page'), 'frontend', 3, 0,
      build('按配置表、几何数据和渲染方案做出完整页面：canvas 三维视图（拖拽旋转、滚轮缩放、双击复位），选项面板（颜色色块、电池与车座单选、车筐开关）和实时摘要（价格、续航、所选配置），并标注“示例价格”。严格按渲染方案的投影公式实现；视图背景用浅色，深色车架也要清楚可见；切换选项要立即重绘。',
        'From the option table, the geometry and the rendering plan, build the complete page: a canvas 3D view (drag to rotate, scroll to zoom, double-click to reset), an options panel (colour swatches, battery and saddle choices, a basket toggle) and a live summary (price, range, chosen options), labelled “sample prices”. Implement the rendering plan’s projection exactly; give the view a light background so a dark frame stays clearly visible; changing an option redraws at once.'),
      l('3D 配置器 HTML', '3D configurator HTML'), l('每个选项都真实改变画面或价格；旋转与缩放可用', 'Every option really changes the view or the price; rotation and zoom work'), 'html'),
    n('review', l('交付验收', 'Delivery review'), 'review', 4, 0,
      review('对照配置表和 HTML 源码检查：每个选项是否改变画面与价格、计价是否与公式一致、续航数字、旋转与缩放、双击复位、遮挡顺序、“示例价格”标注、有无外部库或请求。',
        'Check the HTML source against the option table: whether each option changes the view and the price, pricing against the formula, range figures, rotation and zoom, double-click reset, occlusion order, the “sample prices” label, and any external library or request. '),
      REVIEW_OUTPUT, KEPT_APART),
  ],
  edges: [e('product', 'modelling', '部件与选项', 'Parts and options'), e('modelling', 'rendering', '几何数据', 'Geometry data'), e('product', 'rendering', '颜色与外观', 'Colours and appearance'),
    e('product', 'frontend', '配置表与价格', 'Options and prices'), e('modelling', 'frontend', '几何数据', 'Geometry data'), e('rendering', 'frontend', '渲染方案', 'Rendering plan'),
    e('product', 'review', '验收标准', 'Acceptance criteria'), e('frontend', 'review', '页面源码', 'Page source')],
  artifacts: [l('可旋转、可换装的 3D 配置器', 'A 3D configurator you can rotate and restyle'), l('配置表与计价规则', 'Option table and pricing rules'), l('三维几何与渲染方案', '3D geometry and rendering plan')],
  limitations: limits('用 canvas 对简单图元做透视投影，不是 WebGL，也没有真实车型的 3D 模型；价格与续航是示例数据。', 'Perspective projection of simple primitives on a canvas — not WebGL and not a real bike model; prices and range are sample data.'),
};

const PAPER: OfficialWorkflow = {
  id: 'papercraft-puzzle', category: 'game', categoryLabel: l('游戏', 'Game'), accent: '#a78bfa',
  title: l('纸艺解谜 · 纸径', 'Papercraft puzzle · Paper Path'),
  summary: l('策划定规则，美术、关卡、音效并行，物理写出旋转与滚动算法，程序合成三关可玩的纸艺解谜。', 'Design sets the rules; art, levels and sound work in parallel; physics writes the rotate-and-roll algorithm; code assembles three playable papercraft puzzles.'),
  description: l('整块纸雕关卡板每次旋转 90°，重力始终向下，小球沿纸板通道滚到底，滚进“家”就过关。三关由易到难，显示步数，可重置。', 'The whole paper board turns 90° at a time while gravity stays down; the marble rolls along the paper channels and wins when it reaches its home. Three levels from easy to hard, with a move counter and reset.'),
  pattern: l('谜题规则 → 纸艺视觉 / 三个关卡 / 纸张音效并行 → 旋转与滚动算法 → 可玩谜题 → 验收', 'Puzzle rules → paper visuals / three levels / paper sounds in parallel → rotate-and-roll algorithm → playable puzzle → review'),
  brief: l('做一款纸艺风解谜《纸径》：画面是一块可旋转的纸雕关卡板，每按一次 Q/E（或 ←/→、屏幕按钮）整板旋转 90°，重力始终向下，小球会一路滚到被挡住为止，滚进“家”的洞口即过关；3 个关卡由易到难，显示步数，可重置本关，通关后进入下一关。用 canvas 画出纸张阴影与折痕质感，交付单文件 HTML。',
    'Make a papercraft puzzle, “Paper Path”: the screen is a paper board that rotates 90° per press of Q/E (or ←/→, or on-screen buttons); gravity always points down, so the marble rolls until something stops it, and the level is won when it reaches its home hole. 3 levels from easy to hard, a move counter, reset for the current level, and the next level after a win. Draw paper shadows and creases on a canvas, and deliver one HTML file.'),
  nodes: [
    n('design', l('谜题规则', 'Puzzle rules'), 'general', 0, 0,
      l('定义规则：9×9 网格，格子类型（纸墙、空格、小球起点、家），每次旋转 90° 后小球沿重力方向连续移动直到被墙挡住，途经或停在家即过关；步数统计、重置、进入下一关；3 关的难度目标（解法约 2、3、4 步）。不超过 350 字。',
        'Define the rules: a 9×9 grid; cell types (paper wall, empty, marble start, home); after each 90° turn the marble keeps moving in the direction of gravity until a wall stops it, and passing over or stopping on home wins; move counting, reset and the next level; difficulty targets for the 3 levels (solutions of about 2, 3 and 4 moves). At most 250 words.'),
      l('规则与关卡目标', 'Rules and level goals'), l('旋转、滚动和过关判定没有歧义', 'Rotation, rolling and winning are unambiguous')),
    n('art', l('纸艺视觉', 'Paper visuals'), 'materials', 1, 0,
      l('给出纸艺视觉方案：调色板（纸白、牛皮纸、阴影色，十六进制），纸墙如何画出凸起感（偏移阴影、折痕线），小球（带高光的玻璃珠），家的洞口，旋转动画（约 250 毫秒缓动），按钮与步数的样式。写成可以直接照做的绘制步骤，不超过 300 字。',
        'Give the papercraft look: a palette (paper white, kraft, shadow colours, in hex), how raised paper walls are drawn (offset shadow, crease lines), the marble (a glass bead with a highlight), the home hole, the rotation animation (about 250 ms with easing), and the buttons and move counter. Write drawing steps that can be followed directly, at most 200 words.'),
      l('视觉与绘制步骤', 'Look and drawing steps'), l('只用 canvas 就能画出来，不需要图片', 'Everything can be drawn on a canvas without images')),
    n('levels', l('三个关卡', 'Three levels'), 'data', 1, 1,
      l('按规则设计 3 个 9×9 关卡，每关是 9 个长度为 9 的字符串：# 纸墙，. 空，O 小球起点，H 家；四周一圈都是墙。为每关写出一个可行解（如 E,E,Q）和步数，并逐步写出小球停下的位置来证明可解（每关不超过 6 行）。只输出关卡数组和解法，不写设计或推敲过程；某个布局验算不通过就换一个更简单的，不要反复修改。全部不超过 50 行。',
        'Design 3 levels of 9×9 by the rules, each as 9 strings of length 9: # paper wall, . empty, O marble start, H home; the outer ring is all wall. For each level give a working solution (such as E,E,Q) and its move count, and list where the marble stops after each move to prove it is solvable (at most 6 lines per level). Output only the level arrays and the solutions, with no design notes or deliberation; if a layout does not check out, switch to a simpler one instead of revising it again and again. At most 50 lines in all.'),
      l('关卡数据与解法', 'Level data and solutions'), l('每关恰好 9×9，O 与 H 各一个，解法可以逐步复现', 'Every level is exactly 9×9 with one O and one H; each solution can be replayed step by step')),
    n('sound', l('纸张音效', 'Paper sounds'), 'materials', 1, 2,
      code('用 Web Audio API 合成三个音效：旋转（经过滤的噪声，像纸张摩擦）、小球滚动停下（轻响）、过关（清脆的和弦）。给出 sfx(name) 的 JavaScript，在第一次用户操作后才创建 AudioContext，不加载音频文件，不超过 20 行。',
        'Synthesize three sounds with the Web Audio API: turning (filtered noise, like paper rubbing), the marble coming to rest (a soft knock) and winning (a bright chord). Give sfx(name) in JavaScript that creates the AudioContext only after the first user action and loads no audio files, at most 20 lines.'),
      l('合成音效函数', 'Synthesized sound function'), AUDIO_LATE),
    n('physics', l('旋转与滚动算法', 'Rotate-and-roll algorithm'), 'backend', 2, 0,
      code('按规则和关卡格式写出纯函数：rotate(grid, dir) 把网格顺时针或逆时针转 90°（小球与家随之转动），roll(grid, pos) 让小球向下连续移动直到被墙挡住、途经家就返回过关。用这两个函数把每一关的解法逐步验算一遍，写出每一步后小球的位置。代码不超过 25 行，验算不超过 10 行。',
        'From the rules and the level format, write pure functions: rotate(grid, dir) turns the grid 90° clockwise or counter-clockwise (the marble and home turn with it), and roll(grid, pos) moves the marble down until a wall stops it, returning a win if it passes home. Use them to replay every level’s solution and write the marble’s position after each step. At most 25 lines of code and 10 lines of checks.'),
      l('算法代码与逐步验算', 'Algorithm code and step-by-step checks'), l('三个关卡的解法都能用这套算法复现过关', 'All three solutions win when replayed with these functions')),
    n('build', l('可玩谜题', 'Playable puzzle'), 'frontend', 3, 0,
      build('把关卡、算法、视觉和音效合成为完整游戏：canvas 绘制纸艺关卡板，Q/E、←/→ 与屏幕按钮触发整板旋转动画，动画结束后小球按算法滚动，显示步数，过关提示并进入下一关，R 或按钮重置本关，三关全部完成后显示结束画面。直接复用上游的关卡数据与算法，不要改写。',
        'Assemble the levels, the algorithm, the look and the sounds into a complete game: draw the paper board on a canvas; Q/E, ←/→ and on-screen buttons start the board-turn animation, after which the marble rolls by the algorithm; show the move count, announce a win and move to the next level; R or a button resets the level; show an ending after all three levels. Reuse the upstream levels and algorithm exactly as delivered.'),
      l('可玩谜题 HTML', 'Playable puzzle HTML'), l('旋转、滚动、过关、重置和换关都真实生效', 'Turning, rolling, winning, resetting and changing levels all work'), 'html'),
    n('review', REVIEW_TITLE, 'review', 4, 0,
      review('对照规则、关卡解法和 HTML 源码检查：旋转方向是否与按键一致、滚动是否穿墙、途经家是否判定过关、步数、重置、换关、三关数据是否与上游一致、有无外部请求。',
        'Check the HTML source against the rules and the solutions: whether turn direction matches the keys, whether rolling tunnels through walls, whether passing home wins, the move count, reset, level changes, whether the three levels match upstream, and any external request. '),
      REVIEW_OUTPUT, KEPT_APART),
  ],
  edges: [e('design', 'art', '画面元素', 'Visual elements'), e('design', 'levels', '规则与难度目标', 'Rules and difficulty goals'), e('design', 'sound', '音效清单', 'Sound list'),
    e('design', 'physics', '移动规则', 'Movement rules'), e('levels', 'physics', '关卡与解法', 'Levels and solutions'), e('design', 'build', '规则与流程', 'Rules and flow'),
    e('levels', 'build', '关卡数据', 'Level data'), e('physics', 'build', '旋转与滚动代码', 'Rotate-and-roll code'), e('art', 'build', '视觉方案', 'Look'), e('sound', 'build', '音效代码', 'Sound code'),
    e('levels', 'review', '解法', 'Solutions'), e('build', 'review', '游戏源码', 'Game source')],
  artifacts: [l('三关可玩的纸艺解谜', 'Three playable papercraft puzzles'), l('关卡数据与解法', 'Level data and solutions'), l('旋转与滚动算法', 'Rotate-and-roll algorithm')],
  limitations: limits('三个固定关卡，没有关卡编辑器或存档。', 'Three fixed levels without a level editor or saves.'),
};

const AD: OfficialWorkflow = {
  id: 'summer-ad', category: 'design', categoryLabel: l('广告', 'Ad'), accent: '#f97316',
  title: l('夏日气泡水广告 · 血橙', 'Summer sparkling-drink ad · Blood orange'),
  summary: l('脚本、分镜、剪辑、调色一路交接，最后做出一版可以播放的 30 秒动态分镜。', 'Script, storyboard, edit and grade hand off in turn, ending in a 30-second animatic you can play.'),
  description: l('为一款虚构的血橙气泡水做 30 秒广告的前期方案：脚本、10 个镜头的分镜、精确到 0.1 秒的剪辑表和调色方案，再用 HTML 做出可播放的动态分镜。AwwO 的 Agent 不拍摄，也不生成视频。', 'Pre-production for a 30-second ad for a fictional blood-orange sparkling drink: the script, a 10-shot storyboard, an edit sheet to 0.1 s and a grade, then a playable HTML animatic. AwwO’s agents neither film nor generate video.'),
  pattern: l('广告脚本 → 分镜 → 剪辑节奏 / 调色方案并行 → 动态分镜 → 验收', 'Script → storyboard → edit timing / grade in parallel → animatic → review'),
  brief: l('为一款虚构品牌的血橙气泡水做一支 30 秒夏日广告的前期方案与动态分镜：血橙色主调，冲击力强，节奏快。交付广告脚本、10 个镜头的分镜、精确到 0.1 秒的剪辑节奏表（总长正好 30.0 秒）、调色方案，以及一版可在浏览器里播放的 30 秒 HTML 动态分镜（用形状、文字与转场示意每个镜头）。品牌与口号都是虚构的；不生成、也不冒称拍摄或生成了真实视频素材。',
    'Pre-produce a 30-second summer ad for a fictional brand’s blood-orange sparkling drink, with an animatic: a blood-orange palette, high impact, fast cuts. Deliver the script, a 10-shot storyboard, an edit timing sheet to 0.1 s (exactly 30.0 s in total), a grade, and a 30-second HTML animatic that plays in the browser (shapes, text and transitions standing in for each shot). The brand and slogan are fictional; do not generate, or claim to have filmed or generated, real footage.'),
  nodes: [
    n('script', l('广告脚本', 'Script'), 'materials', 0, 0,
      l('写出创意概念、虚构品牌名与一句口号（注明“虚构”）、旁白与屏幕字幕、音乐风格与 BPM，并把 30 秒分成 4 段：0–3 秒抓眼球、3–15 秒产品、15–25 秒高潮、25–30 秒落版。不超过 400 字。',
        'Write the concept, a fictional brand name and one slogan (marked “fictional”), the voice-over and on-screen supers, the music style and BPM, and split the 30 seconds into 4 parts: 0–3 s hook, 3–15 s product, 15–25 s peak, 25–30 s end card. At most 250 words.'),
      l('脚本与节拍结构', 'Script and beat structure'), l('四段时长加起来正好 30 秒；品牌与口号标明虚构', 'The four parts add up to exactly 30 s; brand and slogan are marked fictional')),
    n('boards', l('分镜', 'Storyboard'), 'materials', 1, 0,
      l('按脚本写 10 个镜头的分镜表：镜号、时长（秒，一位小数）、景别、画面内容、镜头运动、屏幕文字。10 个镜头的时长加起来正好 30.0 秒。用表格，不超过 450 字。',
        'From the script, write a 10-shot storyboard table: shot number, duration (seconds, one decimal), framing, what is on screen, camera move and on-screen text. The 10 durations add up to exactly 30.0 s. Use a table, at most 300 words.'),
      l('10 镜分镜表', '10-shot storyboard'), l('恰好 10 个镜头，时长合计 30.0 秒', 'Exactly 10 shots totalling 30.0 s')),
    n('edit', l('剪辑节奏表', 'Edit timing sheet'), 'general', 2, 0,
      l('按分镜和脚本的 BPM 做剪辑表：每个镜头的入点与出点（累计时间，一位小数）、转场方式（硬切、甩切、闪白等）、卡在哪个节拍上、音效提示。最后一行写总长，必须是 30.0 秒。用表格，不超过 350 字。',
        'From the storyboard and the script’s BPM, make the edit sheet: each shot’s in and out (running time, one decimal), the transition (cut, whip, flash…), the beat it lands on, and a sound cue. The last row gives the total, which must be 30.0 s. Use a table, at most 250 words.'),
      l('剪辑节奏表', 'Edit timing sheet'), l('入出点首尾相接，总长正好 30.0 秒', 'In and out points are contiguous and total exactly 30.0 s')),
    n('grade', l('调色方案', 'Grade'), 'general', 2, 1,
      l('按脚本与分镜给出调色方案：主色板（血橙、深红、冰白、暗部色，十六进制）、对比度与饱和度的处理、高光与暗部的色彩倾向、各段落的色彩变化、肤色保护。不超过 250 字。',
        'From the script and the storyboard, give the grade: the main palette (blood orange, deep red, ice white, shadow colour, in hex), contrast and saturation handling, highlight and shadow tints, colour changes across the parts, and skin-tone protection. At most 180 words.'),
      l('调色方案与色板', 'Grade and palette'), l('色板可以直接用于页面', 'The palette can be used directly on a page')),
    n('animatic', l('动态分镜', 'Animatic'), 'frontend', 3, 0,
      build('按剪辑表和调色方案做一个 30 秒的 HTML 动态分镜播放器：严格按剪辑表的入出点依次播放 10 个镜头，每个镜头用形状、文字和动画示意画面与运动，套用调色色板，转场按剪辑表；提供播放/暂停、可拖动的时间轴、当前镜号与时间码，播完可重播。不要声称这是成片。',
        'From the edit sheet and the grade, build a 30-second HTML animatic player: play the 10 shots in order at exactly the edit sheet’s in and out points, show each shot’s picture and movement with shapes, text and animation in the grade palette, and use the edit sheet’s transitions; provide play/pause, a draggable timeline, the current shot number and timecode, and replay at the end. Do not present it as the finished film.'),
      l('可播放的动态分镜 HTML', 'Playable animatic HTML'), l('总长 30.0 秒，镜头切换时间与剪辑表一致', 'Total length 30.0 s; shot changes match the edit sheet'), 'html'),
    n('review', REVIEW_TITLE, 'review', 4, 0,
      l('核对分镜、剪辑表与动态分镜源码：镜头是否恰好 10 个、分镜与剪辑表时长是否一致且合计 30.0 秒、动态分镜的切换时间是否与剪辑表一致、是否使用调色色板、品牌与口号是否标明虚构、有无把示意说成真实素材。只能阅读源码时写明“未实际播放”；列出通过项、缺陷和未验证项，不超过 400 字。',
        'Check the storyboard, the edit sheet and the animatic source: exactly 10 shots, storyboard and edit durations matching and totalling 30.0 s, the animatic’s shot changes matching the edit sheet, use of the grade palette, the brand and slogan marked fictional, and no illustration presented as real footage. If you can only read the source, say “not actually played”; list passed items, defects and unverified items, at most 300 words.'),
      REVIEW_OUTPUT, l('时长逐项核算，静态检查与实际播放严格区分', 'Durations are checked line by line; static review and actual playback are kept apart')),
  ],
  edges: [e('script', 'boards', '脚本与节拍', 'Script and beats'), e('script', 'edit', 'BPM 与段落', 'BPM and parts'), e('boards', 'edit', '镜头与时长', 'Shots and durations'),
    e('script', 'grade', '情绪与色彩', 'Mood and colour'), e('boards', 'grade', '画面内容', 'Picture content'), e('boards', 'animatic', '镜头内容', 'Shot content'),
    e('edit', 'animatic', '剪辑节奏表', 'Edit sheet'), e('grade', 'animatic', '色板', 'Palette'), e('boards', 'review', '分镜表', 'Storyboard'), e('edit', 'review', '剪辑表', 'Edit sheet'),
    e('animatic', 'review', '动态分镜源码', 'Animatic source')],
  artifacts: [l('可播放的 30 秒动态分镜', 'A playable 30-second animatic'), l('脚本、分镜与剪辑表', 'Script, storyboard and edit sheet'), l('调色方案', 'Grade')],
  limitations: limits('交付的是广告前期方案和用形状示意的动态分镜，不是成片；AwwO 的 Agent 不拍摄，也不生成视频。案例封面的画面由 AI 视频模型生成，仅作示意，与这张画布的运行无关。',
    'It delivers pre-production and an animatic drawn with shapes — not the finished film; AwwO’s agents neither film nor generate video. The case cover footage was made by an AI video model as an illustration and has nothing to do with this canvas’s run.'),
};

const PORT: OfficialWorkflow = {
  id: 'port-twin', category: '3d', categoryLabel: l('数字孪生', 'Digital twin'), accent: '#22d3ee',
  title: l('港口三维驾驶舱', '3D port cockpit'),
  summary: l('建模和数据并行起步，渲染定等距画法，前端做成场景与指标联动的驾驶舱。', 'Modelling and data start in parallel, rendering fixes the isometric drawing, and the front end builds a cockpit where the scene and the metrics move together.'),
  description: l('虚构港口的 3 个泊位、4 台岸桥、6 块堆场和进出港船只在等距三维场景里随模拟数据变化；点击船或岸桥看详情。全部是标注过的模拟数据。', 'Three berths, four quay cranes, six yard blocks and the ships of a fictional port change in an isometric 3D scene as simulated data advances; click a ship or a crane for details. All data is simulated and labelled as such.'),
  pattern: l('港口场景结构 / 模拟数据模型并行 → 等距渲染方案 → 驾驶舱页面 → 验收', 'Port layout / simulation model in parallel → isometric rendering → cockpit page → review'),
  brief: l('把一座虚构港口做成三维驾驶舱：等距 3D 场景里有 3 个泊位、4 台岸桥、6 个集装箱堆场区块和进出港的船；每 2 秒推进一次模拟数据——船舶到港、靠泊作业、离港，岸桥作业量和堆场占用随之变化；场景着色与指标面板联动，点击船或岸桥查看详情，可暂停与加速；页面明确标注“模拟数据”。canvas 自绘，不用外部库，交付单文件 HTML。',
    'Turn a fictional port into a 3D cockpit: an isometric scene with 3 berths, 4 quay cranes, 6 container-yard blocks and ships coming and going; every 2 seconds the simulation advances — ships arrive, berth and work, then leave, and crane moves and yard occupancy change with them; scene colours and a metrics panel move together; click a ship or crane for details; pause and speed up; label the page “simulated data”. Draw on a canvas with no external library, and deliver one HTML file.'),
  nodes: [
    n('layout', l('港口场景结构', 'Port layout'), 'data', 0, 0,
      l('用网格坐标描述港口：岸线、3 个泊位（位置与长度）、4 台岸桥（所在泊位与轨道范围）、6 个堆场区块（位置、尺寸、容量 TEU）、航道与锚地、船的尺寸档位。给出等距投影常数（图块宽高）。只输出可以直接粘进 JavaScript 的数据，不超过 25 行。',
        'Describe the port in grid coordinates: the quay line, 3 berths (position and length), 4 quay cranes (their berth and rail range), 6 yard blocks (position, size, capacity in TEU), the channel and anchorage, and ship size classes. Give isometric projection constants (tile width and height). Output only data that can be pasted into JavaScript, at most 25 lines.'),
      l('场景几何数据', 'Scene geometry data'), l('物体之间不重叠，岸桥都落在泊位上', 'No objects overlap; every crane sits on a berth')),
    n('sim', l('模拟数据模型', 'Simulation model'), 'data', 0, 1,
      code('写出可复现的模拟：带种子的随机数（如 mulberry32），船的状态机（锚地等待 → 靠泊 → 作业 → 离港），每 2 秒一拍，岸桥作业速度（自然箱/小时），堆场占用的增减规则，以及指标：泊位占用率、岸桥作业量、堆场占用率、等待船数、当天累计吞吐。给出纯 JavaScript 的 init(seed) 与 step(state)，不超过 30 行。',
        'Write a reproducible simulation: a seeded random generator (such as mulberry32), a ship state machine (waiting at anchorage → berthing → working → departing), one tick every 2 seconds, crane rates (moves per hour), rules for yard occupancy, and metrics: berth occupancy, crane moves, yard occupancy, ships waiting, throughput so far today. Give pure JavaScript init(seed) and step(state), at most 30 lines.'),
      l('模拟代码与指标定义', 'Simulation code and metric definitions'), l('同一种子结果相同；占用率不超过 100%', 'The same seed gives the same result; occupancy never exceeds 100%')),
    n('render', l('等距渲染方案', 'Isometric rendering'), 'general', 1, 0,
      l('根据场景数据和模拟状态给出渲染方案：等距投影公式、按 (x+y) 深度排序的绘制顺序、把泊位、堆场、集装箱堆、岸桥和船画成拉伸的立方体、状态配色（空闲、作业、等待、告警）、两次 tick 之间的插值动画、鼠标点击命中检测。给出公式和不超过 20 行的伪代码。',
        'From the layout and the simulation state, give the rendering plan: the isometric projection formula, draw order sorted by (x+y) depth, berths, yard blocks, container stacks, cranes and ships as extruded boxes, status colours (idle, working, waiting, alarm), interpolated animation between ticks, and hit-testing for clicks. Give the formulas and at most 20 lines of pseudocode.'),
      l('渲染公式与绘制顺序', 'Rendering formulas and draw order'), l('遮挡顺序正确，点击能命中具体对象', 'Occlusion order is right and clicks hit specific objects')),
    n('frontend', l('驾驶舱页面', 'Cockpit page'), 'frontend', 2, 0,
      build('合成完整驾驶舱：canvas 等距场景（随模拟每 2 秒推进并平滑动画）、指标面板与事件日志、点击船或岸桥显示详情、暂停与 1×/4× 速度切换，页面醒目标注“模拟数据”。用 setInterval 按速度推进模拟，requestAnimationFrame 只负责插值和绘制。直接复用上游的场景数据与模拟代码，不要改写。这个页面内容多，整页控制在 7000 个字符以内。',
        'Assemble the complete cockpit: an isometric canvas scene that advances every 2 seconds with smooth animation, a metrics panel and event log, details when a ship or crane is clicked, pause and 1×/4× speed, and a prominent “simulated data” label. Advance the simulation with setInterval at the chosen speed, and use requestAnimationFrame only to interpolate and draw. Reuse the upstream layout and simulation code exactly as delivered. This page has a lot in it, so keep it within 7,000 characters.'),
      l('三维驾驶舱 HTML', '3D cockpit HTML'), l('场景、指标与日志随模拟同步变化', 'Scene, metrics and log change together with the simulation'), 'html'),
    n('review', REVIEW_TITLE, 'review', 3, 0,
      review('对照模拟代码和 HTML 源码检查：模拟是否每 2 秒推进、指标计算是否与定义一致、占用率是否越界、遮挡顺序、点击详情、暂停与加速、“模拟数据”标注、有无外部库或请求。',
        'Check the HTML source against the simulation code: whether the simulation advances every 2 seconds, metrics against their definitions, occupancy bounds, occlusion order, click details, pause and speed, the “simulated data” label, and any external library or request. '),
      REVIEW_OUTPUT, KEPT_APART),
  ],
  edges: [e('layout', 'render', '场景几何', 'Scene geometry'), e('sim', 'render', '状态与配色依据', 'States to colour by'), e('layout', 'frontend', '场景数据', 'Layout data'),
    e('sim', 'frontend', '模拟代码', 'Simulation code'), e('render', 'frontend', '渲染方案', 'Rendering plan'), e('sim', 'review', '指标定义', 'Metric definitions'), e('frontend', 'review', '页面源码', 'Page source')],
  artifacts: [l('场景与指标联动的三维驾驶舱', 'A 3D cockpit with a linked scene and metrics'), l('可复现的港口模拟', 'A reproducible port simulation'), l('等距渲染方案', 'Isometric rendering plan')],
  limitations: limits('虚构港口、模拟数据，不连接任何真实设备或业务系统；“三维”是 canvas 等距投影，不是 WebGL。', 'A fictional port with simulated data, connected to no real equipment or systems; the 3D view is an isometric canvas projection, not WebGL.'),
};

const GLIDER: OfficialWorkflow = {
  id: 'glider-adventure', category: 'game', categoryLabel: l('游戏', 'Game'), accent: '#60a5fa',
  title: l('云海滑翔冒险', 'Cloud-sea glider adventure'),
  summary: l('策划定飞行手感，美术和音效并行，程序做出能玩的无尽滑翔。', 'Design sets the flight feel, art and sound work in parallel, and code builds a playable endless glide.'),
  description: l('驾驶纸滑翔机在云海上空飞行：按住爬升、松开俯冲，穿过发光的上升气流补充高度，收集浮岛上的光点。撞上浮岛或掉进云海即结束。', 'Fly a paper glider over a sea of clouds: hold to climb, release to dive, ride glowing updrafts to regain height and collect light orbs on floating islands. Hitting an island or dropping into the clouds ends the flight.'),
  pattern: l('飞行手感与生成规则 → 画面 / 音效并行 → 可玩试玩版 → 验收', 'Flight feel and generation rules → visuals / sound in parallel → playable build → review'),
  brief: l('做一款能玩的滑翔冒险试玩版《云海滑翔》：在云海上空驾驶纸滑翔机，按住空格、鼠标或触屏时抬头爬升，松开俯冲加速；穿过会发光的上升气流补充高度，收集浮岛上的光点得分；撞上浮岛或触到云海即结束，显示飞行距离、得分和本次打开页面以来的最好成绩，可以立刻重开。canvas 自绘视差云层与发光效果，交付单文件 HTML。',
    'Make a playable glider adventure, “Cloud-Sea Glide”: fly a paper glider over a sea of clouds; holding Space, the mouse or a touch pitches up to climb, and releasing dives to gain speed; flying through glowing updrafts restores height, and light orbs on floating islands score points; hitting an island or touching the clouds ends the run, showing distance, score and the best result since the page was opened, with an instant restart. Draw parallax cloud layers and glow effects on a canvas, and deliver one HTML file.'),
  nodes: [
    n('design', l('飞行手感与生成规则', 'Flight feel and generation'), 'general', 0, 0,
      l('给出可以直接写进代码的飞行模型：重力、按住时的升力、阻力、俯冲加速与最大速度（像素/帧，按 60 帧）；浮岛、上升气流、光点的生成间距与随机范围，难度随距离增加的方式；碰撞判定、计分、结束与重开规则。数值要让手感轻盈，以这组为基准微调：松手时下沉加速度约 0.05、最大下沉速度约 1；按住时向上加速度约 0.15、最大爬升速度约 2（像素/帧）。这样从起飞高度什么都不按、滑到云海至少要 4 秒。用列表和数值表，不超过 400 字。',
        'Give a flight model that goes straight into code: gravity, lift while holding, drag, dive acceleration and top speed (pixels/frame at 60 fps); spacing and random ranges for islands, updrafts and orbs, and how difficulty grows with distance; collision, scoring, game over and restart rules. Make it float, tuning around this baseline: released, a sink acceleration of about 0.05 and a top sink speed of about 1; held, an upward acceleration of about 0.15 and a top climb speed of about 2 (pixels/frame). With no input the glider then needs at least 4 seconds to drift from take-off height to the clouds. Use lists and a table, at most 280 words.'),
      l('飞行与生成规格', 'Flight and generation spec'), l('数值能直接用于代码，开局 10 秒内不会必死', 'Numbers can go straight into code; the first 10 seconds are survivable')),
    n('art', l('画面', 'Visuals'), 'materials', 1, 0,
      l('给出画面方案：黎明天空渐变与云海颜色（十六进制），三层视差云的速度比例与画法，纸滑翔机的多边形顶点与倾角表现，浮岛的轮廓画法（岩体与草顶），上升气流的发光画法（径向渐变或 shadowBlur），光点与得分界面的样式。写成可以照做的绘制步骤，不超过 300 字。',
        'Give the look: dawn sky gradient and cloud-sea colours (hex), the speed ratios and drawing of three parallax cloud layers, the paper glider as polygon points and how it tilts, how floating islands are outlined (rock and a grassy top), the glowing updraft (radial gradient or shadowBlur), and the orbs and score display. Write drawing steps that can be followed directly, at most 200 words.'),
      l('画面与绘制步骤', 'Look and drawing steps'), l('只用 canvas 就能画出来', 'Everything can be drawn on a canvas')),
    n('sound', l('音效', 'Sound'), 'materials', 1, 1,
      code('用 Web Audio API 合成：随速度变化的风声循环（经过滤的噪声）、进入上升气流的呼啸声、拾取光点的清脆音、坠落结束的闷响。给出 JavaScript：startWind()、setWind(speed)、sfx(name)，第一次用户操作后才创建 AudioContext，不加载音频文件，不超过 25 行。',
        'Synthesize with the Web Audio API: a wind loop that follows speed (filtered noise), a whoosh on entering an updraft, a bright chime for orbs, and a thud on crashing. Give JavaScript startWind(), setWind(speed) and sfx(name) that create the AudioContext only after the first user action and load no audio files, at most 25 lines.'),
      l('合成音效代码', 'Synthesized sound code'), AUDIO_LATE),
    n('build', l('可玩试玩版', 'Playable build'), 'frontend', 2, 0,
      build('按飞行规格、画面方案和音效代码做出完整游戏，用一个状态变量管理 ready → fly → over 三个阶段，每一帧都按当前阶段更新和绘制：ready 画面提示“按住空格起飞”，按下空格、鼠标或触屏进入 fly；fly 中按住爬升、松开下沉，按规格的数值运动，滑翔机从画面中部起飞，开局 3 秒内不生成浮岛；视差云层、程序生成的浮岛、气流与光点；撞到浮岛或碰到云海进入 over，显示距离、得分和本次页面内的最好成绩（只存在变量里），按空格或点击立即重新起飞。',
        'From the flight spec, the look and the sound code, build the complete game with one state variable for three phases, ready → fly → over, updating and drawing the current phase every frame: the ready screen says “hold Space to take off”, and pressing Space, the mouse or a touch starts fly; in fly, holding climbs and releasing sinks by the spec’s numbers, the glider takes off from mid-screen, and no island appears in the first 3 seconds; parallax clouds, procedurally generated islands, updrafts and orbs; hitting an island or touching the clouds goes to over, which shows distance, score and the best result for this page visit (kept in a variable only), and Space or a click takes off again at once.'),
      l('可玩的滑翔游戏 HTML', 'Playable glider game HTML'), l('爬升、俯冲、气流、得分、结束和重开都真实生效', 'Climbing, diving, updrafts, scoring, game over and restart all work'), 'html'),
    n('review', REVIEW_TITLE, 'review', 3, 0,
      review('对照飞行规格和 HTML 源码检查：按住与松开的手感参数、气流是否补充高度、光点计分、浮岛与云海碰撞、开局是否可生存、最好成绩是否只在内存、重开是否清空状态、有无外部请求。',
        'Check the HTML source against the flight spec: hold and release parameters, whether updrafts restore height, orb scoring, island and cloud collisions, whether the start is survivable, whether the best result stays in memory only, whether restart clears state, and any external request. '),
      REVIEW_OUTPUT, KEPT_APART),
  ],
  edges: [e('design', 'art', '元素清单', 'Element list'), e('design', 'sound', '音效时机', 'Sound cues'), e('design', 'build', '飞行与生成规格', 'Flight and generation spec'),
    e('art', 'build', '画面方案', 'Look'), e('sound', 'build', '音效代码', 'Sound code'), e('design', 'review', '验收标准', 'Acceptance criteria'), e('build', 'review', '游戏源码', 'Game source')],
  artifacts: [l('能玩的云海滑翔试玩版', 'A playable cloud-sea glider build'), l('飞行与生成规格', 'Flight and generation spec'), l('画面方案与合成音效', 'Visual plan and synthesized sound')],
  limitations: limits('无尽模式的单个试玩版，最好成绩只保留到关闭页面。', 'A single endless-mode build; the best result lasts until the page is closed.'),
};

const PARTY: OfficialWorkflow = {
  id: 'party-game', category: 'game', categoryLabel: l('游戏', 'Game'), accent: '#34d399',
  title: l('四人派对游戏 · 冰面抢鱼', 'Party game · Ice Fish Frenzy'),
  summary: l('策划定规则，角色、物理、音效并行，程序做出四人同屏的冰面抢鱼。', 'Design sets the rules; characters, physics and sound work in parallel; code builds a four-player couch game of grabbing fish on the ice.'),
  description: l('四只小企鹅在会滑的冰面上抢鱼，一局 60 秒：惯性滑行、相互碰撞弹开、掉出冰面后复活。四组键位共用一个键盘，可选 2–4 人。', 'Four penguins scramble for fish on slippery ice in 60-second rounds: they slide with momentum, bounce off each other and respawn after falling off. Four key sets share one keyboard; 2–4 players.'),
  pattern: l('规则与键位 → 角色 / 物理 / 音效并行 → 四人可玩版 → 验收', 'Rules and keys → characters / physics / sound in parallel → four-player build → review'),
  brief: l('做一款四人同屏派对小游戏《冰面抢鱼》：4 只小企鹅在一块会滑的冰面上抢鱼，一局 60 秒；企鹅有惯性、摩擦很小，互相碰撞会被弹开，掉出冰面 2 秒后在中心复活；鱼不断随机刷新，普通鱼 1 分、金鱼 3 分；四组键位 WASD / 方向键 / IJKL / 数字键 8-4-5-6，开局可选 2–4 名玩家；倒计时结束显示排名，可再来一局。canvas 自绘，交付单文件 HTML。',
    'Make a four-player couch party game, “Ice Fish Frenzy”: 4 penguins scramble for fish on a slippery ice floe in 60-second rounds; penguins have momentum and little friction, bounce apart when they collide, and respawn in the centre 2 seconds after falling off; fish keep spawning at random, a normal fish scores 1 and a golden fish 3; key sets WASD / arrows / IJKL / numpad 8-4-5-6, and 2–4 players can be chosen at the start; when time runs out show the ranking and offer another round. Draw on a canvas and deliver one HTML file.'),
  nodes: [
    n('design', l('规则与键位', 'Rules and keys'), 'general', 0, 0,
      l('定义一局的流程（选人数、倒计时 3 秒、60 秒对局、结算）、四组键位、计分（普通鱼 1、金鱼 3）、鱼的刷新节奏与上限、掉落与复活规则、平局处理，以及屏幕布局（冰面在中间、四个计分牌在四角）。不超过 350 字。',
        'Define the round flow (choose players, a 3-second countdown, a 60-second round, results), the four key sets, scoring (normal fish 1, golden fish 3), fish spawn rate and cap, falling and respawn rules, ties, and the screen layout (ice in the middle, four scoreboards in the corners). At most 250 words.'),
      l('规则与流程', 'Rules and flow'), l('流程、计分和键位没有冲突', 'Flow, scoring and keys do not conflict')),
    n('characters', l('角色与场景', 'Characters and scene'), 'materials', 1, 0,
      l('给出四只企鹅的配色（十六进制，用围巾颜色区分玩家）与用 canvas 画企鹅的步骤（身体椭圆、白肚皮、喙、鳍、围巾、滑行时的倾斜），普通鱼与金鱼的画法，冰面的样式（裂纹、边缘高光、外圈海水），计分牌样式。写成可照做的绘制步骤，不超过 300 字。',
        'Give four penguin colour schemes (hex; scarves tell players apart) and the steps to draw a penguin on a canvas (body ellipse, white belly, beak, flippers, scarf, a lean while sliding), how to draw normal and golden fish, the ice floe (cracks, rim highlight, sea around it) and the scoreboards. Write drawing steps that can be followed directly, at most 200 words.'),
      l('角色与场景绘制步骤', 'Character and scene drawing steps'), l('四名玩家一眼可分', 'The four players are easy to tell apart')),
    n('physics', l('冰面物理', 'Ice physics'), 'backend', 1, 1,
      code('写出纯 JavaScript 的物理更新 step(penguins, input, dt)：输入加速度、低摩擦衰减（按 dt 指数衰减）、最高速度、圆与圆的弹性碰撞（含分离，避免重叠粘连）、出界判定与复活计时。给出常数与代码，不超过 30 行。',
        'Write a pure JavaScript physics update step(penguins, input, dt): input acceleration, low-friction decay (exponential in dt), top speed, elastic circle–circle collisions (with separation so they never stick), off-ice detection and respawn timers. Give the constants and the code, at most 30 lines.'),
      l('物理代码与常数', 'Physics code and constants'), l('碰撞后不会互相卡住；帧率变化时手感一致', 'Penguins never stick after collisions; the feel holds at varying frame rates')),
    n('sound', l('音效', 'Sound'), 'materials', 1, 2,
      code('用 Web Audio API 合成：抓到鱼（短促上扬）、抓到金鱼（更亮的和弦）、相撞（低沉的“嘭”）、掉水（水花噪声）、倒计时与终场哨声。给出 sfx(name) 的 JavaScript，第一次用户操作后才创建 AudioContext，不加载音频文件，不超过 20 行。',
        'Synthesize with the Web Audio API: catching a fish (a short rising blip), a golden fish (a brighter chord), a bump (a low thud), a splash (water noise), and the countdown and final whistle. Give sfx(name) in JavaScript that creates the AudioContext only after the first user action and loads no audio files, at most 20 lines.'),
      l('合成音效函数', 'Synthesized sound function'), AUDIO_LATE),
    n('build', l('四人可玩版', 'Four-player build'), 'frontend', 2, 0,
      build('合成完整游戏，用一个状态变量管理 menu → countdown → play → end 四个阶段，每一帧都按当前阶段更新和绘制：menu 画面按 2、3、4 键选人数（默认 4 人），按空格开始；countdown 显示 3、2、1 后进入 play；play 持续 60 秒，四组键位同时有效（用 keydown/keyup 状态表），企鹅按物理代码滑行与碰撞，鱼随机刷新与计分，掉出冰面 2 秒后复活，四角计分牌；end 显示排名，按空格清空分数再来一局。直接复用上游的物理代码，不要改写。这个游戏内容多，整页控制在 7000 个字符以内。',
        'Assemble the complete game with one state variable for four phases, menu → countdown → play → end, updating and drawing the current phase every frame: on the menu, keys 2, 3 and 4 choose the number of players (default 4) and Space starts; the countdown shows 3, 2, 1 and then play begins; play lasts 60 seconds with all four key sets active at once (a keydown/keyup state table), penguins sliding and colliding by the physics code, random fish spawns and scoring, respawn 2 seconds after falling off, and scoreboards in the corners; the end screen shows the ranking, and Space clears the scores for another round. Reuse the upstream physics code exactly as delivered. This game has a lot in it, so keep the page within 7,000 characters.'),
      l('四人同屏游戏 HTML', 'Four-player game HTML'), l('多名玩家同时按键互不干扰；计分与排名正确', 'Several players can press keys at once without interfering; scores and ranking are right'), 'html'),
    n('review', REVIEW_TITLE, 'review', 3, 0,
      review('对照规则和 HTML 源码检查：四组键位是否同时生效（keydown/keyup 状态表）、人数选择、碰撞弹开与防粘连、掉落复活、普通鱼与金鱼计分、60 秒倒计时、排名与平局、再来一局是否清空状态、有无外部请求。',
        'Check the HTML source against the rules: whether all four key sets work at once (a keydown/keyup state table), player selection, bouncing without sticking, falling and respawn, normal and golden fish scores, the 60-second timer, ranking and ties, whether play-again clears state, and any external request. '),
      REVIEW_OUTPUT, KEPT_APART),
  ],
  edges: [e('design', 'characters', '角色与布局', 'Characters and layout'), e('design', 'physics', '移动与掉落规则', 'Movement and falling rules'), e('design', 'sound', '音效时机', 'Sound cues'),
    e('design', 'build', '规则与流程', 'Rules and flow'), e('characters', 'build', '绘制步骤', 'Drawing steps'), e('physics', 'build', '物理代码', 'Physics code'), e('sound', 'build', '音效代码', 'Sound code'),
    e('design', 'review', '验收标准', 'Acceptance criteria'), e('build', 'review', '游戏源码', 'Game source')],
  artifacts: [l('四人同屏的冰面抢鱼', 'A four-player game of grabbing fish on the ice'), l('冰面物理代码', 'Ice physics code'), l('角色与音效方案', 'Characters and sound')],
  limitations: limits('四名玩家共用一个键盘，没有手柄与联网对战。', 'Four players share one keyboard; no gamepads or online play.'),
};

const RHYTHM: OfficialWorkflow = {
  id: 'rhythm-runner', category: 'game', categoryLabel: l('游戏', 'Game'), accent: '#f472b6',
  title: l('节奏跑酷 · 琴键疾跑', 'Rhythm runner · Key Dash'),
  summary: l('策划定判定，美术和音乐并行，程序做出跟拍奔跑，再由测试和验收两道把关。', 'Design sets the judging, art and music work in parallel, code makes the beat-driven run, and testing and review check it twice.'),
  description: l('角色在巨型钢琴键上自动奔跑，WebAudio 实时合成 120 BPM 的鼓组；障碍与拍点对齐，跳过黑键缺口、滑铲穿过音符横梁，判定 Perfect / Good / Miss。', 'A runner races across giant piano keys while WebAudio synthesizes a 120 BPM drum kit live; obstacles land on the beat — jump black-key gaps, slide under note bars — judged Perfect / Good / Miss.'),
  pattern: l('节拍与判定 → 画面 / 音乐并行 → 可玩关卡 → 节奏测试 → 验收', 'Beats and judging → visuals / music in parallel → playable level → rhythm testing → review'),
  brief: l('做一款节奏跑酷试玩关《琴键疾跑》：角色在一排巨型钢琴键上自动向右奔跑，WebAudio 实时合成 120 BPM 的鼓组和简单旋律；障碍与拍点对齐——黑键缺口按空格/↑跳过，低悬的音符横梁按↓滑铲；每次操作判定 Perfect / Good / Miss，累计连击与得分，45 秒结束后结算，可重来。canvas 自绘，交付单文件 HTML。',
    'Make a rhythm-runner level, “Key Dash”: a runner races right across a row of giant piano keys while WebAudio synthesizes a 120 BPM drum kit and a simple melody live; obstacles land on the beat — jump black-key gaps with Space/↑ and slide under low note bars with ↓; every action is judged Perfect / Good / Miss with combo and score, and after 45 seconds the results show, with a restart. Draw on a canvas and deliver one HTML file.'),
  nodes: [
    n('design', l('节拍与判定', 'Beats and judging'), 'general', 0, 0,
      l('定义：120 BPM，45 秒共 90 拍；障碍类型（缺口要跳、横梁要滑）与它们对应的拍点规则；判定窗口（Perfect ±60 毫秒、Good ±120 毫秒，其余 Miss）、连击与计分公式；奔跑速度与“障碍到达角色的时刻 = 拍点时刻”的换算；开始、结算与重来流程。不超过 350 字。',
        'Define: 120 BPM, 90 beats in 45 seconds; obstacle types (gaps to jump, bars to slide under) and which beats they fall on; judgment windows (Perfect ±60 ms, Good ±120 ms, otherwise Miss), combo and scoring formulas; running speed and the conversion “an obstacle reaches the runner exactly on its beat”; start, results and restart. At most 250 words.'),
      l('节拍与判定规格', 'Beat and judgment spec'), l('判定窗口与计分公式可以直接实现', 'Judgment windows and scoring can be implemented as written')),
    n('art', l('琴键画面', 'Piano-key visuals'), 'materials', 1, 0,
      l('给出画面方案：琴键地面的画法（白键与黑键交替，按拍点微微下沉），黑键缺口与音符横梁的样式，奔跑角色的简笔造型与跑、跳、滑三种姿态，按节拍脉动的背景，判定文字（Perfect / Good / Miss）与连击数的动画，配色（十六进制）。写成可照做的绘制步骤，不超过 300 字。',
        'Give the look: the piano-key floor (white and black keys alternating, dipping slightly on the beat), the black-key gaps and note bars, a simple runner figure with run, jump and slide poses, a background that pulses with the beat, animation for the judgment words (Perfect / Good / Miss) and the combo count, and a palette (hex). Write drawing steps that can be followed directly, at most 200 words.'),
      l('画面与绘制步骤', 'Look and drawing steps'), l('只用 canvas 就能画出来', 'Everything can be drawn on a canvas')),
    n('music', l('音乐与谱面', 'Music and chart'), 'materials', 1, 1,
      code('写出 JavaScript：startMusic() 在第一次用户操作时创建 AudioContext，用它的时间轴做前瞻调度（lookahead scheduler），合成底鼓、军鼓、踩镲（振荡器与噪声）和一条简单的钢琴旋律；songTime() 在开始前返回 0，开始后返回从第一拍起经过的秒数（以 AudioContext.currentTime 为准，不小于 0）；导出 chart 数组，列出 90 拍里哪些拍放缺口、哪些拍放横梁（前 8 拍空出来热身，障碍之间至少隔 2 拍）。第一次用户操作后才创建 AudioContext，不加载音频文件，不超过 35 行。',
        'Write JavaScript: startMusic() creates the AudioContext on the first user action and runs a lookahead scheduler on its clock that synthesizes kick, snare and hi-hat (oscillators and noise) and a simple piano melody; songTime() returns 0 before the start and afterwards the seconds since the first beat (from AudioContext.currentTime, never below 0); export a chart array listing which of the 90 beats hold a gap and which hold a bar (leave the first 8 beats empty to warm up, and at least 2 beats between obstacles). Create the AudioContext only after the first user action and load no audio files, at most 35 lines.'),
      l('合成音乐与谱面代码', 'Synthesized music and chart code'), l('以 AudioContext.currentTime 为主时钟；谱面符合间隔规则', 'AudioContext.currentTime is the master clock; the chart follows the spacing rules')),
    n('build', l('可玩关卡', 'Playable level'), 'frontend', 2, 0,
      build('合成完整游戏：开始画面，按下开始键后启动音乐，障碍位置由谱面和 songTime() 计算（不能用累计帧数），空格/↑ 跳、↓ 滑，按判定窗口给出 Perfect / Good / Miss，连击与得分，45 秒后结算并可重来。直接复用上游的音乐与谱面代码，不要改写。',
        'Assemble the complete game: a start screen; music starts on the start key; obstacle positions are computed from the chart and songTime() (not accumulated frames); Space/↑ jumps and ↓ slides; Perfect / Good / Miss by the judgment windows, with combo and score; results after 45 seconds and a restart. Reuse the upstream music and chart code exactly as delivered.'),
      l('节奏跑酷 HTML', 'Rhythm runner HTML'), l('障碍与拍点对齐，判定、连击和结算真实生效', 'Obstacles land on the beat; judging, combo and results work'), 'html'),
    n('test', l('节奏测试', 'Rhythm testing'), 'review', 3, 0,
      l('专门检查节奏同步：游戏是否以 AudioContext.currentTime 为主时钟、障碍到达角色的时刻是否等于拍点时刻、判定窗口是否为 ±60/±120 毫秒、暂停或切到后台后是否会错拍、重来时是否重置时钟与谱面。逐条给出依据（引用代码），只能阅读源码时写明“未实际运行”，不超过 350 字。',
        'Check rhythm sync specifically: whether the game uses AudioContext.currentTime as the master clock, whether obstacles reach the runner exactly on their beats, whether the windows are ±60/±120 ms, whether pausing or switching tabs desynchronizes it, and whether restart resets the clock and chart. Give evidence for each point (quote code); if you can only read the source, say “not actually run”; at most 250 words.'),
      l('节奏同步测试记录', 'Rhythm sync test record'), l('每个结论都有代码依据', 'Every finding cites code')),
    n('review', REVIEW_TITLE, 'review', 4, 0,
      l('综合节拍规格、节奏测试记录和 HTML 源码做最终验收：列出确认通过的功能、仍未解决的缺陷（含测试记录里的问题是否成立）、未验证项，给出能否作为试玩关交付的结论。只能阅读源码时写明“未实际运行”，不超过 350 字。',
        'Make the final review from the beat spec, the rhythm test record and the HTML source: list confirmed features, open defects (including whether the test record’s issues hold), unverified items, and conclude whether it can ship as a playable level. If you can only read the source, say “not actually run”; at most 250 words.'),
      l('验收结论', 'Review verdict'), l('结论与证据一致，不把静态检查说成实测', 'The verdict matches the evidence; static review is never called a playtest')),
  ],
  edges: [e('design', 'art', '画面元素', 'Visual elements'), e('design', 'music', '节拍与谱面规则', 'Beat and chart rules'), e('design', 'build', '判定与流程', 'Judging and flow'),
    e('art', 'build', '画面方案', 'Look'), e('music', 'build', '音乐与谱面代码', 'Music and chart code'), e('design', 'test', '判定标准', 'Judging rules'), e('build', 'test', '游戏源码', 'Game source'),
    e('design', 'review', '验收标准', 'Acceptance criteria'), e('build', 'review', '游戏源码', 'Game source'), e('test', 'review', '测试记录', 'Test record')],
  artifacts: [l('跟着鼓点奔跑的节奏关卡', 'A rhythm level that runs on the beat'), l('合成音乐与谱面', 'Synthesized music and chart'), l('节奏测试与验收结论', 'Rhythm test and review verdict')],
  limitations: limits('一首固定曲目、一段 45 秒关卡，判定只针对键盘。', 'One fixed track and one 45-second level, judged for the keyboard only.'),
};

/** Keyed by production case id. The knowledge-base case is not here: it ran on 2026-09-04 with
 * its own canvas, and its record lives in production-runs/knowledge-base.ts. */
export const PRODUCTION_WORKFLOWS: Readonly<Record<string, OfficialWorkflow>> = Object.fromEntries(
  [PIXEL, CONFIGURATOR, PAPER, AD, PORT, GLIDER, PARTY, RHYTHM].map(item => [item.id, item]));
