import { useMemo, useState, type ReactNode } from 'react';
import type { AdvancedDemoProps } from './types';
import {
  ROAD_NODES, ROADS, DELIVERIES, planDispatch, SKUS, WAREHOUSES, initialRetail, retailAction, retailTotals, availableStock,
  FACTORY_ORDERS, INITIAL_MATERIALS, MACHINES, BOM, scheduleFactory, INITIAL_GRID, simulateGrid,
  type RetailAction, type OrderStatus, type Material, type GridScenario,
} from './operationsEngine';
import './advanced-operations.css';

type Locale = AdvancedDemoProps['locale'];
const choose = (locale: Locale, zh: string, en: string) => locale === 'zh' ? zh : en;
const number = (value: number, digits = 0) => value.toLocaleString('en-US', { maximumFractionDigits: digits, minimumFractionDigits: digits });
const money = (value: number) => `¥${number(value, 2)}`;
function Header({ code, title, subtitle, reset, locale }: { code: string; title: string; subtitle: string; reset: () => void; locale: Locale }) {
  return <header className="op-header"><div><span className="op-eyebrow">{code} <i /> {choose(locale, '本地情景系统', 'LOCAL SCENARIO SYSTEM')}</span><h3>{title}</h3><p>{subtitle}</p></div><button className="op-quiet" onClick={reset}>{choose(locale, '重置系统', 'Reset system')} ↺</button></header>;
}
function Tabs({ items, value, set }: { items: Array<[string, string]>; value: string; set: (value: string) => void }) {
  return <div className="op-tabs" role="tablist">{items.map(([id, label]) => <button key={id} role="tab" aria-selected={id === value} onClick={() => set(id)}>{label}</button>)}</div>;
}
function Metrics({ items }: { items: Array<[string, string, string?]> }) { return <div className="op-metrics">{items.map(([label, value, note]) => <div key={label}><span>{label}</span><strong>{value}</strong>{note && <small>{note}</small>}</div>)}</div>; }
function Panel({ title, children, className = '' }: { title: string; children: ReactNode; className?: string }) { return <section className={`op-panel ${className}`}><h4>{title}</h4>{children}</section>; }
function Notice({ children, alert = false }: { children: ReactNode; alert?: boolean }) { return <p className={`op-notice${alert ? ' is-alert' : ''}`} role={alert ? 'alert' : undefined}>{children}</p>; }
function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="op-field"><span>{label}</span>{children}</label>; }

function DispatchDemo({ locale }: { locale: Locale }) {
  const t = (zh: string, en: string) => choose(locale, zh, en);
  const [tab, setTab] = useState('network'); const [traffic, setTraffic] = useState('normal'); const [tight, setTight] = useState(false);
  const [strategy, setStrategy] = useState<'deadline' | 'nearest'>('deadline'); const [selected, setSelected] = useState('EV-01'); const [progress, setProgress] = useState<Record<string, number>>({});
  const blocked = useMemo(() => new Set(ROADS.filter(r => traffic === 'bridge' ? (r.from === 'B' && r.to === 'C') || (r.from === 'C' && r.to === 'B') : traffic === 'isolate' ? r.from === 'E' || r.to === 'E' : false).map(r => r.id)), [traffic]);
  const orders = useMemo(() => DELIVERIES.map(o => ({ ...o, deadline: Math.round(o.deadline * (tight ? 0.65 : 1)) })), [tight]);
  const plan = useMemo(() => planDispatch(orders, blocked, strategy), [orders, blocked, strategy]);
  const baseline = useMemo(() => planDispatch(orders, new Set(), strategy), [orders, strategy]);
  const other = useMemo(() => planDispatch(orders, blocked, strategy === 'deadline' ? 'nearest' : 'deadline'), [orders, blocked, strategy]);
  const truck = plan.trucks.find(p => p.truck.id === selected) ?? plan.trucks[0];
  const reset = () => { setTraffic('normal'); setTight(false); setStrategy('deadline'); setSelected('EV-01'); setProgress({}); setTab('network'); };
  const colors = ['#6fddbb', '#89b4f5', '#eab56e', '#c7a1f0'];
  const status = (id: string) => [t('待派车', 'Planned'), t('运输中', 'En route'), t('已完成', 'Completed')][progress[id] ?? 0];
  return <div className="advanced-ops op-dispatch">
    <Header code="NEXUS / 04" title={t('城市配送控制塔', 'Urban dispatch control')} subtitle={t('08:00 仓库发车基准 · 单程多站路线 · 容量与时窗联动', '08:00 departure baseline · One-way multi-stop routes · Capacity and time windows')} reset={reset} locale={locale} />
    <div className="op-control-row">
      <Field label={t('道路情景', 'Road scenario')}><select value={traffic} onChange={e => { setTraffic(e.target.value); setProgress({}); }}><option value="normal">{t('全路网开放', 'Network open')}</option><option value="bridge">{t('B ↔ C 桥梁封闭', 'B ↔ C bridge closure')}</option><option value="isolate">{t('E 区域完全隔离', 'Destination E isolated')}</option></select></Field>
      <Field label={t('分配策略', 'Assignment policy')}><select value={strategy} onChange={e => { setStrategy(e.target.value as typeof strategy); setProgress({}); }}><option value="deadline">{t('到期优先', 'Deadline first')}</option><option value="nearest">{t('近点优先', 'Nearest first')}</option></select></Field>
      <label className="op-check"><input type="checkbox" checked={tight} onChange={e => { setTight(e.target.checked); setProgress({}); }} />{t('时窗收紧 35%', 'Tighten windows 35%')}</label>
    </div>
    <Metrics items={[[t('准点交付', 'On-time deliveries'), `${plan.onTime}/${plan.total}`, `${number(plan.onTime / plan.total * 100)}%`], [t('路线成本', 'Route cost'), money(plan.cost), `${number(plan.cost - baseline.cost, 1)} ${t('较畅通基线', 'vs open baseline')}`], [t('计划里程', 'Planned distance'), `${plan.km} km`, 'Dijkstra / directed'], [t('未分配', 'Unassigned'), String(plan.unassigned.length), t('硬性容量 / 可达性约束', 'Hard capacity / reachability')]]} />
    <Tabs value={tab} set={setTab} items={[[ 'network', t('路网与派车', 'Network & dispatch') ], ['manifest', t('配送明细', 'Delivery manifest')], ['compare', t('策略对比', 'Policy comparison')]]} />
    {plan.unassigned.length > 0 && <Notice alert>{t('无法分配：', 'Unassigned: ')}{plan.unassigned.map(o => o.id).join(' · ')} {t('（无满足同仓、载重和可达性的车辆）', '(no depot-, capacity- and reachability-feasible truck)')}</Notice>}
    {tab === 'network' && <div className="op-split"><Panel title={t('方向路网 / 选择车辆查看实际路径', 'DIRECTED NETWORK / SELECT A VEHICLE')}>
      <div className="op-vehicle-pills">{plan.trucks.map((p, i) => <button key={p.truck.id} aria-pressed={selected === p.truck.id} onClick={() => setSelected(p.truck.id)} style={{ '--vehicle': colors[i] } as React.CSSProperties}>{p.truck.id}<small>{p.load}/{p.truck.capacity} kg</small></button>)}</div>
      <svg className="op-map" viewBox="0 0 600 400" role="img" aria-label={t('配送有向路网与选中车辆路径', 'Directed delivery network and selected truck route')}>
        <defs><pattern id="op-map-grid" width="30" height="30" patternUnits="userSpaceOnUse"><path d="M 30 0 L 0 0 0 30" fill="none" stroke="currentColor" opacity=".08" /></pattern><marker id="op-road-arrow" viewBox="0 0 10 10" refX="10" refY="5" markerWidth="5" markerHeight="5" orient="auto"><path d="M0,0 L10,5 L0,10 Z" fill="currentColor" /></marker></defs>
        <rect width="600" height="400" fill="url(#op-map-grid)" />
        {ROADS.map(r => { const a = ROAD_NODES.find(n => n.id === r.from)!; const b = ROAD_NODES.find(n => n.id === r.to)!; return <path key={r.id} d={`M${a.x} ${a.y} Q${(a.x + b.x) / 2 + (a.y - b.y) * .07} ${(a.y + b.y) / 2 + (b.x - a.x) * .07} ${b.x} ${b.y}`} fill="none" stroke={blocked.has(r.id) ? '#fa7972' : '#314f4c'} strokeWidth={blocked.has(r.id) ? 2.5 : 1.5} strokeDasharray={blocked.has(r.id) ? '5 5' : undefined} markerEnd="url(#op-road-arrow)" />; })}
        {truck.stops.flatMap((stop, i) => stop.path.map((r, j) => { const a = ROAD_NODES.find(n => n.id === r.from)!; const b = ROAD_NODES.find(n => n.id === r.to)!; return <path key={`${i}-${j}`} d={`M${a.x} ${a.y} L${b.x} ${b.y}`} fill="none" stroke={colors[plan.trucks.indexOf(truck)]} strokeWidth="4" opacity=".8" />; }))}
        {ROAD_NODES.map(n => <g key={n.id}><circle cx={n.x} cy={n.y} r={n.depot ? 17 : 12} fill={n.depot ? '#284b40' : '#172c2b'} stroke={n.id === 'E' && traffic === 'isolate' ? '#fa7972' : '#94c9b6'} strokeWidth="2" /><text x={n.x} y={n.y + 4} fill="#e1f5ed" textAnchor="middle" fontSize={n.depot ? 9 : 11}>{n.id}</text></g>)}
      </svg><p className="op-footnote">{t('两方向行驶时间不同；红色虚线为关闭道路。车辆累计整趟装载，不中途回仓。', 'Travel time differs by direction; red dashes mark closures. Payload is total trip load, without depot returns.')}</p>
    </Panel><Panel title={`${truck.truck.id} / ${status(truck.truck.id)}`}>
      <div className="op-route-summary"><strong>{truck.load} <small>/ {truck.truck.capacity} kg</small></strong><span>{money(truck.cost)}</span></div>
      <progress aria-label={t('车辆装载比例', 'Truck payload ratio')} value={truck.load} max={truck.truck.capacity} />
      <ol className="op-route-stops">{truck.stops.map((s, i) => <li key={s.delivery.id}><span>{i + 1}</span><div><strong>{s.delivery.id} → {s.delivery.destination}</strong><small>{s.delivery.kg} kg · {t('到达', 'Arrival')} +{s.arrival} min</small><small className={s.late ? 'op-negative' : 'op-positive'}>{s.late ? t(`迟到 ${s.late} 分钟`, `${s.late} min late`) : t('在时窗内', 'Within window')}</small></div></li>)}</ol>
      <button className="op-primary" disabled={!truck.stops.length || (progress[selected] ?? 0) >= 2} onClick={() => setProgress(p => ({ ...p, [selected]: Math.min(2, (p[selected] ?? 0) + 1) }))}>{(progress[selected] ?? 0) === 0 ? t('模拟派车', 'Simulate dispatch') : (progress[selected] ?? 0) === 1 ? t('标记路线完成', 'Complete route') : t('路线已完成', 'Route completed')}</button>
      <p className="op-footnote">{t('仅推进本地状态。道路、策略或时窗变更后，旧派车进度自动清空。', 'Local progress only. Road, policy or window changes clear prior dispatch progress.')}</p>
    </Panel></div>}
    {tab === 'manifest' && <Panel title={t('每一站的路径与时窗', 'PER-STOP ROUTE AND TIME WINDOWS')}><div className="op-table-wrap"><table><thead><tr>{[t('车辆 / 订单', 'Truck / order'), t('路径', 'Route'), t('重量', 'Weight'), t('时窗', 'Window'), t('到达', 'Arrival'), t('状态', 'Status')].map(s => <th key={s}>{s}</th>)}</tr></thead><tbody>{plan.trucks.flatMap(p => p.stops.map(s => <tr key={s.delivery.id}><td>{p.truck.id}<small>{s.delivery.id}</small></td><td>{[s.path[0]?.from ?? s.delivery.destination, ...s.path.map(r => r.to)].join(' → ')}</td><td>{s.delivery.kg} kg</td><td>{s.delivery.ready}–{s.delivery.deadline} min</td><td className={s.late ? 'op-negative' : ''}>+{s.arrival} min</td><td>{status(p.truck.id)}</td></tr>))}</tbody></table></div></Panel>}
    {tab === 'compare' && <div className="op-three">{[[t('当前情景 / 当前策略', 'Current scenario / policy'), plan], [t('畅通路网 / 当前策略', 'Open network / current policy'), baseline], [t('当前情景 / 另一策略', 'Current scenario / alternate policy'), other]].map(([label, result]) => { const p = result as typeof plan; return <Panel key={String(label)} title={String(label)}><div className="op-large">{money(p.cost)}</div><dl className="op-kv"><dt>{t('准点', 'On time')}</dt><dd>{p.onTime}/{p.total}</dd><dt>{t('里程', 'Distance')}</dt><dd>{p.km} km</dd><dt>{t('未分配', 'Unassigned')}</dt><dd>{p.unassigned.length}</dd></dl><progress value={p.onTime} max={p.total} aria-label={String(label)} /></Panel>; })}</div>}
    <Notice>{t('固定合成数据 · 最短时间路径 + 贪心分配，无全局最优保证；成本不含回仓，不连接 GPS 或真实调度。', 'Synthetic data · Shortest-time paths + greedy assignment, without global optimality; costs exclude depot return. No GPS or real dispatch connection.')}</Notice>
  </div>;
}

const statusLabels: Record<OrderStatus, [string, string]> = { draft: ['草稿', 'Draft'], reserved: ['已预留', 'Reserved'], approved: ['已审批', 'Approved'], shipped: ['已发货', 'Shipped'], returned: ['已退货', 'Returned'], refunded: ['已退款', 'Refunded'], cancelled: ['已取消', 'Cancelled'] };
const actionLabels: Partial<Record<OrderStatus, [string, string]>> = { reserved: ['预留库存', 'Reserve stock'], approved: ['审批订单', 'Approve order'], shipped: ['确认发货', 'Ship order'], returned: ['整单退货入库', 'Return & restock'], refunded: ['确认退款', 'Issue refund'], cancelled: ['取消订单', 'Cancel order'] };
const nextActions: Record<OrderStatus, OrderStatus[]> = { draft: ['reserved', 'cancelled'], reserved: ['approved', 'cancelled'], approved: ['shipped', 'cancelled'], shipped: ['returned'], returned: ['refunded'], refunded: [], cancelled: [] };
function CommerceDemo({ locale }: { locale: Locale }) {
  const t = (zh: string, en: string) => choose(locale, zh, en); const [state, setState] = useState(initialRetail); const [tab, setTab] = useState('orders');
  const [selected, setSelected] = useState('RT-1001'); const [filter, setFilter] = useState('all'); const [error, setError] = useState('');
  const [basket, setBasket] = useState<Record<string, number>>({ LAMP: 1, MUG: 1, BAG: 0, HUB: 0 }); const [warehouse, setWarehouse] = useState('SH'); const [channel, setChannel] = useState('WEB'); const [coupon, setCoupon] = useState(true);
  const [from, setFrom] = useState('HZ'); const [to, setTo] = useState('SH'); const [sku, setSku] = useState('BAG'); const [quantity, setQuantity] = useState(3);
  const errors: Record<string, string> = { INVALID_ORDER: t('购物篮需要至少一项，数量须为正整数。', 'Add at least one item with a positive integer quantity.'), INSUFFICIENT_STOCK: t('可用库存不足，整单操作未执行。请调拨库存后重试。', 'Insufficient available stock. No part of the order changed; transfer stock and retry.'), TRANSFER_UNAVAILABLE: t('调拨失败：请选择不同仓库，且数量不能超过未预留库存。', 'Transfer rejected: use different warehouses and no more than free stock.'), INVALID_TRANSITION: t('当前状态不能执行此操作。', 'This action is invalid for the current state.') };
  const apply = (action: RetailAction) => { const result = retailAction(state, action); setError(result.error ? errors[result.error] ?? result.error : ''); setState(result.state); return !result.error; };
  const reset = () => { setState(initialRetail()); setTab('orders'); setSelected('RT-1001'); setFilter('all'); setError(''); setBasket({ LAMP: 1, MUG: 1, BAG: 0, HUB: 0 }); setWarehouse('SH'); setChannel('WEB'); setCoupon(true); setFrom('HZ'); setTo('SH'); setSku('BAG'); setQuantity(3); };
  const order = state.orders.find(o => o.id === selected) ?? state.orders[0]; const totals = retailTotals(order);
  const lines = SKUS.filter(s => basket[s.id] > 0).map(s => ({ sku: s.id, quantity: basket[s.id] })); const quote = retailTotals({ lines, coupon });
  const gross = state.orders.filter(o => ['shipped', 'returned', 'refunded'].includes(o.status)).reduce((s, o) => s + retailTotals(o).total, 0);
  const refunds = state.orders.filter(o => o.status === 'refunded').reduce((s, o) => s + retailTotals(o).total, 0);
  const margin = state.orders.filter(o => o.status === 'shipped').reduce((s, o) => s + retailTotals(o).margin, 0);
  const reserved = state.orders.filter(o => ['reserved', 'approved'].includes(o.status)).flatMap(o => o.lines).reduce((s, l) => s + l.quantity, 0);
  const breakdown = (values: ReturnType<typeof retailTotals>) => <dl className="op-kv"><dt>{t('商品原价', 'Goods subtotal')}</dt><dd>{money(values.subtotal)}</dd><dt>{t('优惠', 'Discount')}</dt><dd>−{money(values.discount)}</dd><dt>{t('示例税费 6%', 'Sample goods tax 6%')}</dt><dd>{money(values.tax)}</dd><dt>{t('运费', 'Shipping')}</dt><dd>{money(values.shipping)}</dd><dt><b>{t('应付', 'Total')}</b></dt><dd><b>{money(values.total)}</b></dd><dt>{t('预计毛利（不含税）', 'Expected margin (excl. tax)')}</dt><dd>{money(values.margin)}</dd></dl>;
  return <div className="advanced-ops op-commerce"><Header code="MERIDIAN / COMMERCE" title={t('订单、库存与资金，同一张账', 'Orders, stock and money. One ledger.')} subtitle={t('3 仓 · 4 SKU · 3 渠道 · 原子预留与完整退货流程', '3 warehouses · 4 SKUs · 3 channels · Atomic reservation and returns')} reset={reset} locale={locale} />
    <Metrics items={[[t('订单总数', 'Orders'), String(state.orders.length)], [t('已预留商品', 'Reserved units'), String(reserved)], [t('净收款（含税）', 'Net receipts (incl. tax)'), money(gross - refunds)], [t('已发货留存毛利', 'Retained shipped margin'), money(margin)]]} />
    <Tabs value={tab} set={v => { setTab(v); setError(''); }} items={[[ 'orders', t('订单履约', 'Fulfillment') ], ['basket', t('创建购物篮', 'New basket')], ['inventory', t('库存与调拨', 'Inventory & transfer')], ['finance', t('财务与事件', 'Finance & events')]]} />
    {error && <Notice alert>{error}</Notice>}
    {tab === 'orders' && <div className="op-split"><Panel title={t('订单队列', 'ORDER QUEUE')}><Field label={t('状态筛选', 'Status filter')}><select value={filter} onChange={e => setFilter(e.target.value)}><option value="all">{t('全部状态', 'All states')}</option>{Object.entries(statusLabels).map(([id, labels]) => <option key={id} value={id}>{t(...labels)}</option>)}</select></Field><div className="op-order-list">{state.orders.filter(o => filter === 'all' || o.status === filter).map(o => <button key={o.id} className={o.id === selected ? 'selected' : ''} onClick={() => setSelected(o.id)}><span><strong>{o.id}</strong><small>{o.channel} · {o.warehouse} · {o.lines.reduce((s, l) => s + l.quantity, 0)} {t('件', 'units')}</small></span><span><b>{money(retailTotals(o).total)}</b><small>{t(...statusLabels[o.status])}</small></span></button>)}{!state.orders.some(o => filter === 'all' || o.status === filter) && <Notice>{t('此状态暂无订单。', 'No orders in this state.')}</Notice>}</div></Panel>
      <Panel title={`${order.id} / ${t(...statusLabels[order.status])}`}><div className="op-state-track">{(['draft', 'reserved', 'approved', 'shipped', 'returned', 'refunded'] as OrderStatus[]).map(s => <span key={s} className={order.status === s ? 'active' : ''}>{t(...statusLabels[s])}</span>)}</div>
        {order.lines.map(line => <div className="op-line-item" key={line.sku}><span>{SKUS.find(s => s.id === line.sku)?.[locale]} <small>{line.sku} ×{line.quantity}</small></span><b>{money((SKUS.find(s => s.id === line.sku)?.price ?? 0) * line.quantity)}</b></div>)}{breakdown(totals)}
        <div className="op-actions">{nextActions[order.status].map(action => <button className={action === 'cancelled' ? 'op-quiet' : 'op-primary'} key={action} onClick={() => apply({ type: 'transition', id: order.id, to: action })}>{t(...actionLabels[action]!)}</button>)}</div><p className="op-footnote">{t('退款仅在整单退货入库后开放；再次点击相同转换会被状态机拒绝。', 'Refunds require a completed whole-order return. The state machine rejects repeated transitions.')}</p>
      </Panel></div>}
    {tab === 'basket' && <div className="op-split"><Panel title={t('多 SKU 购物篮', 'MULTI-SKU BASKET')}><div className="op-control-row"><Field label={t('发货仓', 'Fulfillment warehouse')}><select value={warehouse} onChange={e => setWarehouse(e.target.value)}>{WAREHOUSES.map(w => <option key={w}>{w}</option>)}</select></Field><Field label={t('销售渠道', 'Sales channel')}><select value={channel} onChange={e => setChannel(e.target.value)}>{['WEB', 'STORE', 'MARKET'].map(c => <option key={c}>{c}</option>)}</select></Field></div>{SKUS.map(s => <div className="op-product" key={s.id}><span className="op-product-mark">{s.id.slice(0, 1)}</span><div><strong>{s[locale]}</strong><small>{money(s.price)} · {t('可用', 'Available')} {availableStock(state, warehouse, s.id)}</small></div><Field label={`${s[locale]} ${t('数量', 'quantity')}`}><input type="number" min="0" max="30" value={basket[s.id]} onChange={e => setBasket(b => ({ ...b, [s.id]: Math.min(30, Math.max(0, Math.trunc(Number(e.target.value) || 0))) }))} /></Field></div>)}</Panel><Panel title={t('价格与创建', 'PRICING AND CREATION')}><label className="op-check"><input type="checkbox" checked={coupon} onChange={e => setCoupon(e.target.checked)} />{t('满 ¥500 减 10%', '10% off goods above ¥500')}</label>{breakdown(quote)}<button className="op-primary" onClick={() => { const id = `RT-${state.sequence}`; if (apply({ type: 'create', warehouse, channel, lines, coupon })) { setSelected(id); setFilter('all'); setTab('orders'); } }}>{t('创建订单草稿', 'Create order draft')}</button><Notice>{t('草稿不占库存，预留时统一校验。净商品额满 ¥600 免运费；规则为虚构商业样例。', 'Drafts do not reserve inventory. Reservation validates the complete order. Net goods above ¥600 ship free; these are fictional commerce rules.')}</Notice></Panel></div>}
    {tab === 'inventory' && <div className="op-split"><Panel title={t('三仓库存 / 可用 ÷ 现货', 'WAREHOUSE STOCK / AVAILABLE ÷ ON-HAND')}><div className="op-table-wrap"><table><thead><tr><th>SKU</th>{WAREHOUSES.map(w => <th key={w}>{w}</th>)}</tr></thead><tbody>{SKUS.map(s => <tr key={s.id}><td>{s[locale]}<small>{s.id}</small></td>{WAREHOUSES.map(w => <td key={w} className={availableStock(state, w, s.id) < 5 ? 'op-negative' : ''}><b>{availableStock(state, w, s.id)}</b> / {state.stock[w][s.id]}</td>)}</tr>)}</tbody></table></div><p className="op-footnote">{t('可用库存扣除已预留和已审批订单；调拨不能挪用这些商品。', 'Available inventory excludes reserved and approved orders; transfers cannot consume those goods.')}</p></Panel><Panel title={t('跨仓调拨', 'WAREHOUSE TRANSFER')}><div className="op-control-row"><Field label={t('来源仓', 'From warehouse')}><select value={from} onChange={e => setFrom(e.target.value)}>{WAREHOUSES.map(w => <option key={w}>{w}</option>)}</select></Field><Field label={t('目标仓', 'To warehouse')}><select value={to} onChange={e => setTo(e.target.value)}>{WAREHOUSES.map(w => <option key={w}>{w}</option>)}</select></Field></div><Field label={t('调拨 SKU', 'Transfer SKU')}><select value={sku} onChange={e => setSku(e.target.value)}>{SKUS.map(s => <option key={s.id} value={s.id}>{s[locale]}</option>)}</select></Field><Field label={t('调拨数量', 'Transfer quantity')}><input type="number" min="1" max="100" value={quantity} onChange={e => setQuantity(Math.max(1, Math.trunc(Number(e.target.value) || 1)))} /></Field><p>{t('来源仓可调拨', 'Available to transfer')}: <strong>{availableStock(state, from, sku)}</strong></p><button className="op-primary" onClick={() => apply({ type: 'transfer', from, to, sku, quantity })}>{t('执行本地调拨', 'Transfer locally')}</button></Panel></div>}
    {tab === 'finance' && <div className="op-split"><Panel title={t('交易对账 / 人民币示例', 'RECONCILIATION / SAMPLE CNY')}><dl className="op-kv"><dt>{t('累计发货收款', 'Gross shipment receipts')}</dt><dd>{money(gross)}</dd><dt>{t('累计退款', 'Refunds issued')}</dt><dd>{money(refunds)}</dd><dt>{t('净收款', 'Net receipts')}</dt><dd>{money(gross - refunds)}</dd><dt>{t('退货待退款负债', 'Returned, pending refund')}</dt><dd>{money(state.orders.filter(o => o.status === 'returned').reduce((s, o) => s + retailTotals(o).total, 0))}</dd><dt>{t('仍在客户侧的订单毛利', 'Margin on retained shipped orders')}</dt><dd>{money(margin)}</dd></dl><Notice>{t('本地整单模拟；税率为演示常量，退款返还完整账单金额。没有支付或税务服务调用。', 'Local whole-order simulation. Tax is an illustrative constant; refunds return the full invoice. No payment or tax-service calls.')}</Notice></Panel><Panel title={t('事件轨迹 / 新事件在前', 'EVENT TRAIL / NEWEST FIRST')}><ol className="op-event-log">{state.log.map((item, i) => <li key={`${i}-${item}`}><span>{String(state.log.length - i).padStart(2, '0')}</span>{item}</li>)}</ol></Panel></div>}
  </div>;
}

function FactoryDemo({ locale }: { locale: Locale }) {
  const t = (zh: string, en: string) => choose(locale, zh, en); const [tab, setTab] = useState('schedule'); const [materials, setMaterials] = useState({ ...INITIAL_MATERIALS }); const [shift, setShift] = useState(8); const [broken, setBroken] = useState(false);
  const [selected, setSelected] = useState('MO-201'); const [material, setMaterial] = useState<Material>('board'); const [amount, setAmount] = useState(24); const [quality, setQuality] = useState<Record<string, { result: 'pass' | 'fail'; released: boolean }>>({});
  const materialName = (m: Material) => ({ alloy: t('铝合金', 'Alloy'), board: t('控制板', 'Control board'), fastener: t('紧固件', 'Fastener') })[m];
  const outages = useMemo(() => broken ? [{ machine: 'CUT-1', start: 3, end: 28 }] : [], [broken]);
  const plan = useMemo(() => scheduleFactory(materials, shift, outages), [materials, shift, outages]); const baseline = useMemo(() => scheduleFactory(materials, shift), [materials, shift]);
  const reset = () => { setMaterials({ ...INITIAL_MATERIALS }); setShift(8); setBroken(false); setTab('schedule'); setSelected('MO-201'); setQuality({}); setMaterial('board'); setAmount(24); };
  const maxHour = Math.max(72, Math.ceil(plan.makespan / 24) * 24); const stageNames: Record<string, string> = { CUT: t('切割', 'Cut'), ASSEMBLE: t('装配', 'Assemble'), TEST: t('测试', 'Test') };
  return <div className="advanced-ops op-factory"><Header code="FORGE / PRODUCTION" title={t('生产从约束开始', 'Production starts with constraints')} subtitle={t('BOM → 切割 → 双单元装配 → 测试 → 质量放行', 'BOM → Cut → Dual-cell assembly → Test → Quality release')} reset={reset} locale={locale} />
    <div className="op-control-row"><Field label={t('每日班次', 'Daily shift')}><select value={shift} onChange={e => { setShift(Number(e.target.value)); setQuality({}); }}>{[8, 10, 12].map(h => <option key={h} value={h}>{h} {t('小时 / 24小时', 'hours / 24h')}</option>)}</select></Field><label className="op-check"><input type="checkbox" checked={broken} onChange={e => { setBroken(e.target.checked); setQuality({}); }} />{t('CUT-1 停机：第3–28小时', 'CUT-1 outage: hour 3–28')}</label><span className="op-muted">{t('重排自动清空旧抽检与放行', 'Replanning invalidates prior quality and release')}</span></div>
    <Metrics items={[[t('可排生产单', 'Schedulable orders'), `${plan.completion.filter(o => o.end !== null).length}/${FACTORY_ORDERS.length}`], [t('完工跨度', 'Makespan'), `${number(plan.makespan, 1)} h`, `${number(plan.makespan - baseline.makespan, 1)}h ${t('较无停机', 'vs no outage')}`], [t('迟交 / 阻塞', 'Late / blocked'), `${plan.late} / ${plan.blocked.length}`], [t('质量隔离', 'Quarantined'), String(Object.values(quality).filter(q => q.result === 'fail').length), `${Object.values(quality).filter(q => q.released).length} ${t('已放行', 'released')}`]]} />
    <Tabs value={tab} set={setTab} items={[[ 'schedule', t('工序甘特图', 'Operation Gantt') ], ['materials', t('BOM 与物料', 'BOM & materials')], ['quality', t('质量与交付', 'Quality & delivery')]]} />
    {plan.blocked.length > 0 && <Notice alert>{t('阻塞订单不消耗物料，也不进入设备队列：', 'Blocked orders consume no material or machine capacity: ')}{plan.blocked.map(b => `${b.order.id} (${b.reason})`).join(' · ')}</Notice>}
    {tab === 'schedule' && <Panel title={t('设备时间线 / 每个方块都来自排程', 'MACHINE TIMELINE / EVERY BLOCK COMES FROM THE PLAN')}><div className="op-vehicle-pills">{FACTORY_ORDERS.map(o => <button key={o.id} aria-pressed={selected === o.id} onClick={() => setSelected(o.id)}>{o.id}<small>{o.product} ×{o.quantity}</small></button>)}</div><div className="op-gantt-scroll"><svg className="op-gantt" viewBox="0 0 920 320" role="img" aria-label={t('按设备分组的工序排程甘特图', 'Operation Gantt chart grouped by machine')}>
      {Array.from({ length: Math.ceil(maxHour / 24) }, (_, d) => <g key={d}><rect x={115 + (d * 24 + shift) / maxHour * 780} y="36" width={(24 - shift) / maxHour * 780} height="244" fill="#080d13" opacity=".65" /><text x={115 + d * 24 / maxHour * 780} y="24" fill="#a5a7ae" fontSize="11">D{d + 1} / {d * 24}h</text></g>)}
      {MACHINES.map((m, index) => <g key={m}><text x="5" y={72 + index * 58} fill="#c8cad0" fontSize="12">{m}</text><line x1="115" x2="895" y1={95 + index * 58} y2={95 + index * 58} stroke="#29303b" /></g>)}
      {outages.map(d => <rect key={d.machine} x={115 + d.start / maxHour * 780} y="46" width={(d.end - d.start) / maxHour * 780} height="42" fill="#ad4745" opacity=".4" />)}
      {plan.operations.map(op => { const active = op.order === selected; const x = 115 + op.start / maxHour * 780; const y = 47 + MACHINES.indexOf(op.machine as typeof MACHINES[number]) * 58; const width = Math.max(4, (op.end - op.start) / maxHour * 780); return <g key={op.id}><rect x={x} y={y} width={width} height="37" rx="4" fill={active ? '#e9bc64' : '#455367'} opacity={active ? 1 : .65} /><title>{`${op.order} ${stageNames[op.stage]} ${number(op.start, 1)}–${number(op.end, 1)}h`}</title>{width > 22 && <text x={x + width / 2} y={y + 23} fill={active ? '#25231d' : '#d2d6dd'} textAnchor="middle" fontSize="10">{op.order.slice(-3)}</text>}</g>; })}
    </svg></div><div className="op-selected-flow">{plan.operations.filter(op => op.order === selected).map(op => <div key={op.id}><small>{stageNames[op.stage]} / {op.machine}</small><strong>{number(op.start, 1)} → {number(op.end, 1)} h</strong></div>)}{!plan.operations.some(op => op.order === selected) && <Notice>{t('此订单被物料或班次约束阻塞。', 'This order is blocked by material or shift constraints.')}</Notice>}</div><p className="op-footnote">{t('深色背景为非班次；红色区域为停机。启发式按交期选单，不拆分工序，也不声称全局最短工期。', 'Dark bands are off-shift; red indicates downtime. A due-date priority heuristic keeps operations indivisible and does not claim minimum makespan.')}</p></Panel>}
    {tab === 'materials' && <div className="op-split"><Panel title={t('物料供给与排程后余量', 'MATERIAL SUPPLY AND REMAINING BALANCE')}><div className="op-table-wrap"><table><thead><tr><th>{t('物料', 'Material')}</th><th>{t('供给', 'Supply')}</th><th>{t('消耗', 'Consumed')}</th><th>{t('余量', 'Remaining')}</th></tr></thead><tbody>{(Object.keys(materials) as Material[]).map(m => <tr key={m}><td>{materialName(m)}</td><td>{materials[m]}</td><td>{materials[m] - plan.remaining[m]}</td><td>{plan.remaining[m]}</td></tr>)}</tbody></table></div><h4>{t('单位产品 BOM', 'BOM PER PRODUCT')}</h4><div className="op-table-wrap"><table><thead><tr><th>{t('产品', 'Product')}</th>{(Object.keys(materials) as Material[]).map(m => <th key={m}>{materialName(m)}</th>)}</tr></thead><tbody>{Object.entries(BOM).map(([product, bom]) => <tr key={product}><td>{product}</td>{Object.values(bom).map((q, i) => <td key={i}>{q}</td>)}</tr>)}</tbody></table></div></Panel><Panel title={t('物料到货与自动重排', 'REPLENISHMENT AND REPLANNING')}><Field label={t('补充物料', 'Replenish material')}><select value={material} onChange={e => setMaterial(e.target.value as Material)}>{(Object.keys(materials) as Material[]).map(m => <option key={m} value={m}>{materialName(m)}</option>)}</select></Field><Field label={t('到货数量', 'Receipt quantity')}><input type="number" min="1" max="500" value={amount} onChange={e => setAmount(Math.max(1, Math.min(500, Math.trunc(Number(e.target.value) || 1))))} /></Field><button className="op-primary" onClick={() => { setMaterials(m => ({ ...m, [material]: m[material] + amount })); setQuality({}); }}>{t('入库并重新排程', 'Receive and replan')}</button><Notice>{t('补料后重新从全部订单生成计划。旧质量结论与放行记录失效，需重新抽检。', 'Replenishment regenerates the complete plan. Prior quality and release decisions expire; sample checks must be repeated.')}</Notice></Panel></div>}
    {tab === 'quality' && <Panel title={t('交期承诺与质量门', 'DELIVERY COMMITMENTS AND QUALITY GATES')}><div className="op-table-wrap"><table><thead><tr>{[t('订单', 'Order'), t('完成 / 截止', 'Finish / due'), t('风险', 'Risk'), t('质检', 'Quality'), t('操作', 'Actions')].map(s => <th key={s}>{s}</th>)}</tr></thead><tbody>{plan.completion.map(({ order, end }) => { const q = quality[order.id]; return <tr key={order.id}><td>{order.id}<small>{order.product} ×{order.quantity}</small></td><td>{end === null ? '—' : number(end, 1)} / {order.due}h</td><td className={end === null || end > order.due || q?.result === 'fail' ? 'op-negative' : 'op-positive'}>{end === null ? t('物料阻塞', 'Material blocked') : q?.result === 'fail' ? t('整批隔离', 'Batch quarantined') : end > order.due ? t('预计迟交', 'At risk: late') : t('按期可达', 'Within due date')}</td><td>{q?.released ? t('已放行', 'Released') : q?.result === 'pass' ? t('抽检合格', 'Sample passed') : q?.result === 'fail' ? t('抽检不合格', 'Sample failed') : t('待抽检', 'Pending sample')}</td><td><div className="op-actions"><button disabled={end === null} onClick={() => setQuality(v => ({ ...v, [order.id]: { result: 'pass', released: false } }))}>{t('判合格', 'Pass')}</button><button disabled={end === null} onClick={() => setQuality(v => ({ ...v, [order.id]: { result: 'fail', released: false } }))}>{t('判不合格', 'Fail')}</button><button className="op-primary" disabled={end === null || q?.result !== 'pass' || q.released} onClick={() => setQuality(v => ({ ...v, [order.id]: { result: 'pass', released: true } }))}>{t('放行', 'Release')}</button></div></td></tr>; })}</tbody></table></div><Notice>{t('质检为人工模拟结果；不合格整批隔离，重新判定合格才可放行。未连接真实检测设备或 MES。', 'Quality results are manually simulated. Failure quarantines the batch; reinspection must pass before release. No live inspection equipment or MES connection.')}</Notice></Panel>}
  </div>;
}

function EnergyChart({ rows, selected, locale }: { rows: ReturnType<typeof simulateGrid>['hours']; selected: number; locale: Locale }) {
  const width = 710; const height = 210; const max = Math.max(60, ...rows.map(h => Math.max(h.load, h.pv, h.grid)));
  const point = (h: number, value: number) => `${45 + h / 23 * 650},${height - value / max * 165}`;
  return <svg className="op-energy-chart" viewBox={`0 0 ${width} 310`} role="img" aria-label={choose(locale, '24小时负荷、光伏、购电和储能曲线', '24-hour load, PV, import and storage curves')}>
    {[0, .5, 1].map(p => <g key={p}><line x1="45" x2="695" y1={height - p * 165} y2={height - p * 165} stroke="#2c3851" /><text x="5" y={height - p * 165 + 4} fill="#8e9eb8" fontSize="10">{number(max * p)}</text></g>)}
    <text x="5" y="25" fill="#8e9eb8" fontSize="10">kW</text>
    {([['load', '#8e9bad'], ['pv', '#eebd62'], ['grid', '#80baff']] as const).map(([key, color]) => <polyline key={key} points={rows.map(h => point(h.hour, h[key])).join(' ')} fill="none" stroke={color} strokeWidth="2.8" />)}
    <line x1={45 + selected / 23 * 650} x2={45 + selected / 23 * 650} y1="34" y2="280" stroke="#cadcf9" strokeDasharray="4 4" />
    <text x="5" y="245" fill="#8e9eb8" fontSize="10">SOC</text>
    <polyline points={rows.map(h => `${45 + h.hour / 23 * 650},${282 - h.soc / Math.max(1, ...rows.map(x => x.soc)) * 42}`).join(' ')} fill="none" stroke="#a6d8c9" strokeWidth="2.5" />
    {[0, 6, 12, 18, 23].map(h => <text key={h} x={45 + h / 23 * 650} y="303" textAnchor="middle" fill="#8e9eb8" fontSize="10">{String(h).padStart(2, '0')}:00</text>)}
  </svg>;
}
function GridDemo({ locale }: { locale: Locale }) {
  const t = (zh: string, en: string) => choose(locale, zh, en); const [scenario, setScenario] = useState<GridScenario>({ ...INITIAL_GRID }); const [strategy, setStrategy] = useState<'self' | 'tariff'>('tariff'); const [tab, setTab] = useState('curves'); const [selected, setSelected] = useState(18);
  const result = useMemo(() => simulateGrid(scenario, strategy), [scenario, strategy]); const self = useMemo(() => simulateGrid(scenario, 'self'), [scenario]); const tariff = useMemo(() => simulateGrid(scenario, 'tariff'), [scenario]); const none = useMemo(() => simulateGrid({ ...scenario, power: 0 }, 'self'), [scenario]);
  const h = result.hours[selected]; const maxError = Math.max(...result.hours.map(row => Math.abs(row.balanceError)));
  const reset = () => { setScenario({ ...INITIAL_GRID }); setStrategy('tariff'); setTab('curves'); setSelected(18); };
  const slider = (key: keyof Omit<GridScenario, 'outage'>, label: string, min: number, max: number, step: number, display: string) => <Field label={`${label} · ${display}`}><input type="range" aria-label={label} min={min} max={max} step={step} value={scenario[key]} onChange={e => setScenario(s => ({ ...s, [key]: Number(e.target.value) }))} /></Field>;
  return <div className="advanced-ops op-grid"><Header code="FLUX / MICROGRID" title={t('让每一度电都有去向', 'Account for every kilowatt-hour')} subtitle={t('24小时负荷、光伏与储能 · 效率损耗入账 · 停电缺口可见', '24-hour load, PV and storage · Efficiency losses accounted for · Outage gaps visible')} reset={reset} locale={locale} />
    <Metrics items={[[t('净电费', 'Net energy cost'), money(result.cost), `${money(none.cost - result.cost)} ${t('较无储能节省', 'saved vs no storage')}`], [t('最大购电功率', 'Peak import'), `${number(result.peak, 1)} kW`], [t('购电碳排', 'Import emissions'), `${number(result.carbon, 1)} kg CO₂`], [t('未供电量', 'Unserved energy'), `${number(result.unserved, 1)} kWh`, maxError < 1e-8 ? t('24/24 小时电量守恒', '24/24 hours balanced') : t('电量存在残差', 'Energy residual detected')]]} />
    <div className="op-grid-layout"><aside className="op-panel op-scenario"><h4>{t('情景参数', 'SCENARIO INPUTS')}</h4>{slider('demand', t('用电需求', 'Load factor'), .4, 1.8, .1, `${number(scenario.demand * 100)}%`)}{slider('solar', t('光伏发电', 'PV factor'), 0, 1.6, .1, `${number(scenario.solar * 100)}%`)}{slider('capacity', t('储能容量', 'Storage capacity'), 20, 200, 10, `${scenario.capacity} kWh`)}{slider('power', t('充放电功率', 'Charge/discharge power'), 0, 60, 2, `${scenario.power} kW`)}{slider('initialSOC', t('初始电量', 'Initial SOC'), .1, 1, .1, `${number(scenario.initialSOC * 100)}%`)}<Field label={t('运行策略', 'Dispatch policy')}><select value={strategy} onChange={e => setStrategy(e.target.value as typeof strategy)}><option value="self">{t('自用优先', 'Self-consumption')}</option><option value="tariff">{t('峰谷电价', 'Time-of-use tariff')}</option></select></Field><label className="op-check"><input type="checkbox" checked={scenario.outage} onChange={e => setScenario(s => ({ ...s, outage: e.target.checked }))} />{t('18–20点电网停电', 'Grid outage 18:00–20:59')}</label><p className="op-footnote">{t('最低SOC 10% · 充/放效率各95% · 峰段 ¥1.45 / 谷段 ¥0.38 · 售电 ¥0.20/kWh', 'Min SOC 10% · Charge/discharge efficiency 95% each · Peak ¥1.45 / off-peak ¥0.38 · Export ¥0.20/kWh')}</p></aside>
    <div><Tabs value={tab} set={setTab} items={[[ 'curves', t('调度曲线', 'Dispatch curves') ], ['ledger', t('逐时账本', 'Hourly ledger')], ['compare', t('策略对照', 'Policy comparison')]]} />
    {result.unserved > 0 && <Notice alert>{t(`情景存在 ${number(result.unserved, 1)} kWh 未供电量。可增加储能容量/功率或降低需求，规则策略不保证消除缺口。`, `The scenario leaves ${number(result.unserved, 1)} kWh unserved. Increase storage capacity/power or reduce demand; rule-based policies do not guarantee elimination of shortfalls.`)}</Notice>}
    {tab === 'curves' && <Panel title={t('真实计算曲线 / 1小时步长', 'CALCULATED CURVES / ONE-HOUR STEPS')}><div className="op-chart-legend"><span style={{ color: '#8e9bad' }}>● {t('负荷', 'Load')}</span><span style={{ color: '#eebd62' }}>● PV</span><span style={{ color: '#80baff' }}>● {t('购电', 'Import')}</span><span style={{ color: '#a6d8c9' }}>● SOC</span></div><EnergyChart rows={result.hours} selected={selected} locale={locale} /><Field label={`${t('选中小时', 'Selected hour')} · ${String(selected).padStart(2, '0')}:00`}><input type="range" min="0" max="23" value={selected} onChange={e => setSelected(Number(e.target.value))} /></Field><div className="op-hour-flow"><div><small>PV + {t('购电', 'import')} + {t('放电', 'discharge')}</small><strong>{number(h.pv, 1)} + {number(h.grid, 1)} + {number(h.discharge, 1)}</strong></div><b>=</b><div><small>{t('已供负荷 + 充电 + 售/弃电', 'Served load + charge + export/curtail')}</small><strong>{number(h.load - h.unserved, 1)} + {number(h.charge, 1)} + {number(h.exported, 1)}</strong></div></div><p className="op-footnote">SOC {number(h.soc, 1)} kWh · {t('电价', 'Tariff')} ¥{h.tariff}/kWh · {t('未供电', 'Unserved')} {number(h.unserved, 1)} kWh</p></Panel>}
    {tab === 'ledger' && <Panel title={t('每小时能量与储能状态', 'HOURLY ENERGY AND STORAGE STATE')}><div className="op-table-wrap"><table><thead><tr>{[t('小时', 'Hour'), t('负荷', 'Load'), 'PV', t('购电', 'Import'), t('充 / 放', 'Charge / discharge'), 'SOC', t('缺口', 'Unserved')].map(s => <th key={s}>{s}</th>)}</tr></thead><tbody>{result.hours.map(row => <tr key={row.hour} className={row.unserved > 0 ? 'op-row-alert' : ''}><td>{String(row.hour).padStart(2, '0')}:00</td><td>{number(row.load, 1)}</td><td>{number(row.pv, 1)}</td><td>{number(row.grid, 1)}</td><td>{number(row.charge, 1)} / {number(row.discharge, 1)}</td><td>{number(row.soc, 1)}</td><td>{number(row.unserved, 1)}</td></tr>)}</tbody></table></div><p className="op-footnote">{t('所有能量列为 kWh（1小时步长）；守恒使用未四舍五入值。', 'Energy columns are kWh (one-hour steps); conservation uses unrounded values.')}</p></Panel>}
    {tab === 'compare' && <Panel title={t('同一情景，三种结果', 'ONE SCENARIO, THREE OUTCOMES')}><div className="op-table-wrap"><table><thead><tr>{[t('策略', 'Policy'), t('净电费', 'Net cost'), t('峰值kW', 'Peak kW'), t('碳排kg', 'CO₂ kg'), t('缺口kWh', 'Unserved kWh')].map(s => <th key={s}>{s}</th>)}</tr></thead><tbody>{[[t('无储能', 'No storage'), none], [t('自用优先', 'Self-consumption'), self], [t('峰谷电价', 'Time-of-use'), tariff]].map(([label, data]) => { const d = data as typeof result; return <tr key={String(label)}><td>{String(label)}</td><td>{money(d.cost)}</td><td>{number(d.peak, 1)}</td><td>{number(d.carbon, 1)}</td><td>{number(d.unserved, 1)}</td></tr>; })}</tbody></table></div><div className="op-cost-bars">{[[t('无储能', 'No storage'), none], [t('自用优先', 'Self-consumption'), self], [t('峰谷电价', 'Time-of-use'), tariff]].map(([label, data]) => { const d = data as typeof result; return <div key={String(label)}><span>{String(label)}</span><progress max={Math.max(1, none.cost, self.cost, tariff.cost)} value={Math.max(0, d.cost)} /><b>{money(d.cost)}</b></div>; })}</div><Notice>{t('较低电费不一定代表更低碳排或更强停电韧性。三组均使用相同输入；规则策略并非全局最优。', 'Lower cost does not necessarily mean lower emissions or stronger outage resilience. All three share identical inputs; policies are not globally optimal.')}</Notice></Panel>}
    </div></div><Notice>{t('本地合成预测，无真实交易或电网控制。未计设备老化、需量费、电网约束与预测误差。SOC 曲线独立归一化；数值以账本为准。', 'Local synthetic forecasts, no real trading or grid control. Excludes degradation, demand charges, network constraints and forecast error. The SOC curve has an independent normalized scale; use ledger values.')}</Notice>
  </div>;
}

export function AdvancedOperationsDemo({ id, locale }: AdvancedDemoProps) {
  if (id === 'dispatch-network') return <DispatchDemo locale={locale} />;
  if (id === 'commerce-ops') return <CommerceDemo locale={locale} />;
  if (id === 'factory-orchestrator') return <FactoryDemo locale={locale} />;
  if (id === 'grid-balance') return <GridDemo locale={locale} />;
  return null;
}
