import { bilingual as l, type AdvancedCase, type AdvancedWorkflowStep } from './types';
import type { Localized } from '../officialWorkflows';

interface IndustrySpec {
  id: string; title: Localized; industry: Localized; accent: string; summary: Localized; brief: Localized;
  capabilities: Localized[]; datasets: Localized[]; domain: Localized; visual: Localized; checks: Localized; artifacts: Localized[]; limitations: Localized;
}
function workflow(spec: IndustrySpec): AdvancedWorkflowStep[] {
  const step = (id: string, title: Localized, role: AdvancedWorkflowStep['role'], after: string[], task: Localized, output: Localized, acceptance: Localized[], outputType?: 'html'): AdvancedWorkflowStep => ({ id, title, role, after, task, output, acceptance, ...(outputType ? { outputType } : {}) });
  const sourceNotes = l('说明最多 400 中文字或 200 英文词；只写接口、假设与未验证项，不重述上游文档，不用字符画、伪代码或成功自述代替源码。边界用例区分预期值与实际观测；没有执行证据的用例标为待执行。', 'Limit explanation to 400 Chinese characters or 200 English words: interfaces, assumptions and unverified items only. Do not repeat upstream documents or replace source with ASCII art, pseudocode or success claims. Separate expected fixture values from observations; label cases without execution evidence as not executed.');
  const htmlOnly = l('只输出一个完整 HTML 文档；需要保留的修复说明、零变更说明和未验证项放在 HTML 注释或页面内，不能在文档前后附报告。', 'Output one complete HTML document only. Put repair notes, zero-change notes and unverified items inside HTML comments or the page, never in a report before or after the document.');
  return [
    step('scope', l('行业问题与交付边界', 'Industry scope and delivery boundary'), 'general', [], spec.brief, l('领域 brief、计算口径和操作清单', 'Domain brief, calculation conventions and action inventory'), [l('明确合成数据、本地状态及行业简化假设', 'Make synthetic data, local state and domain simplifications explicit')]),
    step('data', l('合成数据与引用完整性', 'Synthetic data and referential integrity'), 'materials', ['scope'], l(`建立并校验固定种子样例：${spec.datasets.map(d => d.zh).join('；')}。每实体有稳定 ID，重置恢复同一基线；拒绝负数与无效引用。`, `Create and validate deterministic samples: ${spec.datasets.map(d => d.en).join('; ')}. Use stable entity IDs, deterministic reset and invalid-reference/nonnegative checks.`), l('带字段定义、单位和边界样本的数据模块', 'Data module with field definitions, units and boundary fixtures'), [l('关系引用可解析，异常样例可以复现', 'References resolve and exception fixtures are reproducible')]),
    step('model', l('业务约束与算法设计', 'Business constraints and algorithm design'), 'general', ['scope'], spec.domain, l('纯函数签名、状态转换与不变量', 'Pure function signatures, transitions and invariants'), [spec.checks]),
    step('ux', l('行业视图与交互协议', 'Industry views and interaction contract'), 'frontend', ['scope'], spec.visual, l('视图层级、筛选选中态和可访问性协议', 'View hierarchy, selection state and accessibility contract'), [l('控件都有可见结果；状态跨视图同步；支持键盘和窄屏', 'Controls have observable outcomes; views share state; keyboard and narrow layouts work')]),
    step('engine', l('实现约束计算内核', 'Implement the constrained calculation engine'), 'frontend', ['data', 'model'], l(`按数据定义实现不依赖 UI 的纯计算和不可变状态更新。${spec.domain.zh} 禁止硬编码结果指标；错误返回可显示的原因。交付完整浏览器 JavaScript 源码及必要的样例数据，不能只给算法说明。提供统一对象 AwwOEngine：createInitialState() 返回固定初态；transition(state, action) 返回 {state, error}，非法操作保留原状态；derive(state) 返回全部视图共用的真实计算结果。列出各 action 的类型与字段，保留所有行业算法、数据规模和异常路径；不依赖模块导入、TypeScript 编译或外部包。${sourceNotes.zh}`, `Implement UI-independent calculations and immutable updates from the data schema. ${spec.domain.en} Do not hard-code result metrics; return displayable error reasons. Deliver complete browser JavaScript source and required fixtures, not just algorithm descriptions. Provide AwwOEngine: createInitialState() returns deterministic initial state; transition(state, action) returns {state, error}, retaining the original state on invalid actions; derive(state) returns actual calculations shared by all views. List action types and fields; preserve every domain algorithm, dataset size and exception path. Require no module imports, TypeScript compilation or external packages. ${sourceNotes.en}`), l('浏览器计算源码、统一接口与边界用例', 'Browser calculation source, shared API and boundary fixtures'), [spec.checks, l('AwwOEngine 的三个函数完整实现；预期结果不冒充运行记录', 'All three AwwOEngine functions are implemented; expected results are not execution records')]),
    step('views', l('实现联动视图与图形', 'Implement linked views and graphics'), 'frontend', ['data', 'ux'], l(`${spec.visual.zh} 本节点是实际视图实现，不是再次设计。交付可直接组装的 DOM 模板、内嵌 CSS、SVG 绘图和浏览器 JavaScript 源码，包含全部视图、双语文案、表单、选择、键盘、重置及错误反馈。实现 mountViews(root, api)，api 提供 getState()、getViewModel()、dispatch(action)、reset()；返回 render() 与 destroy()，前者按最新状态重绘，后者移除事件监听、计时器和动画。所有控件通过 api 更新真实状态，图表读取 getViewModel() 的真实结果；列出所需字段和 action，供构建节点适配 AwwOEngine，不在视图中另造计算内核或硬编码 KPI。不依赖框架、模块导入、TypeScript 编译、外部资源或网络。${sourceNotes.zh}`, `${spec.visual.en} This node implements views; it does not repeat design work. Deliver directly composable DOM templates, inline CSS, SVG drawing and browser JavaScript source for every view, bilingual copy, forms, selection, keyboard control, reset and error feedback. Implement mountViews(root, api); api provides getState(), getViewModel(), dispatch(action), reset(). Return render() to redraw current state and destroy() to remove listeners, timers and animations. All controls update real state through api; charts use actual getViewModel() results. List required fields and actions so the build node can adapt AwwOEngine; do not duplicate the calculation engine or hard-code KPIs in views. Require no framework, module imports, TypeScript compilation, external resources or network. ${sourceNotes.en}`), l('可组装的 DOM/CSS/JavaScript 视图源码', 'Composable DOM/CSS/JavaScript view source'), [l('mountViews 实际绑定所有操作并渲染计算结果；无设计稿、字符画或伪代码替代实现', 'mountViews binds all actions and renders calculated results; design documents, ASCII art and pseudocode cannot substitute for implementation'), l('图形来自实际计算数据；无外部图片、凭证或请求', 'Graphics use actual calculations; no external images, credentials or requests')]),
    step('build', l('合成完整行业原型', 'Assemble the complete industry prototype'), 'frontend', ['engine', 'views'], l(`汇合计算内核和所有视图，生成完整的独立 HTML，内嵌 CSS、SVG 与脚本。连接所有输入、异常提示、状态流、对比和重置；说明数据和单位。若上游只有规格、片段或接口不一致，必须补齐全部视图、事件、数据和计算连接，将 TypeScript 转成浏览器可直接执行的 JavaScript，并适配 AwwOEngine 与 mountViews；不能原样拼接说明或留下 TODO、占位按钮、伪代码、静态假指标。保留完整 brief 的行业算法、数据规模和功能，不为缩短文件删减异常路径。无工具调用或执行证据时仅作静态核对，交互测试标为待执行，不声称已运行通过。${htmlOnly.zh}`, `Combine the calculation engine and views into complete standalone HTML with inline CSS, SVG and scripts. Wire inputs, errors, transitions, comparisons and reset; explain data and units. Implement missing views, events, data and calculation bindings when upstream content contains only specifications, fragments or incompatible interfaces. Convert TypeScript to directly executable browser JavaScript and adapt AwwOEngine to mountViews; do not concatenate prose or leave TODOs, placeholder controls, pseudocode or fake metrics. Preserve the complete brief's domain algorithms, dataset sizes and features; do not remove exception paths to shorten the file. Without tool calls or execution evidence, perform static review only and label interaction checks as not executed rather than claiming they passed. ${htmlOnly.en}`), l('完整可运行行业系统 HTML', 'Complete runnable industry-system HTML'), [l('完整 html/head/body，所有依赖内嵌，初始状态可交互', 'Complete html/head/body, embedded dependencies and interactive initial state'), l('所有视图和事件有实际源码；接口适配且不含未编译 TypeScript；运行记录须有执行证据', 'Every view and event has source; interfaces are adapted with no uncompiled TypeScript; execution claims require evidence')], 'html'),
    step('checks', l('业务不变量与交互审查', 'Business invariant and interaction review'), 'review', ['scope', 'model', 'engine', 'build'], l(`逐项复核模型及 HTML。${spec.checks.zh} 另查重置、双语、键盘、窄屏和异常提示。能运行则记录步骤与结果；不能运行仅报告静态发现。`, `Review the model and HTML. ${spec.checks.en} Also check reset, both languages, keyboard, narrow layouts and errors. Record execution evidence when possible; otherwise report static findings only.`), l('带严重性、复现条件和证据的检查报告', 'Review report with severity, reproduction conditions and evidence'), [l('计算错误和未验证项显式列出，不编造成功记录', 'List calculation errors and unverified areas without invented success records')]),
    step('repair', l('修复并保留完整成果', 'Repair while preserving the complete artifact'), 'frontend', ['build', 'checks'], l(`逐条处理检查报告，优先修复状态非法转换、计算不守恒和视图不一致；无缺陷时仍回传完整原始 HTML 和零变更说明。输出完整文件，不能只输出补丁。${htmlOnly.zh}`, `Address review findings, prioritizing invalid transitions, conservation errors and inconsistent views. With no defects, still return the complete original HTML and a zero-change note. Output the whole file, not a patch. ${htmlOnly.en}`), l('修复后完整 HTML 与修复说明', 'Complete repaired HTML and repair notes'), [l('每条发现有处理结果；保留失败边界提示', 'Every finding has a disposition; failure boundaries remain visible')], 'html'),
    step('recheck', l('回归与残余风险复核', 'Regression and residual-risk review'), 'review', ['repair', 'checks', 'model'], l(`对修复后完整文件重新核对：${spec.checks.zh} 标识已验证、静态通过和未验证项；本节点正常顺序执行，不依赖后端条件分支。`, `Recheck the complete repaired file: ${spec.checks.en} Distinguish executed, statically reviewed and unverified results. This is a normal sequential node, not a backend conditional branch.`), l('最终回归记录与残余风险', 'Final regression record and residual risks'), [l('未验证项不会被标记为已通过', 'Unverified areas are not marked as passed')]),
    step('deliver', l('交付行业演示文件', 'Deliver the industry demonstration'), 'frontend', ['repair', 'recheck', 'scope'], l(`引用修复后的完整 HTML 和复核记录，交付最终完整文件，页面内保留合成数据与本地边界说明。如有未解决问题，说明限制而非伪称已发布。${htmlOnly.zh}`, `Use the complete repaired HTML and regression record to deliver the final file with synthetic-data and local-only notes. Describe unresolved limitations instead of claiming a production release. ${htmlOnly.en}`), l('最终完整行业演示 HTML', 'Final complete industry demonstration HTML'), [l('交付引用最新复核证据且可独立打开', 'Delivery references the latest review evidence and opens independently')], 'html'),
    step('guide', l('领域替换与接入指南', 'Domain customization and integration guide'), 'general', ['deliver', 'recheck', 'data'], l('说明输入数据、算法假设、操作路径、已知限制以及真实 API 接入前需独立验证的内容。保留实际交付文件引用；不要声称具备真实调度、交易、工厂或电网控制权限。', 'Document inputs, algorithm assumptions, workflows, limitations and validation required before real API integration. Reference the delivered file; claim no real dispatch, transaction, factory or grid-control authority.'), l('数据字典、运行指南和扩展清单', 'Data dictionary, usage guide and extension checklist'), [spec.limitations]),
  ];
}
const specs: IndustrySpec[] = [
  {
    id: 'dispatch-network', title: l('NEXUS / 城市配送控制塔', 'NEXUS / Urban dispatch control'), industry: l('供应链 · 物流', 'Supply chain · Logistics'), accent: '#69d7ba',
    summary: l('两仓四车八订单，在有向路网中执行容量与时窗约束，封路后重新分配并解释准点率变化。', 'Two depots, four trucks and eight orders: route through a directed network with capacity and time windows, then replan after disruption.'),
    brief: l('构建城市配送控制塔：8个路网节点、24条方向独立计时的道路、2仓、4车、8张带重量和可送达时窗的订单。用 Dijkstra 算最短时间路径，以到期优先或近点优先贪心分配，硬性限制车仓归属和每车整趟总装载。显示真实路线、到达分钟、迟到和未分配原因。允许切断双向桥梁、孤立配送点、切换策略与收紧时窗；每次修改重新计算并清空旧派车进度。提供路网、配送明细、策略对比和派车进度视图；推进只改变本地计划状态，不发送真实调度。单程多站路线不包含回仓，也不声称全局最优。', 'Build an urban dispatch control tower with 8 graph nodes, 24 direction-specific roads, 2 depots, 4 trucks and 8 orders with weight and delivery windows. Use Dijkstra shortest-time paths and deadline-first or nearest-first greedy assignment, enforcing depot ownership and total trip payload. Show routes, arrival minutes, lateness and unassigned orders. Support bridge closure, destination isolation, strategy changes and tighter windows; recalculate and clear dispatch progress on each scenario change. Provide network, manifest, comparison and dispatch views. Progress is local only. One-way multi-stop routes exclude depot return and make no global-optimality claim.'),
    capabilities: [l('有向最短路', 'Directed shortest paths'), l('多仓车队容量', 'Multi-depot fleet capacity'), l('订单时窗与迟到', 'Delivery windows and lateness'), l('交通中断重算', 'Disruption replanning'), l('贪心策略对比', 'Greedy strategy comparison'), l('地图路线联动', 'Linked route map'), l('本地派车进度', 'Local dispatch progress')],
    datasets: [l('8节点 / 24有向道路', '8 nodes / 24 directed roads'), l('2仓 / 4车及载重与公里成本', '2 depots / 4 trucks with capacity and kilometre costs'), l('8订单及重量、就绪时间与截止时间', '8 orders with weight, ready time and deadlines')],
    domain: l('Dijkstra 按行驶分钟找路径；候选车必须同仓且累计装载不超容量。候选评分为迟到分钟×20+增量公里成本，等待订单就绪、停靠6分钟；不可达和超载不得偷偷纳入计划。', 'Dijkstra minimizes travel minutes. Candidate trucks must share the depot and remain within total payload. Score lateness×20 plus incremental distance cost; wait until ready and allow six-minute stops. Unreachable or overcapacity orders stay unassigned.'),
    visual: l('设计深绿调度台：可选车辆彩色路线、箭头道路、关闭道路和节点；配送表显示每站窗口与到达；策略面板比较距离成本和准点率；派车按计划→途中→完成推进，异常重算清空进度。', 'Design a dark green dispatch desk with selected colored truck routes, directional roads and closed links. Show per-stop windows and arrivals, compare cost and on-time performance, and advance planned→en route→complete status. Replanning clears progress.'),
    checks: l('检查有向不可达、封路绕行、容量硬限制、同仓约束、到达不早于就绪和迟到计数；修改情景后不沿用旧派车状态。', 'Check directed disconnection, detours, capacity and depot constraints, arrivals no earlier than ready time, lateness counts and cleared progress after scenario changes.'),
    artifacts: [l('互动配送路网', 'Interactive delivery network'), l('车辆路线与订单清单', 'Vehicle routes and manifest'), l('中断与策略对比报告', 'Disruption and strategy comparison')],
    limitations: l('固定合成路网；贪心单程多站计划，不是车辆路径全局最优解，无实时交通/GPS/真实派车。', 'Fixed synthetic network; greedy one-way multi-stop plans, not a globally optimal vehicle-routing solution. No live traffic, GPS or real dispatch.'),
  },
  {
    id: 'commerce-ops', title: l('MERIDIAN / 全渠道零售履约', 'MERIDIAN / Omnichannel fulfillment'), industry: l('零售 · 商业运营', 'Retail · Commerce operations'), accent: '#df9670',
    summary: l('从多 SKU 购物篮到预留、审批、发货、退货退款，库存、利润与跨仓调拨始终对账。', 'Move a multi-SKU basket through reservation, approval, shipping, return and refund while reconciling inventory and margin.'),
    brief: l('构建全渠道零售履约台：4 SKU、3仓、3个初始订单，支持 WEB/STORE/MARKET 渠道创建多SKU草稿。满500的示例优惠券减10%，优惠后满600免18运费，商品净额税率6%，毛利扣货品成本和18物流成本，税不计利润。预留必须原子检查库存；审批后才发货，发货扣现货；退货入库后才退款，重复操作拒绝；取消释放预留。调拨只能使用未预留库存，禁止同仓和超额。提供订单、库存调拨、购物篮和财务视图、操作记录、异常与重置。所有状态在浏览器内，无真实支付、税务服务或持久化。', 'Build a fulfillment desk with 4 SKUs, 3 warehouses and 3 initial orders. Create multi-SKU drafts from WEB/STORE/MARKET channels. A sample coupon discounts 10% above 500; net goods above 600 receive free shipping otherwise 18; goods tax is 6%; margin excludes tax and deducts product cost plus 18 logistics cost. Reserve atomically, approve before shipping, deduct on-hand stock on shipment, restock returns before refund and reject duplicate transitions. Cancellation releases reservations. Transfer only free stock and reject same-warehouse or oversized transfers. Provide orders, inventory, basket and finance views, event log, errors and reset. Browser-only state, no real payment, tax service or persistence.'),
    capabilities: [l('多SKU购物篮', 'Multi-SKU baskets'), l('跨渠道订单', 'Cross-channel orders'), l('原子库存预留', 'Atomic stock reservation'), l('履约与退货状态机', 'Fulfillment and return state machine'), l('优惠税费与毛利', 'Discount, tax and margin'), l('可用库存跨仓调拨', 'Transfer available stock'), l('业务事件审计', 'Business event audit')],
    datasets: [l('4个SKU与价格/成本', '4 SKUs with prices and costs'), l('3仓12组库存', '3 warehouses / 12 stock balances'), l('3个渠道及初始订单', '3 channels and initial orders')],
    domain: l('库存可用量=现货−预留和已审批订单；预留全单成功或全单失败。合法状态为草稿→预留→审批→发货→退货→退款，前三态可取消。发货减现货，退货加现货，退款不再次加库存。', 'Available stock equals on-hand minus reserved and approved orders. Reservation succeeds or fails for the entire order. Valid states are draft→reserved→approved→shipped→returned→refunded; the first three may cancel. Shipping deducts stock, returning adds it, and refunding never adds stock again.'),
    visual: l('暖色商业工作台：订单状态轨道与订单详情、SKU购物篮明细计价、三仓库存矩阵和调拨表单、收入退款与毛利对账。选单后操作按钮严格随状态变化，错误原因可见。', 'Build a warm commerce workspace with order state tracks and details, basket price breakdowns, a three-warehouse stock matrix and transfer form, plus revenue/refund/margin reconciliation. Available actions follow the selected order state; error reasons remain visible.'),
    checks: l('验证超卖拒绝且无部分预留、取消释放、发货扣减、退货只入库一次、重复退款拒绝、调拨总库存守恒、优惠阈值与税费口径。', 'Test rejected overselling without partial reservations, release on cancellation, shipment deduction, single return restocking, duplicate-refund rejection, transfer conservation, coupon thresholds and tax conventions.'),
    artifacts: [l('多渠道履约系统', 'Multi-channel fulfillment system'), l('库存与财务对账视图', 'Inventory and financial reconciliation'), l('状态机与事件记录', 'State machine and event records')],
    limitations: l('本地合成商品与人民币示例规则，无真实税务或退款操作；同步调拨与整单退货，不含部分履约、支付或权限服务。', 'Local synthetic goods and illustrative CNY rules; no real tax or refund action. Transfers are immediate and returns cover whole orders. No partial fulfillment, payments or authorization service.'),
  },
  {
    id: 'factory-orchestrator', title: l('FORGE / 排产与质量协同', 'FORGE / Production and quality'), industry: l('制造 · 工业运营', 'Manufacturing · Industrial operations'), accent: '#e4b04e',
    summary: l('BOM 用料、班次产能、设备停机和工序依赖共同生成甘特图，再用质量门控制交付。', 'BOM materials, shift capacity, downtime and operation dependencies produce a Gantt plan with a quality gate for delivery.'),
    brief: l('构建制造排产质量台：3产品BOM、3种原料、6订单、4设备；每单切割→装配→测试，双装配单元选择最早空闲机器。按交期顺序，先验证整单物料再扣料；物料不足或单工序超过班次容量的订单阻塞而不消耗物料。在24小时日历中支持8/10/12小时班次，停机时间不可重叠作业；提供甘特图、物料需求、交付与质量视图。可补充原料、切换班次、制造停机重排；这些修改使旧质检与放行失效。抽检通过后才能本地放行，不合格整批隔离，可重新检测。显示截止时刻、迟交风险和基线对比。合成离散计划，不控制真实设备，无自动优化最优性承诺。', 'Build a production and quality desk with 3 product BOMs, 3 materials, 6 orders and 4 machines. Every order follows cut→assemble→test; choose the earliest available of two assembly cells. Process orders by due date, verify all materials before consumption and block shortages or operations exceeding shift capacity without consuming materials. Use 24-hour days with 8/10/12-hour shifts and non-overlapping machine downtime. Provide Gantt, materials and delivery/quality views. Replenish materials, change shifts and simulate breakdowns; all replanning invalidates prior quality and release decisions. Passing a local sample check permits release, failure quarantines the whole batch, and reinspection is possible. Show deadlines, late risks and baseline comparison. Synthetic discrete planning only, no equipment control or optimality claim.'),
    capabilities: [l('多产品BOM物料约束', 'Multi-product BOM constraints'), l('工序依赖排程', 'Operation dependency scheduling'), l('并行设备选择', 'Parallel machine selection'), l('班次日历与停机', 'Shift calendars and downtime'), l('可追溯甘特图', 'Traceable Gantt chart'), l('质检隔离与放行', 'Quality quarantine and release'), l('交期风险与重排', 'Delivery risk and replanning')],
    datasets: [l('3产品 × 3原料BOM', '3 products × 3 material BOMs'), l('6生产订单及数量/交期', '6 production orders with quantities and due dates'), l('4设备 / 3道依赖工序', '4 machines / 3 dependent operations')],
    domain: l('按到期日串行选单，物料不足不占用设备；每单工序严格前后依赖，同机器不能重叠，工序不能跨班次或停机。质量状态为待检/合格/隔离；只有已排程且合格的订单可放行。', 'Select orders by due date; shortages occupy no machine capacity. Respect per-order dependencies, non-overlapping machines, shift boundaries and downtime. Quality is pending/pass/quarantine; release only scheduled, passing orders.'),
    visual: l('工业金色工作台：按设备分行的真实甘特图，选择订单突出其工序；物料面板展示BOM、余量、补料和阻塞原因；质量表显示完成时刻、交期、抽检/隔离/放行。', 'Use an industrial gold workspace with a machine-row Gantt chart and selected-order highlighting. Materials show BOMs, remaining stock, replenishment and blocking reasons. Quality rows show completion, deadline, sampling, quarantine and release.'),
    checks: l('验证工序先后、设备互斥、班次与停机避让、物料不为负、不足订单不扣料、不合格不能放行、重排使旧质检失效。', 'Verify operation precedence, machine exclusion, shift and downtime avoidance, nonnegative materials, no consumption by blocked orders, no release of failed batches and invalidation of quality on replanning.'),
    artifacts: [l('生产排程与甘特图', 'Production schedule and Gantt chart'), l('BOM与物料约束报告', 'BOM and material-constraint report'), l('质量门与交付风险', 'Quality gate and delivery risks')],
    limitations: l('样例串行优先级启发式，工序不可拆分；质检为人工模拟判定，无真实MES、设备控制或统计抽样合规认证。', 'Sample priority-list heuristic with indivisible operations. Quality checks are manually simulated; no real MES, equipment control or statistical sampling certification.'),
  },
  {
    id: 'grid-balance', title: l('FLUX / 微电网调度实验室', 'FLUX / Microgrid dispatch lab'), industry: l('能源 · 基础设施', 'Energy · Infrastructure'), accent: '#87bdff',
    summary: l('编辑24小时用能情景，比较自用优先与分时电价策略，并核对每小时电量守恒和停电缺口。', 'Edit a 24-hour energy scenario, compare self-consumption and tariff policies, and verify hourly energy balance and outage shortfalls.'),
    brief: l('构建微电网调度实验室：24小时合成负荷、光伏和三段电价，储能容量/功率/初始SOC可调，最低SOC为10%，充放电效率各95%。自用策略优先消纳光伏后放电；电价策略谷时充至90%、峰时放电；停电18–20点禁止购电并显示未供电量。每小时限制充放电功率与SOC，禁止同时充放电；曲线和表格展示负荷、PV、购电、充放电、SOC、弃售电与缺口。计算进口电费减售电收入、进口碳排和最高购电功率；对照两策略与无储能基线。允许调节需求、光伏、容量、功率、初始SOC和停电，重置恢复固定样例。清楚标注小时步长、合成预测及无真实电网控制。', 'Build a microgrid dispatch lab with 24 synthetic hourly load/PV samples and three tariff periods. Edit storage capacity, power and initial SOC; minimum SOC is 10% and charge/discharge efficiency is 95% each. Self-use consumes PV and discharges against deficits; tariff policy charges to 90% at off-peak hours and discharges at peak. An 18–20 outage prohibits imports and exposes unserved energy. Enforce hourly power/SOC limits and prevent simultaneous charge/discharge. Charts and tables show load, PV, imports, storage flows, SOC, export/curtailment and shortfall. Calculate import cost minus export revenue, import emissions and peak demand; compare both policies and a no-storage baseline. Edit demand/PV factors, capacity, power, initial SOC and outage; reset deterministic samples. State hourly resolution, synthetic forecasts and no real grid control.'),
    capabilities: [l('24小时负荷与光伏', '24-hour load and PV'), l('SOC与效率约束', 'SOC and efficiency constraints'), l('峰谷电价策略', 'Time-of-use tariff policy'), l('停电与未供电量', 'Outage and unserved energy'), l('逐时电量守恒', 'Hourly energy conservation'), l('成本碳排与削峰', 'Cost, emissions and peak shaving'), l('多情景曲线对比', 'Scenario curve comparison')],
    datasets: [l('24小时合成负荷与日照曲线', '24-hour synthetic load and sunlight curves'), l('三段电价及售电价0.2元/kWh', 'Three tariff periods and 0.2 CNY/kWh export tariff'), l('90kWh/24kW储能默认参数', 'Default 90kWh/24kW storage parameters')],
    domain: l('每小时 PV+购电+放电=已供负荷+充电+售电/弃电；SOC增量=充电×0.95−放电/0.95。储能边界10%–100%，输入功率限制约束充放电。停电强制购电0，剩余缺口记未供电；策略为确定性规则而非数学最优调度。', 'Each hour PV+imports+discharge=served load+charge+export/curtailment. SOC change=charge×0.95−discharge/0.95. Keep SOC within 10%–100% and flows within power limits. During outages imports are zero and residual deficits become unserved energy. Policies are deterministic rules, not mathematical optimization.'),
    visual: l('蓝色能源实验台：负荷/PV/购电曲线与独立SOC曲线；逐时账本可选小时联动数值；策略对照面板显示成本、峰值、碳排与缺口；情景参数即时重算。', 'Build a blue energy lab with load/PV/import curves and a separate SOC chart. Selecting an hour links the hourly ledger and values; compare cost, peak, emissions and shortfall across policies. Scenario inputs recalculate immediately.'),
    checks: l('逐小时验证守恒残差接近0，SOC在上下界，充放电不同时发生且不超功率，停电无进口、低储能有缺口、零光伏/零功率仍有有限结果。', 'Verify near-zero hourly balance residuals, SOC bounds, mutually exclusive power-limited charge/discharge, zero outage imports, shortfalls with inadequate storage and finite outputs for zero PV/power.'),
    artifacts: [l('微电网调度与SOC曲线', 'Microgrid dispatch and SOC curves'), l('逐时能量平衡账本', 'Hourly energy-balance ledger'), l('策略成本与韧性对比', 'Policy cost and resilience comparison')],
    limitations: l('固定小时步长、合成预测、确定性规则；未计设备老化、需量费、电网约束或预测误差，无真实电力交易/控制。', 'Fixed hourly resolution, synthetic forecasts and deterministic policies. Excludes degradation, demand charges, network constraints and forecast error; no real energy trading or control.'),
  },
];
export const OPERATIONS_CASES: ReadonlyArray<AdvancedCase> = specs.map(spec => ({
  id: spec.id, category: 'operations', industry: spec.industry, title: spec.title, summary: spec.summary,
  description: spec.summary, pattern: l('领域定义 → 数据 / 模型 / 交互并行 → 内核与视图汇合 → 构建 → 检查 → 修复 → 回归 → 交付', 'Scope → parallel data/model/interaction → engine and view convergence → build → check → repair → regression → delivery'),
  brief: spec.brief, accent: spec.accent, capabilities: spec.capabilities, datasets: spec.datasets, artifacts: spec.artifacts,
  limitations: spec.limitations, steps: workflow(spec),
}));
