// Shared by the publish scripts: identifier redaction and the TypeScript module writer.
import fs from 'node:fs';

const UUID = /[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/gi;
// A Windows drive path such as C:/tmp/…, optionally behind a leading slash; never the scheme of a URL.
const DRIVE = String.raw`(?<![A-Za-z0-9])\/?[A-Za-z]:\/(?!\/)`;
const ARTIFACT_PATH = new RegExp(String.raw`${DRIVE}[^\s)\]]*?\/(artifacts\/[^\s)\]]+)`, 'g');
const LOCAL_PATH = new RegExp(String.raw`${DRIVE}(?:[^\s)\]]*\/)?([^\s/)\]]+)`, 'g');

/** Keep a local file reference's artifacts/<file> tail (or its file name), drop the machine path, and hide identifiers. */
export function redact(value) {
  return value.replace(ARTIFACT_PATH, '$1').replace(LOCAL_PATH, '$1').replace(UUID, '…');
}

/** Write a record as a typed module. JSON.stringify escapes every string, so outputs stay inert data. */
export function writeRecord(file, record) {
  fs.writeFileSync(file, `// Generated by scripts/showcase/ from a recorded run; do not edit by hand.\nimport type { ProductionRunRecord } from '../productionRuns';\n\nconst record: ProductionRunRecord = ${JSON.stringify(record, null, 2)};\nexport default record;\n`);
}

/** Keep production-runs/summary.json — what the homepage cards show without loading a record — in step. */
export function writeSummary(file, record, delivered) {
  const summary = fs.existsSync(file) ? JSON.parse(fs.readFileSync(file, 'utf8')) : {};
  summary[record.caseId] = { completed: record.completed, total: record.total, seconds: record.seconds, delivered, capturedOn: record.capturedOn, model: record.model, runtime: record.runtime };
  const ordered = Object.fromEntries(Object.keys(summary).sort().map(key => [key, summary[key]]));
  fs.writeFileSync(file, JSON.stringify(ordered, null, 2) + '\n');
}
